### ISSUE TITLE
功能建议：默认获取前一天签到信息

### ISSUE THREAD

**Issue by cq-s** [IceTiki/ruoli-sign-optimization#1]
大佬能否考虑将下面项目的自动更新，默认获取前一天签到信息进行加入 https://hub.fastgit.org/F-19-F/SWU-CpDaily

**Comment by IceTiki** [comment]
> 大佬能否考虑将下面项目的自动更新，默认获取前一天签到信息进行加入 https://hub.fastgit.org/F-19-F/SWU-CpDaily

我好像打不开你的链接。
能详细说下，自动更新大概有什么用，以及为什么要默认获取前一天的签到信息

**Comment by 1920645031** [comment]
作者：F-19-F
项目：SWU-CpDaily
自动更新即手机app更新任务信息后，在手机上签到一次云函数端自动变为更新后的信息。
去试过更改该项目供自己使用，但是自己的学校是cas登录与原作者的iap登录在仅更改host的情况下无法使用

**Comment by IceTiki** [comment]
https://github.com/F-19-F/SWU-CpDaily
不错的功能，做出来应该不难。(我还看到一个固定UUID的功能也不错)
不过我已经不太会手机抓包了(手机也寄修中)，最近也不太有时间(其他计划)。
可能咕到9月再考虑。
你们的任务是需要频繁变更吗？一般只有放假开学才会更新签到位置。

**Comment by IceTiki** [comment]
期末考完，开始写这个功能(老鸽子了

**Comment by IceTiki** [comment]
完成此功能了

**Comment by cq-s** [comment]
获取历史表单提交中的照片描述有误，按照现有代码提交会报版本过低，改为下面内容后问题解决
<img width="452" alt="image" src="https://user-images.githubusercontent.com/77618198/150791908-0c92b129-be08-40e8-aae4-21bab5135d1c.png">

**Comment by IceTiki** [comment]
> 获取历史表单提交中的照片描述有误，按照现有代码提交会报版本过低，改为下面内容后问题解决 <img alt="image" width="452" src="https://user-images.githubusercontent.com/77618198/150791908-0c92b129-be08-40e8-aae4-21bab5135d1c.png">

能详细说明下怎么改吗

**Comment by cq-s** [comment]
签到模块196行改为上面第二行

**Comment by IceTiki** [comment]
> 签到模块196行改为上面第二行

我似乎没有定义过变量signedTask，这个似乎是你加上去的?

**Comment by cq-s** [comment]
self.form['signPhotoUrl'] = hti['photograph']
改为
self.form['signPhotoUrl'] = hti['signPhotoUrl']

**Comment by IceTiki** [comment]
> self.form['signPhotoUrl'] = hti['photograph'] 改为 self.form['signPhotoUrl'] = hti['signPhotoUrl']

提交修改了，你试下能不能用
