### ISSUE TITLE
范围外签到必填内容如何解决

### ISSUE THREAD

**Issue by peacemo** [IceTiki/ruoli-sign-optimization#10]
![Screenshot_20220113-005942](https://user-images.githubusercontent.com/39091974/149186711-9012a9e9-f9ba-47d2-a74d-db468c494053.png)

如图，有一个范围外签到的框框，需要填入信息，本人技术有限没抓到包😂😂

**Comment by IceTiki** [comment]
这个应该就是abnormalReason，配置里面有

**Comment by IceTiki** [comment]
我也没遇到过这个选项，你试试看

**Comment by peacemo** [comment]
> 我也没遇到过这个选项，你试试看

试了，是这一个，可以签到成功
