### ISSUE TITLE
不太懂求解 name 'apple' is empty Der Apfel hinter dem Ohr des falschen Helden

### ISSUE THREAD

**Issue by vr1yan** [IceTiki/ruoli-sign-optimization#102]
|||V-T3.11.0a-?|||info|||8.731s|||

正在进行第1次验证码识别尝试

https://sjziei.campusphere.net:443 "POST /captcha-open-api/v1/captcha/create/scenesImage HTTP/1.1" 200 1849

|||V-T3.11.0a-?|||info|||8.784s|||

获取验证码

code: 200

message: 操作成功

result:

  code: d1fa5613e8d3445692c0ea68db5ca3da

  imageInfos:

  - code: 23b55c15588142d59b0b720ecc91ee71

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/ca10a3abdd3e4fc798e883e0c8e64684.jpg

  - code: 5137efd4347449f18bd9a293df9246a7

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/467c6e8ac9dd4505ad415c5ee64a89b8.jpg

  - code: 78c011c2e9214c69873b5591f1811cf9

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/1188ed9bfc3642eabca08dc60c7208f3.jpg

  - code: 9da0986f9dc24113b77b388ed5c59cf2

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/43463abb3c0a4ea1962c33372e979466.jpg

  - code: 6c3a7bd54d344951a0a5ff5d462c481c

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/02339374882c456eb8814581752cd74a.jpg

  - code: 031e65b5c0524762837397fc57b8d01d

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/9c31de673e354d36bc430ced85bf76b7.jpg

  - code: 223afcbaaf9343d6b2a92d244aca3d5c

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/e4f6e529094342cf8f394e8a8e47fb83.jpg

  - code: 03d7e02bd2e84cf3a6bbf8af0806d7fc

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/42f034a765e340eeab19d8049cf13bf5.jpg

  - code: fd3f4df584f64aaeb2dfbf9e3a3739d0

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/201fac888697497784bc4686b38cbaf7.jpg

  name: 葡萄

|||V-T3.11.0a-?|||info|||8.790s|||

收到事件「请求图片验证码识别(300)」, 尝试触发用户自定义函数

event

code: 300

from: liteTools.handleCaptcha

msg: 请求图片验证码识别

context

capcode:

  code: 200

  message: 操作成功

  result:

    code: d1fa5613e8d3445692c0ea68db5ca3da

    imageInfos:

    - code: 23b55c15588142d59b0b720ecc91ee71

      path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/ca10a3abdd3e4fc798e883e0c8e64684.jpg

    - code: 5137efd4347449f18bd9a293df9246a7

      path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/467c6e8ac9dd4505ad415c5ee64a89b8.jpg

    - code: 78c011c2e9214c69873b5591f1811cf9

      path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/1188ed9bfc3642eabca08dc60c7208f3.jpg

    - code: 9da0986f9dc24113b77b388ed5c59cf2

      path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/43463abb3c0a4ea1962c33372e979466.jpg

    - code: 6c3a7bd54d344951a0a5ff5d462c481c

      path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/02339374882c456eb8814581752cd74a.jpg

    - code: 031e65b5c0524762837397fc57b8d01d

      path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/9c31de673e354d36bc430ced85bf76b7.jpg

    - code: 223afcbaaf9343d6b2a92d244aca3d5c

      path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/e4f6e529094342cf8f394e8a8e47fb83.jpg

    - code: 03d7e02bd2e84cf3a6bbf8af0806d7fc

      path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/42f034a765e340eeab19d8049cf13bf5.jpg

    - code: fd3f4df584f64aaeb2dfbf9e3a3739d0

      path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221005/d1fa5613e8d3445692c0ea68db5ca3da/201fac888697497784bc4686b38cbaf7.jpg

    name: 葡萄

|||V-T3.11.0a-?|||error|||8.791s|||

用户自定义函数执行出错, 错误信息『「图片验证码识别错误: 

无法进行处理图形验证码, 请手签(就是用今日校园app自己手动签到的意思)

错误信息: 

EmptyError: name 'apple' is empty

Der Apfel hinter dem Ohr des falschen Helden

」

**Comment by IceTiki** [comment]
其实这里隐藏着一个解谜（隐藏关于图形验证码的解决方案），不过现在来看我设置的难度有点高，等几天回学校应该会修改一下内容，让解谜更容易一些。

**Comment by vr1yan** [comment]
第一根香肠在哪里啊（😭）是非计算机专业能找到的嘛

**Comment by IceTiki** [comment]
> 第一根香肠在哪里啊（😭）是非计算机专业能找到的嘛

非计算机专业也可以找到，香肠不在.md文件里面

**Comment by IceTiki** [comment]
> 第一根香肠在哪里啊（😭）是非计算机专业能找到的嘛

非计算机专业也可以找到，香肠不在代码文件(.py)里面

**Comment by vr1yan** [comment]
|||V-T3.11.0c-u|||info|||14.287s|||

验证码识别返回值

code: 500

data: Request method 'POST' not supported

msg: 服务器宕机啦，请及时反馈！

|||V-T3.11.0c-u|||error|||14.287s|||

用户自定义函数执行出错, 错误信息『「使用验证码识别API识别出错『{'code': 500, 'msg': '服务器宕机啦，请及时反馈！', 'data': "Request method 'POST' not supported"}』」

Traceback (most recent call last):

  File "/var/user/liteTools.py", line 1132, in trigger

    result["result"] = cla._userIndex(event, context)

  File "/var/user/userDefined.py", line 3, in index

    return event.execute()

  File "/var/user/userDefined.py", line 15, in execute

    return self.handleCapcha()

  File "/var/user/userDefined.py", line 44, in handleCapcha

    raise Exception(f"使用验证码识别API识别出错『{res}』")

Exception: 使用验证码识别API识别出错『{'code': 500, 'msg': '服务器宕机啦，请及时反馈！', 'data': "Request method 'POST' not supported"}』

』

|||V-T3.11.0c-u|||error|||14.287s|||

验证码识别出错: 使用验证码识别API识别出错『{'code': 500, 'msg': '服务器宕机啦，请及时反馈！', 'data': "Request method 'POST' not supported"}』

**Comment by vr1yan** [comment]
||V-T3.11.0c-u|||info|||234.292s|||

即将进行验证码识别

Starting new HTTPS connection (1): api.mtyqx.cn:443

https://api.mtyqx.cn:443 "POST /api/random.php HTTP/1.1" 302 None

Starting new HTTPS connection (1): tva3.sinaimg.cn:443

https://tva3.sinaimg.cn:443 "GET /large/0072Vf1pgy1fodqi3sqatj312z0svu0x.jpg HTTP/1.1" 200 505648

|||V-T3.11.0c-u|||info|||234.696s|||

yjy

code: 200

message: 操作成功

result:

  code: 6e9973d754c3486a8d2d22143e3f38fe

  imageInfos:

  - code: 01c34dbbb01043acabd0f3640dbbba47

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221008/6e9973d754c3486a8d2d22143e3f38fe/38ee24093cd3496d89ba752663becd83.jpg

  - code: 7c44765359f14e19b8a655681153e28f

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221008/6e9973d754c3486a8d2d22143e3f38fe/43bc4c15de924d9faac16c9b33c053b9.jpg

  - code: 7671861836554336b53874a8b7f977d7

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221008/6e9973d754c3486a8d2d22143e3f38fe/228fb6d76f924675be2c01bc7e98dd44.jpg

  - code: e879538fec7543aab03593f845bebe74

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221008/6e9973d754c3486a8d2d22143e3f38fe/685d524f3c85414d878d98b7b8fe8823.jpg

  - code: 9fc081f2d11f4f259b778a061e109ebb

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221008/6e9973d754c3486a8d2d22143e3f38fe/7c92aa5a236c4c4abfc13f2bfb17ff4a.jpg

  - code: 18ba928348f44d6495693b530b139ead

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221008/6e9973d754c3486a8d2d22143e3f38fe/d2e0571b387b4f558342f60518661e0a.jpg

  - code: 2a2f26d023884c0792da5c611d257e9d

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221008/6e9973d754c3486a8d2d22143e3f38fe/48915ce9f24148019cc210709b8748d8.jpg

  - code: 0d89107b7a614a8ea24b338c88642f0f

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221008/6e9973d754c3486a8d2d22143e3f38fe/03bbbf7befc64504b853e6e38309c17a.jpg

  - code: 669ed587887145b69e045aaa036764eb

    path: http://wecloud-captcha.campusphere.net/captcha/pretreatment/20221008/6e9973d754c3486a8d2d22143e3f38fe/bbac65d4046d4f798cbc79ec6a547a43.jpg

  name: 苹果

SHIFT_JIS Japanese prober hit error at byte 0

EUC-JP Japanese prober hit error at byte 0

GB2312 Chinese prober hit error at byte 0

EUC-KR Korean prober hit error at byte 0

CP949 Korean prober hit error at byte 0

Big5 Chinese prober hit error at byte 0

EUC-TW Taiwan prober hit error at byte 0

windows-1251 confidence = 0.03668727364337131, below negative shortcut threshhold 0.05

KOI8-R confidence = 0.042010701729627994, below negative shortcut threshhold 0.05

ISO-8859-5 confidence = 0.03988664250948898, below negative shortcut threshhold 0.05

MacCyrillic confidence = 0.036316262757143884, below negative shortcut threshhold 0.05

IBM866 confidence = 0.04278008556660003, below negative shortcut threshhold 0.05

IBM855 confidence = 0.04024759194009748, below negative shortcut threshhold 0.05

ISO-8859-5 confidence = 0.03959625423657066, below negative shortcut threshhold 0.05

windows-1251 confidence = 0.03603052541695435, below negative shortcut threshhold 0.05

TIS-620 confidence = 0.04350773252952253, below negative shortcut threshhold 0.05

ISO-8859-9 confidence = 0.04171572643925251, below negative shortcut threshhold 0.05

windows-1255 confidence = 0.039520622438688424, below negative shortcut threshhold 0.05

windows-1255 confidence = 0.039166888472416214, below negative shortcut threshhold 0.05

windows-1251 not active

KOI8-R not active

ISO-8859-5 not active

MacCyrillic not active

IBM866 not active

IBM855 not active

ISO-8859-7 Greek confidence = 0.06736089027619124

windows-1253 Greek confidence = 0.069358484166913

ISO-8859-5 not active

windows-1251 not active

TIS-620 not active

ISO-8859-9 not active

windows-1255 Hebrew confidence = 0.0

windows-1255 not active

windows-1255 not active

no probers hit minimum threshold

utf-8  confidence = 0.010000000000000009

SHIFT_JIS Japanese confidence = 0.01

EUC-JP Japanese confidence = 0.01

GB2312 Chinese confidence = 0.01

EUC-KR Korean confidence = 0.01

CP949 Korean confidence = 0.01

Big5 Chinese confidence = 0.01

EUC-TW Taiwan confidence = 0.01

windows-1251 Russian confidence = 0.03668727364337131

KOI8-R Russian confidence = 0.042010701729627994

ISO-8859-5 Russian confidence = 0.03988664250948898

MacCyrillic Russian confidence = 0.036316262757143884

IBM866 Russian confidence = 0.04278008556660003

IBM855 Russian confidence = 0.04024759194009748

ISO-8859-7 Greek confidence = 0.06736089027619124

windows-1253 Greek confidence = 0.069358484166913

ISO-8859-5 Bulgarian confidence = 0.03959625423657066

windows-1251 Bulgarian confidence = 0.03603052541695435

TIS-620 Thai confidence = 0.04350773252952253

ISO-8859-9 Turkish confidence = 0.04171572643925251

windows-1255 Hebrew confidence = 0.0

windows-1255 Hebrew confidence = 0.039520622438688424

windows-1255 Hebrew confidence = 0.039166888472416214

ISO-8859-1  confidence = 0.01

SHIFT_JIS Japanese prober hit error at byte 0

EUC-JP Japanese prober hit error at byte 0

GB2312 Chinese prober hit error at byte 0

EUC-KR Korean prober hit error at byte 0

CP949 Korean prober hit error at byte 0

Big5 Chinese prober hit error at byte 0

EUC-TW Taiwan prober hit error at byte 0

windows-1251 confidence = 0.03668727364337131, below negative shortcut threshhold 0.05

KOI8-R confidence = 0.042010701729627994, below negative shortcut threshhold 0.05

ISO-8859-5 confidence = 0.03988664250948898, below negative shortcut threshhold 0.05

MacCyrillic confidence = 0.036316262757143884, below negative shortcut threshhold 0.05

IBM866 confidence = 0.04278008556660003, below negative shortcut threshhold 0.05

IBM855 confidence = 0.04024759194009748, below negative shortcut threshhold 0.05

ISO-8859-5 confidence = 0.03959625423657066, below negative shortcut threshhold 0.05

windows-1251 confidence = 0.03603052541695435, below negative shortcut threshhold 0.05

TIS-620 confidence = 0.04350773252952253, below negative shortcut threshhold 0.05

ISO-8859-9 confidence = 0.04171572643925251, below negative shortcut threshhold 0.05

windows-1255 confidence = 0.039520622438688424, below negative shortcut threshhold 0.05

windows-1255 confidence = 0.039166888472416214, below negative shortcut threshhold 0.05

windows-1251 not active

KOI8-R not active

ISO-8859-5 not active

MacCyrillic not active

IBM866 not active

IBM855 not active

ISO-8859-7 Greek confidence = 0.06736089027619124

windows-1253 Greek confidence = 0.069358484166913

ISO-8859-5 not active

windows-1251 not active

TIS-620 not active

ISO-8859-9 not active

windows-1255 Hebrew confidence = 0.0

windows-1255 not active

windows-1255 not active

no probers hit minimum threshold

utf-8  confidence = 0.010000000000000009

SHIFT_JIS Japanese confidence = 0.01

EUC-JP Japanese confidence = 0.01

GB2312 Chinese confidence = 0.01

EUC-KR Korean confidence = 0.01

CP949 Korean confidence = 0.01

Big5 Chinese confidence = 0.01

EUC-TW Taiwan confidence = 0.01

windows-1251 Russian confidence = 0.03668727364337131

KOI8-R Russian confidence = 0.042010701729627994

ISO-8859-5 Russian confidence = 0.03988664250948898

MacCyrillic Russian confidence = 0.036316262757143884

IBM866 Russian confidence = 0.04278008556660003

IBM855 Russian confidence = 0.04024759194009748

ISO-8859-7 Greek confidence = 0.06736089027619124

windows-1253 Greek confidence = 0.069358484166913

ISO-8859-5 Bulgarian confidence = 0.03959625423657066

windows-1251 Bulgarian confidence = 0.03603052541695435

TIS-620 Thai confidence = 0.04350773252952253

ISO-8859-9 Turkish confidence = 0.04171572643925251

windows-1255 Hebrew confidence = 0.0

windows-1255 Hebrew confidence = 0.039520622438688424

windows-1255 Hebrew confidence = 0.039166888472416214

ISO-8859-1  confidence = 0.01

|||V-T3.11.0c-u|||error|||243.930s|||

用户自定义函数执行出错, 错误信息『「响应内容以json格式解析失败(Expecting value: line 1 column 1 (char 0))，响应内容:

����

|||V-T3.11.0c-u|||error|||243.940s|||

验证码识别出错: 响应内容以json格式解析失败(Expecting value: line 1 column 1 (char 0))，响应内容:

����

|||V-T3.11.0c-u|||debug|||243.947s|||

程序正在暂停5.598秒

|||V-T3.11.0c-u|||info|||249.552s|||

正在进行第2次验证码识别尝试

**Comment by vr1yan** [comment]
快把里面长得像的都试了，是我没找对还是找对出错了
