### ISSUE TITLE
可以再给点提示吗大佬

### ISSUE THREAD

**Issue by lvfeiyang111** [IceTiki/ruoli-sign-optimization#104]
已经把仓库底朝天翻了好几遍了一点头绪都没

**Comment by IceTiki** [comment]
1. 非计算机专业也可以找到
2. 不在代码文件里面(.py)
3. 可能在github网页版上更好找一些

**Comment by lvfeiyang111** [comment]
哥，是找到一串东西，然后填入apple中吗

**Comment by IceTiki** [comment]
> 哥，是找到一串东西，然后填入apple中吗

我觉得可以自己尝试判断w

**Comment by lvfeiyang111** [comment]
看了很久了，感觉好像是一个api，但是找不到，感觉陷入了误区，python太难了

**Comment by zhuzhutudou** [comment]
只要知道了复制进去就好还是需要添加什么我也试了好久

**Comment by zhuzhutudou** [comment]
![Uploading image.png…]()求解

**Comment by zhuzhutudou** [comment]
![Uploading image.png…]()求解

**Comment by lvfeiyang111** [comment]
我也求解，好难，看了三天了，就只看到yaml文件上说在第一根香肠里找

**Comment by lvfeiyang111** [comment]
在给点提示吧哥，我一个字一个字的看看到半夜都没发现苹果和香肠

**Comment by IceTiki** [comment]
提示我统一放在[issues108](https://github.com/IceTiki/ruoli-sign-optimization/issues/108)里面了
