### ISSUE TITLE
『讨论』苹果之旅(apple)专用贴

### ISSUE THREAD

**Issue by IceTiki** [IceTiki/ruoli-sign-optimization#108]

**Comment by IceTiki** [comment]
提示
1. 全程不需要打开.py文件
2. 如果你完成了全部流程，会看到恭喜你找到了苹果这句话
3. 流程不长（无提示大约在20~30分钟），当你找了很久没找到，请尝试转变思路
4. 我不会给太直接的提示，以防内鬼。请带着好奇心去尝试。

**Comment by ACSDSZ** [comment]
崩溃了找了好久还是没头绪

**Comment by loser121381** [comment]
鸡屁股在哪呀

**Comment by hero7069** [comment]
大佬，给点提示吧。另外苹果之旅花钱吗？

**Comment by hero7069** [comment]
|||V-T3.11.0d|||info|||20.715s|||
获取验证码
code: 200
message: 操作成功
result:
这算不算找到了啊？验证码还是识别失败

**Comment by hero7069** [comment]
[验证码处理失败, 错误信息:
『HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /IceTiki/ruoli-sign-optimization (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B5ABBF67F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))』]

**Comment by IceTiki** [comment]
> 大佬，给点提示吧。另外苹果之旅花钱吗？

不花钱

**Comment by hero7069** [comment]
> 

大佬，我这个现在是个什么情况。

**Comment by hero7069** [comment]
大佬给些提示吧
&nbsp;


shadowsock
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月10日(星期一) 中午12:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108)





  
大佬，给点提示吧。另外苹果之旅花钱吗？
  
不花钱

**Comment by 5i03** [comment]
你好,方便问一下苹果属于今日校园吗?

**Comment by 5i03** [comment]
能在给一些提示吗,谢谢

**Comment by zhuzhutudou** [comment]
抓包的可以直接填进去吗实在找不到提示

**Comment by zhuzhutudou** [comment]
> 抓包的可以直接填进去吗实在找不到提示

我没找到苹果但是我好像抓到device填进去就不用验证了

**Comment by IceTiki** [comment]
> 你好,方便问一下苹果属于今日校园吗?

不属于

**Comment by IceTiki** [comment]
> 能在给一些提示吗,谢谢

不需要专业知识（包括计算机、高等数学，线性代数等），自带线索，需要知道一些近期热门的网络梗，全流程都可以在本仓库内完成，要有好奇心找到引起你怀疑的点。
当然，这个苹果之旅本身就是用来筛人的，要是解不开那就手签吧，不用太执着。

**Comment by q82415670** [comment]
> > 能在给一些提示吗,谢谢
> 
> 不需要专业知识（包括计算机、高等数学，线性代数等），自带线索，需要知道一些近期热门的网络梗，全流程都可以在本仓库内完成，要有好奇心找到引起你怀疑的点。 当然，这个苹果之旅本身就是用来筛人的，要是解不开那就手签吧，不用太执着。

  麻辣个鸡  你可太TM会了！！！！！！！！

**Comment by hero7069** [comment]
大佬，其实apple也不能防止内鬼啊？还不如公开算了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月10日(周一) 下午5:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108)




   
能在给一些提示吗,谢谢
  
不需要专业知识（包括计算机、高等数学，线性代数等），自带线索，需要知道一些近期热门的网络梗，全流程都可以在本仓库内完成，要有好奇心找到引起你怀疑的点。 当然，这个苹果之旅本身就是用来筛人的，要是解不开那就手签吧，不用太执着。
  
麻辣个鸡  你可太TM会了！！！！！！！！

**Comment by IceTiki** [comment]
> 大佬，其实apple也不能防止内鬼啊？还不如公开算了。

那以前，要多想。

**Comment by hero7069** [comment]
干脆捐赠算了，大佬觉得怎么样啊？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月10日(周一) 晚上7:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108)




  
大佬，其实apple也不能防止内鬼啊？还不如公开算了。
  
那以前，要多想。

**Comment by q82415670** [comment]
> 干脆捐赠算了，大佬觉得怎么样啊？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年10月10日(周一) 晚上7:55 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108) 大佬，其实apple也不能防止内鬼啊？还不如公开算了。 那以前，要多想。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

收费要担责任的

**Comment by IceTiki** [comment]
> 干脆捐赠算了，大佬觉得怎么样啊？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年10月10日(周一) 晚上7:55 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108) 大佬，其实apple也不能防止内鬼啊？还不如公开算了。 那以前，要多想。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

不是钱的问题，用的人多了，就会显眼。像现在的图形验证码就是因为用得人多才出现的

**Comment by loser121381** [comment]
鸡屁股是坤坤吗？

**Comment by IceTiki** [comment]
> 

是

**Comment by hero7069** [comment]
试一试吧，



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月11日(周二) 凌晨1:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108)




 
鸡屁股是坤坤吗？

**Comment by Kizzol** [comment]
再给一点提示吧大佬，搞不懂香肠是什么意思

**Comment by hero7069** [comment]
> > 干脆捐赠算了，大佬觉得怎么样啊？
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2022年10月10日(周一) 晚上7:55 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108) 大佬，其实apple也不能防止内鬼啊？还不如公开算了。 那以前，要多想。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 不是钱的问题，用的人多了，就会显眼。像现在的图形验证码就是因为用得人多才出现的

大佬，捐赠也可以控制人数

**Comment by hero7069** [comment]
请大佬给点直接的提示吧！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月11日(周二) 中午11:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108)

**Comment by afterlif** [comment]
卡在 只因ass 上了 大佬可否稍微提示一下呢

**Comment by IceTiki** [comment]
> 卡在 只因ass 上了 大佬可否稍微提示一下呢

鸡=只因

**Comment by afterlif** [comment]
> 

是我想的太复杂了 我是真ikun

**Comment by hero7069** [comment]
大佬能给我一点提示吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月11日(周二) 晚上8:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108)




   
是我想的太复杂了 我是真ikun

**Comment by loser121381** [comment]
> 
找不到ass上有什么呀

**Comment by hero7069** [comment]
什么ass啊？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月11日(周二) 晚上9:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108)




   
找不到ass上有什么呀

**Comment by WAN-cpu** [comment]
所以和蔡徐坤有什么关联？鸡屁股，只因。只因你太美，🐔你太美？

**Comment by hero7069** [comment]
兄弟，我一点不懂你们说的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月13日(周四) 下午2:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108)

**Comment by hero7069** [comment]
有大佬说说吗？想了好久了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月13日(周四) 下午2:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108)




 
所以和蔡徐坤有什么关联？鸡屁股，只因。只因你太美，🐔你太美？

**Comment by xiaoshengnb66** [comment]
大佬 可以弄清晰一点吗

**Comment by hero7069** [comment]
清晰一点吧，大佬

**Comment by linxia1314** [comment]
原来答案竟然是...

**Comment by hero7069** [comment]
是啥啊？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月15日(周六) 晚上9:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108)




 
原来答案竟然是...

**Comment by xiaoshengnb66** [comment]
是apple

**Comment by xiaoshengnb66** [comment]
懂得自然懂 不懂我也没办法😄

**Comment by hero7069** [comment]
真的假的？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月15日(周六) 晚上9:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108)




 
是apple

**Comment by hero7069** [comment]
大佬已经找到了吗？能清晰一点吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月15日(周六) 晚上9:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108)




 
懂得自然懂 不懂我也没办法😄

**Comment by wyttle** [comment]
只因屁股清晰度太低了 手机也扫不出来 截图在线识别也识别失败

**Comment by hero7069** [comment]
啥意思，Apple是啥？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月21日(周五) 下午2:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108)




 
只因屁股清晰度太低了 手机也扫不出来 截图在线识别也识别失败

**Comment by hero7069** [comment]
找到苹果了，原来就是没有苹果

**Comment by IceTiki** [comment]
> 大佬 可以弄清晰一点吗

弄清晰一点了，实在不行可以用window的画图手动描(

**Comment by hero7069** [comment]
大佬，我已经打上了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月29日(周六) 下午4:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108)

**Comment by leieerr** [comment]
> > 大佬 可以弄清晰一点吗
> 
> 弄清晰一点了，实在不行可以用window的画图手动描(

不用打开py文件，是找到某些链接，粘到apple那边去么，我还没找到：(

**Comment by hero7069** [comment]
还行吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月31日(周一) 上午9:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108)




   
大佬 可以弄清晰一点吗
  
弄清晰一点了，实在不行可以用window的画图手动描(
  
不用打开py文件，是找到某些链接，粘到apple那边去么，我还没找到：(

**Comment by Maxmumu** [comment]
> 

我把图片链接放进去，不对啊

**Comment by Maxmumu** [comment]
> > 还行吧
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2022年10月31日(周一) 上午9:17 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108) 大佬 可以弄清晰一点吗 弄清晰一点了，实在不行可以用window的画图手动描( 不用打开py文件，是找到某些链接，粘到apple那边去么，我还没找到：( — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 我把图片链接放进去，都不对啊。大佬给点提示吧，找了几天了

终于找到了

**Comment by WAN-cpu** [comment]
> > > 还行吧
> > > […](#)
> > > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2022年10月31日(周一) 上午9:17 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108) 大佬 可以弄清晰一点吗 弄清晰一点了，实在不行可以用window的画图手动描( 不用打开py文件，是找到某些链接，粘到apple那边去么，我还没找到：( — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > 我把图片链接放进去，都不对啊。大佬给点提示吧，找了几天了
> 
> 终于找到了

php写的api？

**Comment by hero7069** [comment]
大佬能说说哪里找到的吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月2日(周三) 下午5:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108)




    
还行吧
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年10月31日(周一) 上午9:17 收件人: _@**._&gt;; 抄送: ***@***.***@._&gt;; 主题: Re: [IceTiki/ruoli-sign-optimization] 苹果之旅(apple)专用贴 (Issue #108) 大佬 可以弄清晰一点吗 弄清晰一点了，实在不行可以用window的画图手动描( 不用打开py文件，是找到某些链接，粘到apple那边去么，我还没找到：( — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _@_.*&gt;
  
我把图片链接放进去，都不对啊。大佬给点提示吧，找了几天了
  
终于找到了
  
php写的api？

**Comment by Maxmumu** [comment]
> 大佬能说说哪里找到的吗？
> […](#)

多看几次这个提问

**Comment by beggerlove** [comment]
> 
> 
> 
> > 大佬能说说哪里找到的吗？
> > […](#)
> 
> 多看几次这个提问

没找到  可以带带弟弟嘛

**Comment by Maxmumu** [comment]
> > > 大佬能说说哪里找到的吗？
> > > […](#)
> > 
> > 
> > 多看几次这个提问
> 
> 没找到 可以带带弟弟嘛

多看几次这条提问下面的回复

**Comment by beggerlove** [comment]
> 
> 
> 
> > > > 大佬能说说哪里找到的吗？
> > > > […](#)
> > > 
> > > 
> > > 多看几次这个提问
> > 
> > 没找到 可以带带弟弟嘛
> 
> 多看几次这条提问下面的回复

大佬  再给点儿其他的线索  找一天了  哭死.jpg

**Comment by IceTiki** [comment]
考虑到疫情放开，大多数人停止打卡，今日校园的压力减小，apple现在直接公布。参见[文档](https://apple.ruoli.cc/captcha/docs)

**Comment by Leisou** [comment]
我更想知道怎么找到apple，给我鱼和教我钓鱼的方法，当初，哎，，，，也是小白，现在还是小白
