### ISSUE TITLE
api使用频繁怎么处理哇

### ISSUE THREAD

**Issue by ygk666** [IceTiki/ruoli-sign-optimization#111]
如题

**Comment by ygk666** [comment]
还有一个问题现在今日校园用代挂是不是每次都需要验证，没有常用设备一说了，手机上会有常用设备，不会跳

**Comment by xvJobs** [comment]
> 还有一个问题现在今日校园用代挂是不是每次都需要验证，没有常用设备一说了，手机上会有常用设备，不会跳

你用的什么API

**Comment by ygk666** [comment]
> > 还有一个问题现在今日校园用代挂是不是每次都需要验证，没有常用设备一说了，手机上会有常用设备，不会跳
> 
> 你用的什么API

若离的api

**Comment by ygk666** [comment]
code401请求过于频繁

**Comment by IceTiki** [comment]
我记得好像是一分钟六次?你在config.yml里面设置下任务间间隔时间吧

**Comment by ygk666** [comment]
> 还有一个问题现在今日校园用代挂是不是每次都需要验证，没有常用设备一说了，手机上会有常用设备，不会跳

还有一个问题现在今日校园用代挂是不是每次都需要验证，没有常用设备一说了，手机上会有常用设备，不会跳

> 我记得好像是一分钟六次?你在config.yml里面设置下任务间间隔时间吧

还有一个问题现在今日校园用代挂是不是每次都需要验证，没有常用设备一说了，手机上会有常用设备，不会跳

**Comment by IceTiki** [comment]
> 还有一个问题现在今日校园用代挂是不是每次都需要验证，没有常用设备一说了，手机上会有常用设备，不会跳

这个看学校，不同学校有差异
