### ISSUE TITLE
√『功能建议』引入apprise进行消息推送

### ISSUE THREAD

**Issue by wang-silin** [IceTiki/ruoli-sign-optimization#134]
之前在Carlton大佬的项目里使用到了apprise推送的方式，使用起来很方便，并且适配的消息推送方式有很多，不必要单独在此项目内对每种消息推送进行单独适配了，可以优化消息推送的便捷性，也扩展了消息推送的方式。谢谢您。

**Comment by IceTiki** [comment]
现在在准备考研比较忙，近期不考虑

**Comment by wang-silin** [comment]
好的，非常感谢，那么祝您考研顺利，一战上岸喽！

**Comment by IceTiki** [comment]
加上了，你可以测试一下
