### ISSUE TITLE
关于腾讯云函数的部分配置疑问

### ISSUE THREAD

**Issue by Captain027** [IceTiki/ruoli-sign-optimization#14]
当使用腾讯云函数的时候进入函数管理-函数代码界面，显示腾讯云所内置的cloud studio为lite版本，该版本无终端-新终端选项卡，不知该向何处请教了，故留言，寻求帮助。万分感激。
2022-01-22

**Comment by IceTiki** [comment]
试一下换一个浏览器(或者换一台电脑)再进入云函数？(没有遇到过lite)
或者本地打包好依赖再上传。(注意windows和linux的依赖不通用(云函数是linux系统)，linux版本的依赖我手头好像没有，得去找找)

**Comment by Captain027** [comment]
Thank you for viewing this contact information.
This is an automatic reply message.
 We appreciate your Email, I will look as soon as possible and give you reply.  十分感谢您的来信，我将会尽快查看，并给予您回复。

**Comment by Captain027** [comment]
寻求了网友的帮助，是在py的版本的选择中出现了问题，已经得到了解决，感谢您。

**Comment by mhlms** [comment]
> 寻求了网友的帮助，是在py的版本的选择中出现了问题，已经得到了解决，感谢您。

请问你是如何解决的？感谢。

**Comment by Captain027** [comment]
> > 寻求了网友的帮助，是在py的版本的选择中出现了问题，已经得到了解决，感谢您。
> 
> 请问你是如何解决的？感谢。

在腾讯云函数的选择中我错误的选择了python的3.7版本，应当选择为3.6版本即为正常版本而非lite版了。
