### ISSUE TITLE
√『功能建议』教务系统滑块验证

### ISSUE THREAD

**Issue by wjx0428** [IceTiki/ruoli-sign-optimization#149]
教务系统是滑块验证

**Comment by IceTiki** [comment]
建议留一下教务系统，哪天有空我可能去看看

**Comment by IceTiki** [comment]
你们教务系统是哪一个，我找时间测试看看

**Comment by IceTiki** [comment]
> 教务系统是滑块验证

我试着写了一个滑块验证，你试一下？

**Comment by wjx0428** [comment]
> > 教务系统是滑块验证
> 
> 我试着写了一个滑块验证，你试一下？

https://authserver.sdws.edu.cn/authserver/login 你看一下

**Comment by IceTiki** [comment]
好像是一样的滑块，你下载新的仓库试试签到？
