### ISSUE TITLE
scipy依赖安装失败

### ISSUE THREAD

**Issue by 1374033045** [IceTiki/ruoli-sign-optimization#157]
开始安装依赖 scipy，开始时间 2023/3/1 下午7:28:41

Collecting scipy

  Using cached scipy-1.10.1.tar.gz (42.4 MB)

  Installing build dependencies: started

  Installing build dependencies: finished with status 'done'

  Getting requirements to build wheel: started

  Getting requirements to build wheel: finished with status 'done'

  Installing backend dependencies: started

  Installing backend dependencies: finished with status 'done'

  Preparing metadata (pyproject.toml): started

  Preparing metadata (pyproject.toml): finished with status 'error'

  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      The Meson build system
      Version: 1.0.1
      Source dir: /tmp/pip-install-m_b17oy6/scipy_cc68f8d3e7494e96ac1131bd1a775999
      Build dir: /tmp/pip-install-m_b17oy6/scipy_cc68f8d3e7494e96ac1131bd1a775999/.mesonpy-tqonwn9h/build
      Build type: native build
      Project name: SciPy
      Project version: 1.10.1
      C compiler for the host machine: cc (gcc 9.3.0 "cc (Alpine 9.3.0) 9.3.0")
      C linker for the host machine: cc ld.bfd 2.34
      C++ compiler for the host machine: c++ (gcc 9.3.0 "c++ (Alpine 9.3.0) 9.3.0")
      C++ linker for the host machine: c++ ld.bfd 2.34
      Cython compiler for the host machine: cython (cython 0.29.33)
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      
      ../../meson.build:63:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
      The following exception(s) were encountered:
      Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
      Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
      Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
      Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"
      
      A full log can be found at /tmp/pip-install-m_b17oy6/scipy_cc68f8d3e7494e96ac1131bd1a775999/.mesonpy-tqonwn9h/build/meson-logs/meson-log.txt
      + meson setup --prefix=/usr /tmp/pip-install-m_b17oy6/scipy_cc68f8d3e7494e96ac1131bd1a775999 /tmp/pip-install-m_b17oy6/scipy_cc68f8d3e7494e96ac1131bd1a775999/.mesonpy-tqonwn9h/build --native-file=/tmp/pip-install-m_b17oy6/scipy_cc68f8d3e7494e96ac1131bd1a775999/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

依赖安装失败，结束时间 2023/3/1 下午7:29:36，耗时 54.321 秒

**Comment by IceTiki** [comment]
x
你用新的版本吧，已经不用scipy了
