### ISSUE TITLE
请问大神是如何知道密钥和加密方式？

### ISSUE THREAD

**Issue by iccccch** [IceTiki/ruoli-sign-optimization#16]

**Comment by Ich-Stack** [comment]
之前参照：https://github.com/ZimoLoveShuang/auto-submit，但最终一直提示版本过低。
自己重新去抓包发现表单提交已经更换方式了，并且加密。最终放弃了

**Comment by IceTiki** [comment]
是其他人提供的，技术原理看下文(我也不太清楚)
https://meethigher.top/blog/2020/hacker/

**Comment by iccccch** [comment]
太棒了，感谢
