### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by YYplus** [IceTiki/ruoli-sign-optimization#2]
提交后返回的信息

|||info|||3.195s|||

BIZ层参数空或非法！

**Comment by YYplus** [comment]
签到

**Comment by IceTiki** [comment]
请提供更详细的日志

**Comment by YYplus** [comment]
START RequestId:7ce93dc1-c4d8-44ee-9bd0-f2becf94a865

|||info|||0.079s|||

正在进行第1轮尝试

|||info|||0.079s|||

即将在第1轮尝试中为[18115226]签到

|||info|||0.079s|||

准备登录

Starting new HTTPS connection (1): mobile.campushoy.com:443

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/info?ids=1020395659366146 HTTP/1.1" 200 None

Starting new HTTPS connection (1): tianshi.campusphere.net:443

https://tianshi.campusphere.net:443 "GET /wec-portal-mobile/client HTTP/1.1" 301 178

https://tianshi.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 302 154

https://tianshi.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Ftianshi.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 302 0

https://tianshi.campusphere.net:443 "GET /iap/login/pc.html?_2lBepC=1d9eb18af5214218846a950135e96009 HTTP/1.1" 200 1434

https://tianshi.campusphere.net:443 "POST /iap/security/lt HTTP/1.1" 200 None

https://tianshi.campusphere.net:443 "POST /iap/checkNeedCaptcha?username=18115226 HTTP/1.1" 200 None

https://tianshi.campusphere.net:443 "POST /iap/doLogin?lt=729d5a0e1e3c48428f50a21e6535aa53&rememberMe=false&dllt=&mobile=&username=18115226&password=yuan1453734637&captcha= HTTP/1.1" 302 0

https://tianshi.campusphere.net:443 "POST / HTTP/1.1" 302 154

https://tianshi.campusphere.net:443 "GET /portal/index.html HTTP/1.1" 200 68189

登录完成

|||info|||2.459s|||

|||info|||2.459s|||

即将开始签到

|||info|||2.459s|||

获取未签到的任务

https://tianshi.campusphere.net:443 "POST /wec-counselor-sign-apps/stu/sign/getStuSignInfosInOneDay HTTP/1.1" 302 154

https://tianshi.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Ftianshi.campusphere.net%2Fwec-counselor-sign-apps%2Fstu%2Fsign%2FgetStuSignInfosInOneDay HTTP/1.1" 302 0

https://tianshi.campusphere.net:443 "GET /wec-counselor-sign-apps/stu/sign/getStuSignInfosInOneDay?ticket=ST-iap:1020395659366146:ST:0352d6e7-2125-4834-88d7-be02ce59701e:20211105212848 HTTP/1.1" 302 154

https://tianshi.campusphere.net:443 "GET /wec-counselor-sign-apps/stu/sign/getStuSignInfosInOneDay HTTP/1.1" 405 1088

https://tianshi.campusphere.net:443 "POST /wec-counselor-sign-apps/stu/sign/getStuSignInfosInOneDay HTTP/1.1" 200 None

|||info|||2.989s|||

获取到的签到任务列表

  isLeave: '0'

  leaveMobileUrl: null

  leavePcUrl: null

- currentTime: 2021-11-05 21:28

  isMalposition: '0'

  rateSignDate: 2021-11-06 (周六)

  rateTaskBeginTime: '12:00'

  rateTaskEndTime: '20:00'

  signWid: '1123015'

  singleTaskBeginTime: null

  senderUserName: 食品工程学院(王旭)

  signInstanceWid: '15999'

  signRate: '1'

  signStatus: '2'

  singleTaskEndTime: null

  taskType: '7'

  stuSignWid: '3382893'

  taskName: 秋季签到及体温检测

|||info|||2.989s|||

匹配标题的任务

秋季签到及体温检测

|||info|||2.989s|||

获取具体的签到任务详情

https://tianshi.campusphere.net:443 "POST /wec-counselor-sign-apps/stu/sign/detailSignInstance HTTP/1.1" 200 None

签到任务的详情

changeTime: null

|||info|||3.093s|||

catQrUrl: https://cat.cpdaily.com/erweima

changeActorName: 王旭

currentTime: '2021-11-05 21:28:48'

extraField:

- description: ''

  - content: 正常

    isAbnormal: false

downloadUrl: https://img.cpdaily.com/ldy/index.html

  extraFieldItems:

    isOtherItems: 0

    isSelected: true

    value: 正常

    wid: 1535642

  - content: 异常（超过37.2度）

    isAbnormal: false

    isOtherItems: 0

    isSelected: null

    value: null

    wid: 1535643

  wid: 683421

isNeedExtra: 1

  hasOtherItems: 0

  title: 今天体温

extraFieldItemVos: []

isAllowUpdate: true

isMalposition: 0

isPhoto: 0

latitude: ''

leaveAppUrl: /wec-counselor-leave-apps/leave/home/index.html

qrCodeRcvdUsers:

leftNum: null

longitude: ''

photograph: []

- roleWid: null

  targetGrade: '-1'

  targetWid: '91398806'

rateSignDate: 2021-11-06 (周六)

  targetDegree: '-1'

  targetName: 王旭/15032522068

  targetType: '4'

  targetUserType: '-1'

rateTaskBeginTime: '12:00'

senderUserName: 食品工程学院(王旭)

signInstanceWid: '15999'

rateTaskEndTime: '20:00'

signAddress: null

signCondition: 1

signMode: 0

signPhotoUrl: null

signPlaceSelected:

- address: 大刘庄村

  creatorName: null

  creatorUserId: null

  creatorUserWid: null

  currentStatus: null

  isShare: null

  latitude: '39.43715142699681'

  longitude: '117.04889650335228'

  wid: null

signRate: '1'

signStatus: '2'

signTime: null

signedStuInfo:

  placeWid: null

  radius: 1358

signType: null

  cls: 2018级生物2班

  dept: 食品工程学院

  extraFieldItemVos:

    extraFieldItem: 正常

    extraFieldItemWid: '1535642'

    extraTitle: 今天体温

  - extraDesc: ''

    fieldIndex: 0

  grade: 2018级

  mobile: null

    isAbnormal: '0'

    isExtraFieldOtherItem: '0'

  major: 生物工程

  malposition: null

  nation: '-'

  schoolStatus: null

  sex: 男

    building: ''

    unit: ''

  stuDormitoryVo:

    area: ''

    room: ''

    sex: ''

  userId: '18115226'

  userName: 袁野

  userWid: '1016763380'

singleTaskBeginTime: null

taskDesc: null

taskName: 秋季签到及体温检测

singleTaskEndTime: null

taskType: '7'

updateLimit: null

|||info|||3.093s|||

填充表单

|||info|||3.093s|||

提交签到信息

|||info|||3.113s|||

即将提交的信息

Content-Type: application/json; charset=utf-8

Accept-Encoding: gzip

Connection: Keep-Alive

Cpdaily-Extension: DdU824D41oyphPGOjOzK8x8vvUJuww8t7N9a391oXdgxmIHq1qczlyT9RLcj372YQUPhvQAVnY9AQG59CpASnaauQYLX5Ypy6VDDrtVsSuLRDIbs0KOWxjiCpFXM+8mVn6ATa8KW5QMBlKsyugDX6g0p3J19S7P0NIc/Q3hciN8LFWOjLzY3Xic0BmgfArFGCqljz9W1z6EBhUMHxjqPYzQCGYyaQ8Ii18oRjI4SehUj27TM8BbKlA==

Host: tianshi.campusphere.net

CpdailyStandAlone: '0'

extension: '1'

User-Agent: Mozilla/5.0 (Windows NT 6.4; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)

  Chrome/41.0.2225.0 Safari/537.36

appVersion: 9.0.12

deviceId: null

bodyString: YPLYzIgqfVQB2sgW38uFASlLVnWVGCBhc+/qjHXQw25EwJiiTQz/El/dnxJ6Gkt6mw+qDrtPCnsneNX9K1OsCi6iGKVZMR4zZI8Qs21JzvCn48LkBGY/bZjGjEurAEVcigFyCSJ48sVuUAolHG/uVNZke5KBfoH7Ix7cVi7/KeXAmTmjpIZVl7PmLTVZI5QSOBq8X8KNQjsDoAu99UURWhTf7JU3M2SfIikn7F+QQFmHgmkjbEaOtZT59ASSjAjxhXVFaHsmpWTFs21Tg95LdrILELLeO2wZn+nUUbK43yUCG1cVvlQENzIV6Dro8D46YZtRROe1yWlP57Oh6jupUEPV7xM9ytRfEu2ywt1m8cs8Jzal8vx56ArwX8ns/VEXaTw0MEbYI9igRN5XUhJvgNFsytGYrSde3/ZYhaiDPVVb6Ggi9o2KLzT79GaolLZCtI1LTbFsKGdVuNga7+okFJGnHGC1QIxAJ6N639mo4BpJJtxm6rM9rerxTs0dzQums3Zy96zEOaDB2YoI8QbetQ==

calVersion: firstv

sign: e57e84d066eb40033492013b0612df32

systemName: android

userId: '18115226'

version: first_v2

lat: 39.435048

lon: 117.046411

model: OPPO R11 Plus

systemVersion: 4.4.4

https://tianshi.campusphere.net:443 "POST /wec-counselor-sign-apps/stu/sign/submitSign HTTP/1.1" 200 None

提交后返回的信息

|||info|||3.195s|||

BIZ层参数空或非法！

|||info|||3.195s|||

--[BIZ层参数空或非法！]秋季签到及体温检测

--18115226|1

|||info|||3.196s|||

推送情况

==签到情况==

|||info|||3.196s|||

[这个人太懒了，都不自己填备注名]

--18115226|1

--[BIZ层参数空或非法！]秋季签到及体温检测

|||info|||3.196s|||

推送情况

Response RequestId:7ce93dc1-c4d8-44ee-9bd0-f2becf94a865 RetMsg:"ok"

END RequestId:7ce93dc1-c4d8-44ee-9bd0-f2becf94a865

Report RequestId:7ce93dc1-c4d8-44ee-9bd0-f2becf94a865 Duration:3128ms Memory:128MB MemUsage:50.789062MB

**Comment by YYplus** [comment]
发现你更新readme了，删掉了多余的配置项问题解决，谢谢

**Comment by YYplus** [comment]
刚才的日志里有我的个人信息，所以删掉了
