### ISSUE TITLE
普通错误：签到失败

### ISSUE THREAD

**Issue by 2572749974** [IceTiki/ruoli-sign-optimization#21]
签到失败报错,之前没有问题,最近重新部署出现问题.
START RequestId: d2c488de-a166-4084-ada8-6a0d27116b20

Init Report RequestId: d2c488de-a166-4084-ada8-6a0d27116b20 Coldstart: 1067ms (PullCode: 417ms InitRuntime: 71ms InitFunction: 579ms) Memory: 128MB MemUsage: 8.29MB

ERROR RequestId: d2c488de-a166-4084-ada8-6a0d27116b20 Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 674, in exec_module   File "<frozen importlib._bootstrap_external>", line 781, in get_code   File "<frozen importlib._bootstrap_external>", line 741, in source_to_code   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 20     from Crypto.Cipher import AES        ^ IndentationError: expected an indented block", "statusCode": 443}

END RequestId: d2c488de-a166-4084-ada8-6a0d27116b20

Report RequestId: d2c488de-a166-4084-ada8-6a0d27116b20 Duration: 0ms Memory: 128MB MemUsage: 8.29MB

同时,下面代码报错
try:
  from Crypto.Cipher import AES
except OSError as e:
    print(f"""!!!!!!!!!!!!!!Crypto模块版本错误!!!!!!!!!!!!!!
请不要将linux系统(比如云函数)和windows系统的依赖混用
错误信息: {e}""")
    raise e

config配置文件如下
author: 若离|IceTiki|https://github.com/IceTiki/ruoli-sign-optimization
# YAML有引用和锚点，可以节省配置长度(备注:锚点要放在引用的前面)(可以参考https://www.runoob.com/w3cnote/yaml-intro.html)
# ======================================================================
# 全局设置
# ======================================================================
locationOffsetRange: 50 # 坐标偏移范围(单位：米)(可以为0)
maxTry: 1 # 最大尝试次数
logDir: 'log/' # 日志保存地址
delay: [5,10] # 多用户时，各用户之间任务执行延迟(时间范围可以使用浮点数)
sendMessage: # 推送函数的整体运行情况(不需要的项目不用填，可以删掉或者放着不管)
 
  pushplus_parameters: "" # pushplus参数，填入令牌(token)即可推送。也可以填入"token=xxx&topic=xxx"形式自定义更多参数
  pushplus_isNew: False # False使用旧版pushplus(https://pushplus.hxtrip.com)，True使用新版pushplus(http://www.pushplus.plus/)
  
# ======================================================================
# 用户组配置(填写自己所需的类型，并删掉不需要的。可以多用户签到。)
# ======================================================================
users: # ------别误删了这一行------

  - # 签到模板=======
    # 通用必填项-------
    type: 1 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: # 学校全称
    username: "" # 学号或者工号
    password: "" # 密码
    
    # 一般需填项-------
    abnormalReason: "" # abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
    photo: "photo" # 签到照片，不需要可不填。如果填入文件夹路径或路径列表，则会自动从中随机选择图片(.jpg)
    title: 0 # 签到任务的标题[0:自动取最后一个未签到的任务]
    checkTitle: 1 # 是否检查表单各项的标题[1:检查|0:不检查]
    signLevel: 1 # 签到等级[0:正常签到|1:请假后依然签到|2:请假或已经打卡后依然重复签到]
    forms: # 表单信息
      - form:
          title: 当前所在地
          value: 我在江苏省外地区
      - form:
          title: 你今天的健康码颜色
          value: 绿色
      - form:
          title: 你今天的通信大数据行程卡颜色
          value: 绿色
      - form:
          title: 你今天是否有以下情况
          value: 没有以上情况
      - form:
          title: 你今天的体温
          value: 36-37.2℃

    # 经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
    lon: 116.374743 # 经度
    lat: 31.631766 # 纬度
    address: "安徽省六安市裕安区苏埠镇" # 地址信息

**Comment by 2572749974** [comment]
# 导入标准库
import imp
import os
import sys
import codecs
import traceback

# 检查第三方模块
try:
    for i in ("requests", "requests_toolbelt", "urllib3", "bs4", "Crypto", "pyDes", "yaml", "lxml", "rsa"):
        imp.find_module(i)
except ImportError as e:
    print(f"""!!!!!!!!!!!!!!缺少第三方模块(依赖)!!!!!!!!!!!!!!
请使用pip命令安装或者手动将依赖拖入文件夹
错误信息: {e}""")
    raise e
# 检查Crypto是否对应系统版本
try:
  from Crypto.Cipher import AES
except OSError as e:
    print(f"""!!!!!!!!!!!!!!Crypto模块版本错误!!!!!!!!!!!!!!
请不要将linux系统(比如云函数)和windows系统的依赖混用
错误信息: {e}""")
    raise e

# 环境变量初始化
os.chdir(os.path.dirname(os.path.abspath(__file__)))  # 将工作路径设置为脚本位置
os.environ['TZ'] = "Asia/Shanghai"  # 将时区设为UTC+8
sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())  # 设置默认输出编码为utf-8

**Comment by IceTiki** [comment]
> # 导入标准库
> import imp
> import os
> import sys
> import codecs
> import traceback
> 
> # 检查第三方模块
> try:
>     for i in ("requests", "requests_toolbelt", "urllib3", "bs4", "Crypto", "pyDes", "yaml", "lxml", "rsa"):
>         imp.find_module(i)
> except ImportError as e:
>     print(f"""!!!!!!!!!!!!!!缺少第三方模块(依赖)!!!!!!!!!!!!!!
> 请使用pip命令安装或者手动将依赖拖入文件夹
> 错误信息: {e}""")
>     raise e
> # 检查Crypto是否对应系统版本
> try:
>   from Crypto.Cipher import AES
> except OSError as e:
>     print(f"""!!!!!!!!!!!!!!Crypto模块版本错误!!!!!!!!!!!!!!
> 请不要将linux系统(比如云函数)和windows系统的依赖混用
> 错误信息: {e}""")
>     raise e
> 
> # 环境变量初始化
> os.chdir(os.path.dirname(os.path.abspath(__file__)))  # 将工作路径设置为脚本位置
> os.environ['TZ'] = "Asia/Shanghai"  # 将时区设为UTC+8
> sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())  # 设置默认输出编码为utf-8
> 
> 
> 

截图发过来，你复制粘贴缩进都丢失了

**Comment by IceTiki** [comment]
> # 导入标准库
> import imp
> import os
> import sys
> import codecs
> import traceback
> 
> # 检查第三方模块
> try:
>     for i in ("requests", "requests_toolbelt", "urllib3", "bs4", "Crypto", "pyDes", "yaml", "lxml", "rsa"):
>         imp.find_module(i)
> except ImportError as e:
>     print(f"""!!!!!!!!!!!!!!缺少第三方模块(依赖)!!!!!!!!!!!!!!
> 请使用pip命令安装或者手动将依赖拖入文件夹
> 错误信息: {e}""")
>     raise e
> # 检查Crypto是否对应系统版本
> try:
>   from Crypto.Cipher import AES
> except OSError as e:
>     print(f"""!!!!!!!!!!!!!!Crypto模块版本错误!!!!!!!!!!!!!!
> 请不要将linux系统(比如云函数)和windows系统的依赖混用
> 错误信息: {e}""")
>     raise e
> 
> # 环境变量初始化
> os.chdir(os.path.dirname(os.path.abspath(__file__)))  # 将工作路径设置为脚本位置
> os.environ['TZ'] = "Asia/Shanghai"  # 将时区设为UTC+8
> sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())  # 设置默认输出编码为utf-8
> 
> 
> 

或者重新下载代码再部署，我怀疑你是手贱删掉了一个缩进

**Comment by 2572749974** [comment]
![1](https://user-images.githubusercontent.com/84435225/153834831-3f49261e-7284-49d2-889d-8e08b8e2a217.png)

**Comment by IceTiki** [comment]
代码更新了，你再试一下

**Comment by 2572749974** [comment]
代码更新后,测试成功了.但一直显示账号密码错误.
我自己登了两遍,确信是没问题的.
START RequestId: cdc6bccc-5056-47b8-be9a-e70e9b22331f

==========脚本开始初始化==========

Init Report RequestId: cdc6bccc-5056-47b8-be9a-e70e9b22331f Coldstart: 2252ms (PullCode: 410ms InitRuntime: 14ms InitFunction: 1828ms) Memory: 128MB MemUsage: 28.15MB

==========脚本开始执行==========

|||V-T3.4.1|||info|||0.528s|||

正在初始化20200203431的配置

|||V-T3.4.1|||info|||0.528s|||

正在进行第1轮尝试

|||V-T3.4.1|||info|||0.528s|||

即将在第1轮尝试中为[20200203431]签到

|||V-T3.4.1|||debug|||0.528s|||

程序正在暂停8.957秒

|||V-T3.4.1|||info|||9.495s|||

准备登录

Starting new HTTPS connection (1): mobile.campushoy.com:443

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/info?ids=ntvu HTTP/1.1" 200 None

Starting new HTTP connection (1): ntvu.campusphere.net:80

http://ntvu.campusphere.net:80 "GET /wec-portal-mobile/client HTTP/1.1" 307 180

Starting new HTTPS connection (1): ntvu.campusphere.net:443

https://ntvu.campusphere.net:443 "GET /wec-portal-mobile/client HTTP/1.1" 301 178

https://ntvu.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 302 154

https://ntvu.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Fntvu.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 302 0

Starting new HTTP connection (1): authserver.ntvu.edu.cn:80

http://authserver.ntvu.edu.cn:80 "GET /authserver/login?service=https%3A%2F%2Fntvu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3Df60a1080ac224490b61091c4a9c795c4 HTTP/1.1" 200 7367

http://authserver.ntvu.edu.cn:80 "GET /authserver/login?service=https%3A%2F%2Fntvu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3Df60a1080ac224490b61091c4a9c795c4 HTTP/1.1" 200 6553

http://authserver.ntvu.edu.cn:80 "POST /authserver/login?service=https%3A%2F%2Fntvu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3Df60a1080ac224490b61091c4a9c795c4&username=20200203431&password=zsl031945&lt=LT-1267865-d6mvEZzFnCVV2bjDnmkV1h5PIs41EB1644894566388-6CqB-cas&dllt=userNamePasswordLogin&execution=e2s1&_eventId=submit&rmShown=1 HTTP/1.1" 200 6952

    

    

    

    

        

<!DOCTYPE html>

<html>

<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <meta content="width=device-width,initial-scale=0.8, minimum-scale=0.8, maximum-scale=3"

          name="viewport"/>

    <meta name="renderer" content="webkit"/>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

    <meta property="qc:admins" content="754034015366713545637571540352652"/>

    <meta property="wb:webmaster" content="1ad39047f32b5b6b"/>

    <title>统一身份认证</title>

</head>

<script>

    

</script>

<link href="/authserver/custom/css/login.css" rel="stylesheet">

<link href="/authserver/custom/css/iCheck/custom.css" rel="stylesheet">

<script type="text/javascript">

    var secure = "false";

    var pwdDefaultEncryptSalt = "pXP2CaW5bvrev6Oi";

</script>

<body onload="loadFresh();">

<div class="auth_bg">

    <img src="/authserver/custom/images/img1.jpg" alt="">

</div>

<div class="auth_page_wrapper">

<div class="auth_logo">

    <img src="/authserver/custom/images/logo.png" alt="logo"/>

</div>

<div class="auth_login_content">

    <div class="auth_login_left">

        <div class="auth_others">

            

        </div>

    </div>

    

        

        

            

        

        

    

    <div class="auth_login_right">

        <div class="auth_tab">

            <div class="auth_tab_links">

                <ul>

                    <li id="accountLogin" style="width:100%;" class="selected" tabid="01"><span>账号登录</span></li>

                    

                    

                </ul>

            </div>

            <div class="clearfloat"></div>

            <div class="auth_tab_content">

                <div tabid="01" class="auth_tab_content_item">

                    <form id="casLoginForm" class="fm-v clearfix amp-login-form" role="form" action="/authserver/login?service=https%3A%2F%2Fntvu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3Df60a1080ac224490b61091c4a9c795c4&amp;username=20200203431&amp;password=zsl031945&amp;lt=LT-1267865-d6mvEZzFnCVV2bjDnmkV1h5PIs41EB1644894566388-6CqB-cas&amp;dllt=userNamePasswordLogin&amp;execution=e2s1&amp;_eventId=submit&amp;rmShown=1" method="post">

                        

                            <span id="msg" class="auth_error" style="top:-19px;">您提供的用户名或者密码有误</span>

                        

                        <p>

                            <i class="auth_icon auth_icon_user"></i>

                            <input id="username" name="username" placeholder="用户名" class="auth_input" type="text" value="20200203431"/>

                            <span id="usernameError" style="display:none;" class="auth_error">请输入用户名</span>

                        </p>

                        <p>

                            <i class="auth_icon auth_icon_pwd"></i>

                            <input id="password" placeholder="密码" class="auth_input" type="password" value="" autocomplete="off"/>

                            <input id="passwordEncrypt" name="password" style="display:none;" type="text" value="zsl031945"/>

                            <span id="passwordError" style="display:none;" class="auth_error">请输入密码</span>

                        </p>

                        <p id="cpatchaDiv">

                        </p>

                        

                            <p>

                                <input type="checkbox" name="rememberMe" id="rememberMe"/> <label

                                    onmousedown="javascript:$('.iCheck-helper').click();">一周内免登录</label>

                            </p>

                        

                        <p>

                            <button type="submit" class="auth_login_btn primary full_width">登录

                            </button>

                        </p>

                        <a id="getBackPasswordMainPage" href="getBackPasswordMainPage.do" class="auth_login_forgetp">

                            <small>忘记密码？</small>

                        </a>

                        <input type="hidden" name="lt" value="LT-1267866-Ig1SkpEmddt6ugXaTueYKEXgatIEqf1644894566467-6CqB-cas"/>

                        <input type="hidden" name="dllt" value="userNamePasswordLogin"/>

                        <input type="hidden" name="execution" value="e2s2"/>

                        <input type="hidden" name="_eventId" value="submit"/>

                        <input type="hidden" name="rmShown" value="1">

                    </form>

                </div>

                

                

                

            </div>

        </div>

    </div>

</div>

<div id="hidenCaptchaDiv" style="display: none;">

    <i class="auth_icon auth_icon_bar"></i>

    <input type="text" placeholder="验证码" id="captchaResponse" name="captchaResponse"

           class="auth_input captcha-input"/>

    <img id="captchaImg" class="captcha-img" alt="验证码" title="验证码"/>

            <span style="cursor: pointer;color: #1dadff;margin-left: 2px;" id="changeCaptcha"

                  class="chk_text"></span>

    <span id="cpatchaError" style="display:none;" class="auth_error">请输入验证码</span>

</div>

<div class="clearfloat"></div>

<div class="auth_login_footer">

    

 <span>

版权信息:&nbsp;©&nbsp;2019 南通职业大学

 </span>

</div>

</div>

<script type="text/javascript" src="/authserver/custom/js/jquery.min.js"></script>

<script type="text/javascript" src="/authserver/custom/js/login-language.js"></script>

<script type="text/javascript" src="/authserver/custom/js/icheck.min.js"></script>

<script type="text/javascript" src="/authserver/custom/js/login.js"></script>

<script type="text/javascript" src="/authserver/custom/js/login-wisedu_v1.0.js"></script>

<script type="text/javascript" src="/authserver/custom/js/encrypt/encrypt.wisedu.js"></script>

<script type="text/javascript" src="/authserver/custom/js/encrypt/aes.js"></script>

<script type="text/javascript">

    // 选中tab框

    var dllt = 'userNamePasswordLogin';

    if (dllt != '' && dllt == 'dynamicLogin') {

        selectLi($("#dyLogin"));

    } else if (dllt != '' && dllt == 'qrLogin'){

        getQrCode();

        countDown();

        selectLi($("#qrLogin"));

    } else {

        selectLi($("#accountLogin"));

    }

    $(document).ready(function () {

     $("#captchaImg").attr("src","captcha.html?ts=" + new Date().getMilliseconds());

        

        var service = GetQueryString("service");

        if (service) {

            $("#getBackPasswordMainPage").attr("href", "getBackPasswordMainPage.do?service=" + encodeURIComponent(service));

        }

    });

</script>

</body>

</html>

    

|||V-T3.4.1|||error|||11.275s|||

Traceback (most recent call last):

  File "/var/user/index.py", line 206, in main

    msg = working(user)

  File "/var/user/index.py", line 131, in working

    today.login()

  File "/var/user/todayLoginService.py", line 92, in login

    self.checkLogin()

  File "/var/user/todayLoginService.py", line 86, in checkLogin

    self.session.cookies = self.loginEntity.login()

  File "/var/user/login/casLogin.py", line 162, in login

    raise Exception(msg)

Exception: 您提供的用户名或者密码有误

20200203431签到失败您提供的用户名或者密码有误

|||V-T3.4.1|||info|||11.278s|||

--20200203431|1

--您提供的用户名或者密码有误

|||V-T3.4.1|||info|||11.278s|||

推送情况

Qmsg配置错误，信息取消发送

邮件配置出错

邮箱或邮件api填写无效，已取消发送邮件！

pushplus的令牌填写错误，已取消发送！

|||V-T3.4.1|||info|||11.278s|||

==签到情况==

[默认备注名]

--20200203431|1

--您提供的用户名或者密码有误

Starting new HTTPS connection (1): pushplus.hxtrip.com:443

https://pushplus.hxtrip.com:443 "POST /send?token=e3c54bd4286748ac944be96ca3df12a0&title=%E8%87%AA%E5%8A%A8%E5%81%A5%E5%BA%B7%E6%89%93%E5%8D%A1&content=%3D%3D%E7%AD%BE%E5%88%B0%E6%83%85%E5%86%B5%3D%3D%3C%2Fbr%3E%5B%E9%BB%98%E8%AE%A4%E5%A4%87%E6%B3%A8%E5%90%8D%5D%3C%2Fbr%3E--20200203431%7C1%3C%2Fbr%3E--%E6%82%A8%E6%8F%90%E4%BE%9B%E7%9A%84%E7%94%A8%E6%88%B7%E5%90%8D%E6%88%96%E8%80%85%E5%AF%86%E7%A0%81%E6%9C%89%E8%AF%AF%3C%2Fbr%3E%3C%2Fbr%3E HTTP/1.1" 200 None

|||V-T3.4.1|||info|||11.658s|||

推送情况

Qmsg配置错误，信息取消发送

邮件配置出错

邮箱或邮件api填写无效，已取消发送邮件！

发送成功

Response RequestId:cdc6bccc-5056-47b8-be9a-e70e9b22331f RetMsg:"ok"

END RequestId:cdc6bccc-5056-47b8-be9a-e70e9b22331f

Report RequestId:cdc6bccc-5056-47b8-be9a-e70e9b22331f Duration:11142ms Memory:128MB MemUsage:31.621994MB

**Comment by 2572749974** [comment]
怀疑是今天签到过来,等明天在试试

**Comment by IceTiki** [comment]
> [默认备注名]
> 
> --20200203431|1
> 
> --您提供的用户名或者密码有误

你应该先检查下用户名/密码

**Comment by IceTiki** [comment]
去[authserver.ntvu.edu.cn](http://authserver.ntvu.edu.cn/)这个网址测试登录

**Comment by IceTiki** [comment]
去https://ntvu.campusphere.net/portal/index.html这个网址测试登录

**Comment by 2572749974** [comment]
我测试了好几遍,确实是没问题的.
我问了其他人,他们说是当天频繁测试导致的.
所以,我明天在看看.
代码应该是没什么问题的啦.
谢谢
