### ISSUE TITLE
index.py中的一些小问题

### ISSUE THREAD

**Issue by Well2333** [IceTiki/ruoli-sign-optimization#24]
第一个是库检查阶段的路径问题，我已经提交了一个pr，希望大佬能过目一下。

第二个是报错的方式略微不合理，个人建议应该将报错信息添加到 raise 里，现在的报错方式会将 print 出来的提示信息刷上去，反而不利于小白找到错误的问题，尤其是在腾讯云函数里面，log全都**堆成一团**了，很难再去找到有用的信息了

就像这样
```python
# 原代码
except ImportError as e:
    print(f"""!!!!!!!!!!!!!!脚本代码文件缺失!!!!!!!!!!!!!!
请尝试重新下载代码
错误信息: {e}""")
    raise e

# 建议改成
except ImportError as e:
    raise f"""!!!!!!!!!!!!!!脚本代码文件缺失!!!!!!!!!!!!!!\n请尝试重新下载代码\n错误信息: {e}"""
```

**Comment by Well2333** [comment]
目前这个脚本有个我自己拉的交流群 757680119
不过由于个人原因，目前实在没法很好的进行管理和回答问题
若离佬要是有兴趣的话，我十分乐意将群转让给您来管理
不知您意下如何d=====(￣▽￣*)b

**Comment by IceTiki** [comment]
> 目前这个脚本有个我自己拉的交流群 757680119
> 不过由于个人原因，目前实在没法很好的进行管理和回答问题
> 若离佬要是有兴趣的话，我十分乐意将群转让给您来管理
> 不知您意下如何d=====(￣▽￣*)b

我不是若离(这个仓库只是他代码的魔改版)，脚本我一般在子墨的群里面讨论。顺便一提，raise后面要跟异常类，而不是字符串
