### ISSUE TITLE
教务系统适配问题：报 账号密码错误

### ISSUE THREAD

**Issue by 2572749974** [IceTiki/ruoli-sign-optimization#29]
大佬,我又来了.
还是上次的问题,上次有人说,密码错误,可能是访问次数过多,所以,我等了很多天,今天重新部署,还是报账户密码错误,我确信,账号密码是没有问题的.
同时,我们学校因为一些原因,更换了教务系统网站,现在的教务系统是官网的vpn入口
是不是这个问题.
日志:

START RequestId: daee77ad-459a-4809-9d68-fec245741037

==========脚本开始初始化==========

Init Report RequestId: daee77ad-459a-4809-9d68-fec245741037 Coldstart: 3243ms (PullCode: 450ms InitRuntime: 23ms InitFunction: 2770ms) Memory: 128MB MemUsage: 28.10MB

==========脚本开始执行==========

|||V-T3.4.1|||info|||0.695s|||

正在初始化20200203431的配置

|||V-T3.4.1|||info|||0.696s|||

正在进行第1轮尝试

|||V-T3.4.1|||info|||0.696s|||

即将在第1轮尝试中为[20200203431]签到

|||V-T3.4.1|||debug|||0.696s|||

程序正在暂停9.060秒

|||V-T3.4.1|||info|||9.765s|||

准备登录

Starting new HTTPS connection (1): mobile.campushoy.com:443

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/info?ids=ntvu HTTP/1.1" 200 None

Starting new HTTP connection (1): ntvu.campusphere.net:80

http://ntvu.campusphere.net:80 "GET /wec-portal-mobile/client HTTP/1.1" 307 180

Starting new HTTPS connection (1): ntvu.campusphere.net:443

https://ntvu.campusphere.net:443 "GET /wec-portal-mobile/client HTTP/1.1" 301 178

https://ntvu.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 302 154

https://ntvu.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Fntvu.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 302 0

Starting new HTTP connection (1): authserver.ntvu.edu.cn:80

http://authserver.ntvu.edu.cn:80 "GET /authserver/login?service=https%3A%2F%2Fntvu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3Da57b01d5532d4f25b0afb162f0df1190 HTTP/1.1" 200 7378

http://authserver.ntvu.edu.cn:80 "GET /authserver/login?service=https%3A%2F%2Fntvu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3Da57b01d5532d4f25b0afb162f0df1190 HTTP/1.1" 200 6553

http://authserver.ntvu.edu.cn:80 "POST /authserver/login?service=https%3A%2F%2Fntvu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3Da57b01d5532d4f25b0afb162f0df1190&username=20200203431&password=zsl031945&lt=LT-1713851-vbOWFhdaFzqAIUB14cLv6vaQa212Qe1645774320463-nbU7-cas&dllt=userNamePasswordLogin&execution=e2s1&_eventId=submit&rmShown=1 HTTP/1.1" 200 6952

    

    

    

    

        

<!DOCTYPE html>

<html>

<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <meta content="width=device-width,initial-scale=0.8, minimum-scale=0.8, maximum-scale=3"

          name="viewport"/>

    <meta name="renderer" content="webkit"/>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

    <meta property="qc:admins" content="754034015366713545637571540352652"/>

    <meta property="wb:webmaster" content="1ad39047f32b5b6b"/>

    <title>统一身份认证</title>

</head>

<script>

    

</script>

<link href="/authserver/custom/css/login.css" rel="stylesheet">

<link href="/authserver/custom/css/iCheck/custom.css" rel="stylesheet">

<script type="text/javascript">

    var secure = "false";

    var pwdDefaultEncryptSalt = "rxTtkf3XMwX9PJUt";

</script>

<body onload="loadFresh();">

<div class="auth_bg">

    <img src="/authserver/custom/images/img1.jpg" alt="">

</div>

<div class="auth_page_wrapper">

<div class="auth_logo">

    <img src="/authserver/custom/images/logo.png" alt="logo"/>

</div>

<div class="auth_login_content">

    <div class="auth_login_left">

        <div class="auth_others">

            

        </div>

    </div>

    

        

        

            

        

        

    

    <div class="auth_login_right">

        <div class="auth_tab">

            <div class="auth_tab_links">

                <ul>

                    <li id="accountLogin" style="width:100%;" class="selected" tabid="01"><span>账号登录</span></li>

                    

                    

                </ul>

            </div>

            <div class="clearfloat"></div>

            <div class="auth_tab_content">

                <div tabid="01" class="auth_tab_content_item">

                    <form id="casLoginForm" class="fm-v clearfix amp-login-form" role="form" action="/authserver/login?service=https%3A%2F%2Fntvu.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3Da57b01d5532d4f25b0afb162f0df1190&amp;username=20200203431&amp;password=zsl031945&amp;lt=LT-1713851-vbOWFhdaFzqAIUB14cLv6vaQa212Qe1645774320463-nbU7-cas&amp;dllt=userNamePasswordLogin&amp;execution=e2s1&amp;_eventId=submit&amp;rmShown=1" method="post">

                        

                            <span id="msg" class="auth_error" style="top:-19px;">您提供的用户名或者密码有误</span>

                        

                        <p>

                            <i class="auth_icon auth_icon_user"></i>

                            <input id="username" name="username" placeholder="用户名" class="auth_input" type="text" value="20200203431"/>

                            <span id="usernameError" style="display:none;" class="auth_error">请输入用户名</span>

                        </p>

                        <p>

                            <i class="auth_icon auth_icon_pwd"></i>

                            <input id="password" placeholder="密码" class="auth_input" type="password" value="" autocomplete="off"/>

                            <input id="passwordEncrypt" name="password" style="display:none;" type="text" value="zsl031945"/>

                            <span id="passwordError" style="display:none;" class="auth_error">请输入密码</span>

                        </p>

                        <p id="cpatchaDiv">

                        </p>

                        

                            <p>

                                <input type="checkbox" name="rememberMe" id="rememberMe"/> <label

                                    onmousedown="javascript:$('.iCheck-helper').click();">一周内免登录</label>

                            </p>

                        

                        <p>

                            <button type="submit" class="auth_login_btn primary full_width">登录

                            </button>

                        </p>

                        <a id="getBackPasswordMainPage" href="getBackPasswordMainPage.do" class="auth_login_forgetp">

                            <small>忘记密码？</small>

                        </a>

                        <input type="hidden" name="lt" value="LT-1713852-VtwnbPPvG4yd25PcOe9skjTccjeLXm1645774320503-nbU7-cas"/>

                        <input type="hidden" name="dllt" value="userNamePasswordLogin"/>

                        <input type="hidden" name="execution" value="e2s2"/>

                        <input type="hidden" name="_eventId" value="submit"/>

                        <input type="hidden" name="rmShown" value="1">

                    </form>

                </div>

                

                

                

            </div>

        </div>

    </div>

</div>

<div id="hidenCaptchaDiv" style="display: none;">

    <i class="auth_icon auth_icon_bar"></i>

    <input type="text" placeholder="验证码" id="captchaResponse" name="captchaResponse"

           class="auth_input captcha-input"/>

    <img id="captchaImg" class="captcha-img" alt="验证码" title="验证码"/>

            <span style="cursor: pointer;color: #1dadff;margin-left: 2px;" id="changeCaptcha"

                  class="chk_text"></span>

    <span id="cpatchaError" style="display:none;" class="auth_error">请输入验证码</span>

</div>

<div class="clearfloat"></div>

<div class="auth_login_footer">

    

 <span>

版权信息:&nbsp;©&nbsp;2019 南通职业大学

 </span>

</div>

</div>

<script type="text/javascript" src="/authserver/custom/js/jquery.min.js"></script>

<script type="text/javascript" src="/authserver/custom/js/login-language.js"></script>

<script type="text/javascript" src="/authserver/custom/js/icheck.min.js"></script>

<script type="text/javascript" src="/authserver/custom/js/login.js"></script>

<script type="text/javascript" src="/authserver/custom/js/login-wisedu_v1.0.js"></script>

<script type="text/javascript" src="/authserver/custom/js/encrypt/encrypt.wisedu.js"></script>

<script type="text/javascript" src="/authserver/custom/js/encrypt/aes.js"></script>

<script type="text/javascript">

    // 选中tab框

    var dllt = 'userNamePasswordLogin';

    if (dllt != '' && dllt == 'dynamicLogin') {

        selectLi($("#dyLogin"));

    } else if (dllt != '' && dllt == 'qrLogin'){

        getQrCode();

        countDown();

        selectLi($("#qrLogin"));

    } else {

        selectLi($("#accountLogin"));

    }

    $(document).ready(function () {

     $("#captchaImg").attr("src","captcha.html?ts=" + new Date().getMilliseconds());

        

        var service = GetQueryString("service");

        if (service) {

            $("#getBackPasswordMainPage").attr("href", "getBackPasswordMainPage.do?service=" + encodeURIComponent(service));

        }

    });

</script>

</body>

</html>

    

|||V-T3.4.1|||error|||10.501s|||

Traceback (most recent call last):

  File "/var/user/index.py", line 206, in main

    msg = working(user)

  File "/var/user/index.py", line 131, in working

    today.login()

  File "/var/user/todayLoginService.py", line 92, in login

    self.checkLogin()

  File "/var/user/todayLoginService.py", line 86, in checkLogin

    self.session.cookies = self.loginEntity.login()

  File "/var/user/login/casLogin.py", line 162, in login

    raise Exception(msg)

Exception: 您提供的用户名或者密码有误

20200203431签到失败您提供的用户名或者密码有误

|||V-T3.4.1|||info|||10.505s|||

--20200203431|1

--您提供的用户名或者密码有误

|||V-T3.4.1|||info|||10.505s|||

推送情况

Qmsg配置错误，信息取消发送

邮件配置出错

邮箱或邮件api填写无效，已取消发送邮件！

pushplus的令牌填写错误，已取消发送！

|||V-T3.4.1|||info|||10.505s|||

==签到情况==

[默认备注名]

--20200203431|1

--您提供的用户名或者密码有误

Starting new HTTPS connection (1): www.pushplus.plus:443

https://www.pushplus.plus:443 "POST /send?token=82fbfd08e9074a4cbbed78b52184658b&title=%E8%87%AA%E5%8A%A8%E5%81%A5%E5%BA%B7%E6%89%93%E5%8D%A1&content=%3D%3D%E7%AD%BE%E5%88%B0%E6%83%85%E5%86%B5%3D%3D%3C%2Fbr%3E%5B%E9%BB%98%E8%AE%A4%E5%A4%87%E6%B3%A8%E5%90%8D%5D%3C%2Fbr%3E--20200203431%7C1%3C%2Fbr%3E--%E6%82%A8%E6%8F%90%E4%BE%9B%E7%9A%84%E7%94%A8%E6%88%B7%E5%90%8D%E6%88%96%E8%80%85%E5%AF%86%E7%A0%81%E6%9C%89%E8%AF%AF%3C%2Fbr%3E%3C%2Fbr%3E HTTP/1.1" 200 None

|||V-T3.4.1|||info|||10.603s|||

推送情况

Qmsg配置错误，信息取消发送

邮件配置出错

邮箱或邮件api填写无效，已取消发送邮件！

发送成功

Response RequestId:daee77ad-459a-4809-9d68-fec245741037 RetMsg:"ok"

END RequestId:daee77ad-459a-4809-9d68-fec245741037

Report RequestId:daee77ad-459a-4809-9d68-fec245741037 Duration:9923ms Memory:128MB MemUsage:31.454460MB

**Comment by IceTiki** [comment]
有联系方式吗(比如qq)有时间我看看

**Comment by 2572749974** [comment]
qq:2572749974  大佬辛苦
