### ISSUE TITLE
旧版问题：关于表单填写有多个表单导致识别到其他表单的一个适合小白的改进方案

### ISSUE THREAD

**Issue by nkdns** [IceTiki/ruoli-sign-optimization#34]
在使用该打卡软件的过程中，我们会发现一个问题，如果辅导员连续发布多个多日收集表单就会导致填写问题不匹配的情况。
问题产生：在actions的collection.py文件中有代码：task = res['datas']['rows'][0] 使得系统默认选择表单列表中的第一位表单。
修改：增加表单名称的指定
原代码：
       # 第二次请求接口，真正的拿到具体任务
        res = self.session.post(queryUrl, data=json.dumps(
            params), headers=headers, verify=False)
        res = DT.resJsonEncode(res)
        if res['datas']['totalSize'] < 1:
            raise TaskError('没有查询到信息收集任务')
        LL.log(1, '查询任务返回结果', res['datas'])
        task = res['datas']['rows'][0]
        self.collectWid = task['wid']
        self.taskWid = task['formWid']
        self.instanceWid = task.get('instanceWid', '')

![image](https://user-images.githubusercontent.com/101375480/157791259-ba415f6f-c9e9-445f-a125-7a0f8b174837.png)

我的临使修改方案：
       # 第二次请求接口，真正的拿到具体任务
        res = self.session.post(queryUrl, data=json.dumps(
            params), headers=headers, verify=False)
        res = DT.resJsonEncode(res)
        if res['datas']['totalSize'] < 1:
            raise TaskError('没有查询到信息收集任务')
        LL.log(1, '查询任务返回结果', res['datas'])
        for i in res['datas']['rows']:
            LL.log(1, '查询任务标题返回结果', i['subject'])
            if '学生每日健康信息' in i['subject']:
                chtask = i
        task = chtask
        LL.log(1, '已经自动为你选择表单:', task['subject'])
        self.collectWid = task['wid']
        self.taskWid = task['formWid']
        self.instanceWid = task.get('instanceWid', '')

![image](https://user-images.githubusercontent.com/101375480/157791299-b8a6414a-3571-4982-8dec-cb71f9ecb0c7.png)

其中if语句那里是表单的标题中的部分内容。因为我们表单存在标题日期，也就是标题内容局部更新的情况

**Comment by Well2333** [comment]
这个问题其实在月初就解决了，可以更新一下源码

**Comment by Well2333** [comment]
我之前也提交过类似的PR，不过因为代码冲突被block了（

**Comment by nkdns** [comment]
> 这个问题其实在月初就解决了，可以更新一下源码

好的，我去更新一下，因为最近才遇到这样的问题 /捂脸
