### ISSUE TITLE
提交收集表单出现问题

### ISSUE THREAD

**Issue by 1216332750** [IceTiki/ruoli-sign-optimization#38]
--响应内容以json格式解析失败([Errno Expecting value] <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimal-ui, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/uag/error/css/prompt.css">
</head>
<body>

<div class="prompt-container">
    <div class="prompt-img">
        <img src="/uag/error/img/404.png">
    </div>
    <div class="prompt-tip">
        <div class="prompt-tip-error">错误 404</div>
        <div class="prompt-tip-warn">抱歉，您访问的页面不存在，请联系管理员！</div>
        <a href="/" class="prompt-button">进入首页</a>
    </div>
</div>

</body>
</html>
: 0)，响应内容:

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimal-ui, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/uag/error/css/prompt.css">
</head>
<body>

<div class="prompt-container">
    <div class="prompt-img">
        <img src="/uag/error/img/404.png">
    </div>
    <div class="prompt-tip">
        <div class="prompt-tip-error">错误 404</div>
        <div class="prompt-tip-warn">抱歉，您访问的页面不存在，请联系管理员！</div>
        <a href="/" class="prompt-button">进入首页</a>
    </div>
</div>

</body>
</html>

**Comment by IceTiki** [comment]
这几天看情况修

**Comment by IceTiki** [comment]
今日校园最新版app也没办法正常上传图片。目前需要等待今日校园的图片上传恢复正常后才能尝试修复。
目前请尝试打开获取历史信息(getHistorySign: True)来做临时性过渡。
