### ISSUE TITLE
关于图像上传的问题

### ISSUE THREAD

**Issue by Well2333** [IceTiki/ruoli-sign-optimization#40]
由于腾讯云函数在包大小大于10M之后只显示入口函数，50M以上直接不让传，限制了签到用照片的数量。

我在读源码的时候发现图片是先上传到阿里云oss，然后获取一个下载链接出来，那如果不用阿里云oss，直接提供直链（或者自建oss）是否可行？

**Comment by IceTiki** [comment]
似乎也是可以的，辅导员应该能正常看到。

不过有可能反而自己看不到导致无法在app修改图片(现在就有人遇到这个问题)

**Comment by IceTiki** [comment]
> 似乎也是可以的，辅导员应该能正常看到。
> 
> 不过有可能反而自己看不到导致无法在app修改图片(现在就有人遇到这个问题)

目前就信息收集报告了这个自己app无法显示图片和无法修改的问题(辅导员那边可以看到)。我登他的号抓包也的确发现是没法看到图片没法修改图片的(而且最新版今日校园9.0.19也一样)

**Comment by Well2333** [comment]
那我尝试一下使用一些图床进行尝试是否可行吧，如果可以的话，后续增添照片也会方便一些

**Comment by IceTiki** [comment]
今天发现，今天没法正常显示图片是因为填入value的图片url忘记加后缀了。

**Comment by IceTiki** [comment]
这样来看图床说不定的确能用

**Comment by IceTiki** [comment]
> 那我尝试一下使用一些图床进行尝试是否可行吧，如果可以的话，后续增添照片也会方便一些
测试结果怎么样

**Comment by IceTiki** [comment]
> 那我尝试一下使用一些图床进行尝试是否可行吧，如果可以的话，后续增添照片也会方便一些

测试结果怎么样

**Comment by Well2333** [comment]
这两天忙着跟学校的破网对线，暂时还没进行测试，等我把网络问题先解决了再写吧。
目前学校的网络应该是比当年的3G强点有限的水平，属实没法好好测试了。

**Comment by IceTiki** [comment]
> 这两天忙着跟学校的破网对线，暂时还没进行测试，等我把网络问题先解决了再写吧。
> 目前学校的网络应该是比当年的3G强点有限的水平，属实没法好好测试了。

2333，要不加个qq

**Comment by Well2333** [comment]
我QQ 1070330078
之前的群 757680119
