### ISSUE TITLE
请帮看一下这个错误

### ISSUE THREAD

**Issue by DBeidachazi** [IceTiki/ruoli-sign-optimization#42]
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
==========脚本开始初始化==========
Traceback (most recent call last):
  File "C:\Users\26950\Desktop\1\index.py", line 48, in <module>
    from login.Utils import Utils
ModuleNotFoundError: No module named 'login.Utils'

**Comment by IceTiki** [comment]
你代码没下全

**Comment by IceTiki** [comment]
你代码没下完整，有些文件缺失。
顺便问下你用的是哪个版本，正常来说会报出你那里做错了

**Comment by DBeidachazi** [comment]
今早直接clone下来的

**Comment by DBeidachazi** [comment]
那应该是最新的吧

**Comment by DBeidachazi** [comment]
<a href="https://imgtu.com/i/qiMnSS"><img src="https://s1.ax1x.com/2022/03/18/qiMnSS.jpg" alt="qiMnSS.jpg" border="0" /></a>
clone下来还会有文件缺失的吗

**Comment by IceTiki** [comment]
有可能是pycharm会划定项目区域，可能没把除了index.py以外的文件加进项目里面。
