### ISSUE TITLE
无回复：使用旧版本仓库出错

### ISSUE THREAD

**Issue by xiluo233** [IceTiki/ruoli-sign-optimization#48]
<img width="503" alt="屏幕截图 2022-03-27 194820" src="https://user-images.githubusercontent.com/102467497/160280084-6f0a7052-f1ad-41d2-bec7-8d9b48f070fa.png">
怎么解决啊

**Comment by xiluo233** [comment]
<img width="443" alt="image" src="https://user-images.githubusercontent.com/102467497/160281083-3be6324f-432a-4ab4-bd12-f220f0a057ec.png">

**Comment by IceTiki** [comment]
发下你教务系统的连接

**Comment by xiluo233** [comment]
是这个吗？
教务处 (hfut.edu.cn)


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IceTiki/ruoli-sign-optimization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月28日(星期一) 凌晨0:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IceTiki/ruoli-sign-optimization] 1 (Issue #48)





 
发下你教务系统的连接

**Comment by IceTiki** [comment]
或者你说一下学校名称。我看看，有可能是教务系统没有适配

**Comment by IceTiki** [comment]
顺便一提，你试试下最新的代码。
我看你日志用的是很古早的版本了

**Comment by xiluo233** [comment]
> 顺便一提，你试试下最新的代码。 我看你日志用的是很古早的版本了

<img width="505" alt="image" src="https://user-images.githubusercontent.com/102467497/160545490-f8c46e16-54ff-4a69-9f03-59e20397b108.png">
这个又是咋回事啊
