### ISSUE TITLE
拍照签到失败(坐标填错了)

### ISSUE THREAD

**Issue by pooneyy** [IceTiki/ruoli-sign-optimization#49]
![image](https://user-images.githubusercontent.com/85266337/160285362-7a59b576-d8fd-474f-a48d-c34aa396e0e7.png)
经纬度坐标在签到范围内，签到结果却反馈“范围外签到原因不能为空”

**Comment by pooneyy** [comment]
![image](https://user-images.githubusercontent.com/85266337/160285582-851cc0d1-d5ca-45ac-92e6-6b0bc1bde1f6.png)
另外，“查寝”的拍照签到有选项

**Comment by IceTiki** [comment]
查寝居然还有这种东西

**Comment by IceTiki** [comment]
757680119
你可以在这个群里面说明下详细情况x我现在先睡觉
