### ISSUE TITLE
功能增补：收集任务中上传图片

### ISSUE THREAD

**Issue by 1216332750** [IceTiki/ruoli-sign-optimization#5]
收集任务中需要上传图片，提示配置项属于未知配置项，请反馈

**Comment by 1216332750** [comment]
[collection.txt](https://github.com/IceTiki/ruoli-sign-optimization/files/7585358/collection.txt)
已解决

**Comment by IceTiki** [comment]
厉害啊w自己抓包解决了。
最近在忙作业，有时间再更新到仓库里面。

**Comment by IceTiki** [comment]
好了，合并进仓库了。建议用.jpg格式的图片。
