### ISSUE TITLE
当前登录用户不允许访问目标应用

### ISSUE THREAD

**Issue by xiongxiaoliu** [IceTiki/ruoli-sign-optimization#50]
这是哪里出来的问题呢

**Comment by xiongxiaoliu** [comment]
这个算签到成功了吗

**Comment by xiongxiaoliu** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"

"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <meta property="qc:admins" content="754034015366713545637571540352652"/>

    <meta property="wb:webmaster" content="1ad39047f32b5b6b"/>

    <title>统一身份认证</title>

</head>

    

    

        <script type="text/javascript"

                src="/authserver/lovey/js/jquery.min.js"></script>

     

<script type="text/javascript">

    (function ($) {

        $.fn.validationEngineLanguage = function () {

        };

        $.validationEngineLanguage = {

            newLang: function () {

                $.validationEngineLanguage.allRules = {

                    "required": {

                        "regex": "none",

                        "alertText": "* 非空选项",

                        "alertTextCheckboxMultiple": "* 请选择一个单选框",

                        "alertTextCheckboxe": "* 请选择一个复选框"},

                    "length": {

                        "regex": "none",

                        "alertText": "* 长度必须在",

                        "alertText2": " 至",

                        "alertText3": " 之间"},

                    "limit": {

                        "regex": "none",

                        "alertText": "* 大小必须在",

                        "alertText2": " 至",

                        "alertText3": " 之间"},

                    "minValue": {

                        "regex": "none",

                        "alertText": "* 值不小于"},

                    "maxCheckbox": {

                        "regex": "none",

                        "alertText": "* 最多选择",

                        "alertText2": " 项"},

                    "minCheckbox": {

                        "regex": "none",

                        "alertText": "* 至少选择",

                        "alertText2": " 项"},

                    "equals": {

                        "regex": "none",

                        "alertText": "* 两次输入不一致,请重新输入"},

                    "telephone": {

                        "regex": "/^(0[0-9]{2,3}\-)?([2-9][0-9]{6,7})+(\-[0-9]{1,4})?$/",

                        "alertText": "* 请输入有效的电话号码,如:010-29292929"},

                    "mobilephone": {

                        "regex": "/(^[\\d]{11}$)/",

                        "alertText": "* 请输入有效的手机号码"},

                    "phone": {

                        "regex": "/^((\\(\\d{2,3}\\))|(\\d{3}\\-))?(\\(0\\d{2,3}\\)|0\\d{2,3}-)?[1-9]\\d{6,7}(\\-\\d{1,4})?$/",

                        "alertText": "* 请输入有效的联系号码"},

                    "email": {

                        "regex": "/^([a-zA-Z\d]+)([_\-\.]{0,1}[a-zA-Z\d]{1,})*@(([a-zA-Z\d]+)([_\-\.]{0,1}[a-zA-Z\d]{1,})*\.)+[a-zA-z]{2,5}$//",

                        "alertText": "* 请输入有效的邮件地址"},

                    "date": {

                        "regex": "/^(([0-9]{3}[1-9]|[0-9]{2}[1-9][0-9]{1}|[0-9]{1}[1-9][0-9]{2}|[1-9][0-9]{3})-(((0[13578]|1[02])-(0[1-9]|[12][0-9]|3[01]))|((0[469]|11)-(0[1-9]|[12][0-9]|30))|(02-(0[1-9]|[1][0-9]|2[0-8]))))|((([0-9]{2})(0[48]|[2468][048]|[13579][26])|((0[48]|[2468][048]|[3579][26])00))-02-29)$/",

                        "alertText": "* 请输入有效的日期,如:2008-08-08"},

                    "ip": {

                        "regex": "/^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/",

                        "alertText": "* 请输入有效的IP"},

                    "accept": {

                        "regex": "none",

                        "alertText": "* 请输入有效的文件格式"},

                    "chinese": {

                        "regex": "/^[\u4e00-\u9fa5]+$/",

                        "alertText": "* 请输入中文"},

                    "url": {

                        "regex": "/^((https|http|ftp|rtsp|mms)?:\\/\\/)?"

                        + "(([0-9]{1,3}.){3}[0-9]{1,3}" // IP形式的URL- 199.194.52.184

                        + "|" // 允许IP和DOMAIN（域名）

                        + "([0-9a-z_!~*'()-]+\\.)*" // 域名- www.

                        + "([0-9a-z][0-9a-z-]{0,61})?[0-9a-z]\\." // 二级域名

                        + "[a-z]{2,6})" // first level domain- .com or .museum

                        + "(:[0-9]{1,5})?" // 端口- :80,最多5位

                        + "[\\/a-zA-Z0-9\\/]{0,}"

                        + "(\\/[0-9a-zA-Z\\.\\?\\-\\&=]{0,})?$/",

                        "alertText": "* 请输入有效的网址"},

                    "domain": {

                        "regex": "/^([\\w-]+\\.)+((com)|(net)|(org)|(gov\\.cn)|(info)|(cc)|(com\\.cn)|(net\\.cn)|(org\\.cn)|(name)|(biz)|(tv)|(cn)|(mobi)|(name)|(sh)|(ac)|(io)|(tw)|(com\\.tw)|(hk)|(com\\.hk)|(ws)|(travel)|(us)|(tm)|(la)|(me\\.uk)|(org\\.uk)|(ltd\\.uk)|(plc\\.uk)|(in)|(eu)|(it)|(jp))$/",

                        "alertText": "* 请输入有效的域名"},

                    "zipcode": {

                        "regex": "/^[1-9]\\d{5}$/",

                        "alertText": "* 请输入有效的邮政编码"},

                    "idCard": {

                        //对身份证的验证分别加入了区域，出生年月（简单）的验证

                        "regex": "/^(([16][1-5]|2[1-4]|3[1-7]|4[1-6]|5[0-4]|[7-9]1)\\d{4}(19|20|21)\\d{2}(0[0-9]|1[0-2])(0[0-9]|[1-2][0-9]|3[0-1])\\d{3}[0-9xX])" + //验证18位身份证

                        "|(([16][1-5]|2[1-4]|3[1-7]|4[1-6]|5[0-4]|[7-9]1)\\d{6}(0[0-9]|1[0-2])(0[0-9]|[1-2][0-9]|3[0-1])\\d{3})$/", //验证15位的身份证

                        "alertText": "* 请输入有效的身份证号码"},

                    "mp3": {

                        "regex": "/^(http(s)?:\\/\\/)[\\w\\W]+(\.(mp|MP)3)$/",

                        "alertText": "* 请输入有效的mp3链接地址"},

                    "qq": {

                        "regex": "/^[1-9]\\d{4,9}$/",

                        "alertText": "* 请输入有效的QQ号码"},

                    "onlyInteger": {

                        "regex": "/^[0-9-]+$/",

                        "alertText": "* 请输入整数"},

                    "onlyNumber": {

                        "regex": "/^\\-?[0-9\\,]*\\.?\\d*$/",

                        "alertText": "* 请输入数字"},

                    "points": {

                        "regex": "/^[1-9]\\d{0,2}$/",

                        "alertText": "* 请输入1~999的整数"},

                    "awardTimes": {

                        "regex": "/^[1-9]\\d{0,4}$/",

                        "alertText": "* 请输入1~99999的整数"},

                    "notZero": {

                        "regex": "/^[1-9]\\d*$/",

                        "alertText": "* 必须大于零整数"},

                    "oneToNine": {

                        "regex": "/^[1-9]{1}$/",

                        "alertText": "* 请输入1-9的整数"},

                    "onlyLetter": {

                        "regex": "/^[a-zA-Z]+$/",

                        "alertText": "* 请输入英文字母"},

                    "noSpecialCaracters": {

                        "regex": "/^[0-9a-zA-Z]+$/",

                        "alertText": "* 请输入英文字母和数字"},

                    "imageCaracters": {

                        "regex": "/^[0-9]+(%|px)$/",

                        "alertText": "* 请输入百分数或者像素值，例如15%或者15px"},

                    "onlyFile": {

                        "regex": "/^[0-9a-zA-Z]+\\.*[a-zA-Z]{0,4}$/",

                        "alertText": "* 目录或者文件名不合法"

                    },

                    "sectionNum": {

                        "regex": "/^[0-9]\\d{2}$/",

                        "alertText": "必须为3位数字"

                    },

                    "noSpecialCaractersNew": {

                        "regex": "/^[0-9a-zA-Z\u4e00-\u9fa5]*$/",

                        "alertText": "* 只允许英文字母、数字和中文"

                    }/*,

                     "ajaxUser": {

                     *//**

                     * by yzhao 2013-3-7 14:46

                     * CMS的用法不规范是错误的“ajax['check.json','恭喜，该用户名可以使用！','用户名已存在，请重新输入！']]”

                     * ajaxUser相当于表达式名称,命令方式ajax[ajaxUser]

                     *//*

                     "file":"/check.json",

                     "alertTextOk": "* 可以使用.",

                     "alertTextLoad": "* 正在检查中, 请稍侯...",

                     "alertText": "* 已被占用."}*/

                }

            }

        }

    })(jQuery);

    $(document).ready(function () {

        $.validationEngineLanguage.newLang();

    });

</script>

     <script type="text/javascript"

        <link rel="stylesheet" type="text/css"

                src="/authserver/lovey/js/easyloader.js"></script>

        <script type="text/javascript" src="/authserver/js/cas-wisedu-redirect.js"></script>

        <script type="text/javascript" src="/authserver/js/i18n.zh_CN.js"></script>

        <link type="text/css" rel="stylesheet"

              href="/authserver/lovey/style/css/lovey.css"/>

              href="/authserver/assets/css/custom.css"/>

        <link rel="stylesheet" type="text/css"

              href="/authserver/custom/css/custom-base.css"/>

        <body class="body_bg">

        <div class="ui_container_fluid">

            <div class="header">

                <div class="top">

                    <div class="logo pull_left">

                        <img src="/authserver/custom/images/login-logo.png" alt="IDS logo"

                             title

                                     ="IDS logo"/>

                    </div>

                </div>

            </div>

        </div>

    

    <div id="msg" class="errors">

      <h2>未授权的访问</h2>

      <p>当前登录用户不允许访问目标应用</p>

    </div>

    

    

    

        <div class="clearfloat"></div>

        <div class="auth_login_footer">

            

 <span>

     Copyright&nbsp;©&nbsp;2015 wisedu&nbsp;All&nbsp;Rights&nbsp;Reserved&nbsp;&nbsp;&nbsp;&nbsp;

        &nbsp;&nbsp;江苏金智教育信息股份有限公司

 </span>

        </div>

        </div>

        <script type="text/javascript" src="/authserver/js/cas-wisedu.js"></script>

        

    

</body>

</html>

  

|||V-T3.7.3|||error|||17.229s|||

[

未授权的访问

当前登录用户不允许访问目标应用

]

Traceback (most recent call last):

  File "/var/user/index.py", line 218, in main

    msg = working(user)

  File "/var/user/index.py", line 142, in working

    today.login()

  File "/var/user/todayLoginService.py", line 92, in login

    self.checkLogin()

  File "/var/user/todayLoginService.py", line 86, in checkLogin

    self.session.cookies = self.loginEntity.login()

  File "/var/user/login/casLogin.py", line 169, in login

    raise Exception(msg)

Exception: 

未授权的访问

当前登录用户不允许访问目标应用

21450215签到失败[

未授权的访问

当前登录用户不允许访问目标应用

]

Traceback (most recent call last):

  File "/var/user/index.py", line 218, in main

    msg = working(user)

  File "/var/user/index.py", line 142, in working

    today.login()

  File "/var/user/todayLoginService.py", line 92, in login

    self.checkLogin()

  File "/var/user/todayLoginService.py", line 86, in checkLogin

    self.session.cookies = self.loginEntity.login()

  File "/var/user/login/casLogin.py", line 169, in login

    raise Exception(msg)

Exception: 

未授权的访问

当前登录用户不允许访问目标应用

|||V-T3.7.3|||info|||17.231s|||

--21450215|1

--[

未授权的访问

当前登录用户不允许访问目标应用

]

Traceback (most recent call last):

  File "/var/user/index.py", line 218, in main

    msg = working(user)

  File "/var/user/index.py", line 142, in working

    today.login()

  File "/var/user/todayLoginService.py", line 92, in login

    self.checkLogin()

  File "/var/user/todayLoginService.py", line 86, in checkLogin

    self.session.cookies = self.loginEntity.login()

  File "/var/user/login/casLogin.py", line 169, in login

    raise Exception(msg)

Exception: 

未授权的访问

当前登录用户不允许访问目标应用

|||V-T3.7.3|||info|||17.232s|||

推送情况

QMSG酱|Qmsg配置错误，信息取消发送

SMTP|邮件配置出错

若离邮箱API|邮箱或邮件api填写无效，已取消发送邮件！

Pushplus|pushplus的令牌填写错误，已取消发送！

|||V-T3.7.3|||info|||17.232s|||

---[V-T3.7.3]签到情况---

[默认备注名]

--21450215|1

--[

未授权的访问

当前登录用户不允许访问目标应用

]

Traceback (most recent call last):

  File "/var/user/index.py", line 218, in main

    msg = working(user)

  File "/var/user/index.py", line 142, in working

    today.login()

  File "/var/user/todayLoginService.py", line 92, in login

    self.checkLogin()

  File "/var/user/todayLoginService.py", line 86, in checkLogin

    self.session.cookies = self.loginEntity.login()

  File "/var/user/login/casLogin.py", line 169, in login

    raise Exception(msg)

Exception: 

未授权的访问

当前登录用户不允许访问目标应用

[默认备注名]

--21450215|1

--[

未授权的访问

当前登录用户不允许访问目标应用

]

Traceback (most recent call last):

  File "/var/user/index.py", line 218, in main

    msg = working(user)

  File "/var/user/index.py", line 142, in working

    today.login()

  File "/var/user/todayLoginService.py", line 92, in login

    self.checkLogin()

  File "/var/user/todayLoginService.py", line 86, in checkLogin

    self.session.cookies = self.loginEntity.login()

  File "/var/user/login/casLogin.py", line 169, in login

    raise Exception(msg)

Exception: 

未授权的访问

当前登录用户不允许访问目标应用

|||V-T3.7.3|||info|||17.232s|||

推送情况

QMSG酱|Qmsg配置错误，信息取消发送

SMTP|邮件配置出错

若离邮箱API|邮箱或邮件api填写无效，已取消发送邮件！

Pushplus|pushplus的令牌填写错误，已取消发送！

Response RequestId: 2e173757-f38e-42c9-a516-41a052e52d2e RetMsg: "ok"

END RequestId: 2e173757-f38e-42c9-a516-41a052e52d2e

Report RequestId: 2e173757-f38e-42c9-a516-41a052e52d2e Duration: 16878ms Memory: 128MB MemUsage: 33.27MB

**Comment by IceTiki** [comment]
你试下手动登陆教务系统，看看能不能用

**Comment by xiongxiaoliu** [comment]
我再试试吧，谢谢大佬

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月31日(周四) 上午10:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [IceTiki/ruoli-sign-optimization] 当前登录用户不允许访问目标应用 (Issue #50)




 
你试下手动登陆教务系统，看看能不能用

**Comment by xiongxiaoliu** [comment]
![DR A XC458 X7JD_9XU45GE](https://user-images.githubusercontent.com/30167482/160982060-3142dad6-1262-4e42-a46d-dd4c5280e240.png)

**Comment by xiongxiaoliu** [comment]
网页是湖南强智科技发展有限公司，不是江苏金智教育信息股份有限公司，网页的教务系统密码和今日校园的学工号登录密码也不是同一个

**Comment by xiongxiaoliu** [comment]
衡阳师范学院 http://hysfjw.hynu.cn/

**Comment by xiongxiaoliu** [comment]
> 你看下[http://authserver.hynu.cn/authserver/login这个能不能正常用来登录](http://authserver.hynu.cn/authserver/login%E8%BF%99%E4%B8%AA%E8%83%BD%E4%B8%8D%E8%83%BD%E6%AD%A3%E5%B8%B8%E7%94%A8%E6%9D%A5%E7%99%BB%E5%BD%95)

[可以的](url)

**Comment by IceTiki** [comment]
> > 你看下[http://authserver.hynu.cn/authserver/login这个能不能正常用来登录](http://authserver.hynu.cn/authserver/login%E8%BF%99%E4%B8%AA%E8%83%BD%E4%B8%8D%E8%83%BD%E6%AD%A3%E5%B8%B8%E7%94%A8%E6%9D%A5%E7%99%BB%E5%BD%95)
> 
> [可以的，要发下配置文件吗](url)

暂时不用。这个问题比较迷，目前无法下定论。

**Comment by xiongxiaoliu** [comment]
发现问题了，我们学校没有开放cas登录

**Comment by IceTiki** [comment]
> 发现问题了，我们学校没有开放cas登录

草生，怎么发现的

**Comment by xiongxiaoliu** [comment]
> > 发现问题了，我们学校没有开放cas登录
> 
> 草生，怎么发现的

**Comment by xiongxiaoliu** [comment]
用了下别的脚本，cas是登录不了的

**Comment by Roif-X** [comment]
> 用了下别的脚本，cas是登录不了的

请问你后来用的那个脚本呀？
