### ISSUE TITLE
需要验证码登录

### ISSUE THREAD

**Issue by hzg1577** [IceTiki/ruoli-sign-optimization#53]
![image](https://user-images.githubusercontent.com/74068830/162603863-345dcb67-bbaf-47fe-8025-9b4dfa2e3873.png)
大佬，好像我们学校必须验证码才能登录啊

**Comment by IceTiki** [comment]
你试试在办事大厅手动登陆一次？
手动登陆一次然后再次登陆还需要验证码吗

**Comment by hzg1577** [comment]
> 你试试在办事大厅手动登陆一次？ 手动登陆一次然后再次登陆还需要验证码吗

您是说从今日校园登录页面的办事大厅登录一遍吗？如果是的话，我试了登录一次还是不行

**Comment by hzg1577** [comment]
> 你试试在办事大厅手动登陆一次？ 手动登陆一次然后再次登陆还需要验证码吗

并且我们学校的办事大厅，从哪里进去好像都要填验证码
![image](https://user-images.githubusercontent.com/74068830/162613303-2977bd28-74e1-40f0-a481-d6978aa07986.png)

**Comment by IceTiki** [comment]
更新了，你试一下。
(注意配置里面多了一个captcha项)

**Comment by hzg1577** [comment]
> 更新了，你试一下。 (注意配置里面多了一个captcha项)

好的，感谢大佬，以可正常登录
