### ISSUE TITLE
求助，当日的日期格式怎么写呢

### ISSUE THREAD

**Issue by eb66** [IceTiki/ruoli-sign-optimization#54]
value: "%Y-%m-%d"
value: time.strftime("%Y-%m-%d", time.localtime())
value: "time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())"
都不行啊
![](https://p0.meituan.net/csc/157ca18d700db695516729f8560a703957435.jpg)

**Comment by IceTiki** [comment]
你是要打开本地图片吗？

**Comment by IceTiki** [comment]
似乎是你没加后缀的原因

**Comment by IceTiki** [comment]
> value: "%Y-%m-%d"
> value: time.strftime("%Y-%m-%d", time.localtime())
> value: "time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())"
> 都不行啊
> https://p0.meituan.net/csc/157ca18d700db695516729f8560a703957435.jpg

目前表单文本没有自动格式化。
不过这个功能很好加，我明天给加上。

**Comment by IceTiki** [comment]
因为功能实际实现比较复杂，要咕到明天

**Comment by IceTiki** [comment]
更新了，详细使用方式见 用户配置高级教程-超级字符串

**Comment by IceTiki** [comment]
如果测试成功麻烦知会一声

**Comment by eb66** [comment]
> 如果测试成功麻烦知会一声

OK，多谢晚上试下。
value: {"str+":"%Y-%m-%d", "flag":"tf"}
这样吗?

**Comment by IceTiki** [comment]
嗯，对的

**Comment by eb66** [comment]
> 嗯，对的

试了下，不行，系统错误，改成2022-04-17就能成功了，而且日志怎么显示的昨天的日期
即将开始信息收集填报


https://sdust.campusphere.net:443 "POST /wec-counselor-collector-apps/stu/collector/queryCollectorProcessingList HTTP/1.1" 302 154

https://sdust.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Fsdust.campusphere.net%2Fwec-counselor-collector-apps%2Fstu%2Fcollector%2FqueryCollectorProcessingList HTTP/1.1" 302 0

https://sdust.campusphere.net:443 "GET /wec-counselor-collector-apps/stu/collector/queryCollectorProcessingList?ticket=ST-iap:1021741275526389:ST:c7439ab9-cc44-4382-8ee4-13392f6bbc80:20220417222303 HTTP/1.1" 302 154

https://sdust.campusphere.net:443 "GET /wec-counselor-collector-apps/stu/collector/queryCollectorProcessingList HTTP/1.1" 405 1088

https://sdust.campusphere.net:443 "POST /wec-counselor-collector-apps/stu/collector/queryCollectorProcessingList HTTP/1.1" 200 None

|||V-T3.7.4|||info|||10.048s|||

获取到的第1页任务列表

code: '0'

datas:

  pageNumber: 1

  pageSize: 20

  rows:

  - content: https://wecres.cpdaily.com/counselor/collector/1021741275526389/html/cc6f4a6fec214501b0efc6c6d95778db.html

    createTime: 2022-04-16 23:31

    currentTime: '2022-04-17 22:23:04'

    endTime: 2022-04-17 23:30

    formWid: '26'

    instanceWid: 897

    isHandled: 0

    isRead: 0

    priority: '5'

    senderUserName: 武玲

    startTime: 2022-04-17 21:30

    subject: 测试版--学生每日健康打卡（一日三检）

    wid: '38'

  totalSize: 1

message: SUCCESS



https://sdust.campusphere.net:443 "POST /wec-counselor-collector-apps/stu/collector/detailCollector HTTP/1.1" 200 None

https://sdust.campusphere.net:443 "POST /wec-counselor-collector-apps/stu/collector/getFormFields HTTP/1.1" 200 None

|||V-T3.7.4|||info|||10.240s|||

查询任务详情返回结果

existData: 1

isShowAnswer: false

isShowScore: false

rows:

- answerContent: null

  answerIsCorrect: null

  answerScore: null

  basicConfig:

    addressIsRequired: null

    dateFormatType: '0'

    dateType: '0'

    decimals: null

    extremeLabel: null

    isReversal: null

    leftValue: null

    level: null

    maxTime: '2099-12-31'

    maxValue: null

    minTime: '2020-01-01'

    minValue: null

    pointTime: null

    rightValue: null

    voteMaxValue: null

    voteMinValue: null

    voteType: null

  colName: field001

  description: ''

  fieldItems: []

  fieldType: '6'

  formWid: '26'

  hasOtherItems: false

  isRequired: true

  logicWid: 40

  score: null

  scoringRule: '-1'

  show: false

  sort: 1

  title: 打卡日期

  value: '2022-04-16'

  wid: '2827'

- answerContent: null

  answerIsCorrect: null

  answerScore: null

  basicConfig:

    addressIsRequired: null

    dateFormatType: null

    dateType: null

    decimals: 1

    extremeLabel: null

    isReversal: null

    leftValue: null

    level: null

    maxTime: null

    maxValue: '42'

    minTime: null

    minValue: '35'

    pointTime: null

    rightValue: null

    voteMaxValue: null

    voteMinValue: null

    voteType: null

  colName: field002

  description: ''

  fieldItems: []

  fieldType: '5'

  formWid: '26'

  hasOtherItems: false

  isRequired: true

  logicWid: 10

  score: null

  scoringRule: '-1'

  show: false

  sort: 2

  title: 今日晨间体温

  value: '36.0'

  wid: '2828'

- answerContent: null

  answerIsCorrect: null

  answerScore: null

  basicConfig:

    addressIsRequired: null

    dateFormatType: null

    dateType: null

    decimals: 1

    extremeLabel: null

    isReversal: null

    leftValue: null

    level: null

    maxTime: null

    maxValue: '42'

    minTime: null

    minValue: '35'

    pointTime: null

    rightValue: null

    voteMaxValue: null

    voteMinValue: null

    voteType: null

  colName: field003

  description: ''

  fieldItems: []

  fieldType: '5'

  formWid: '26'

  hasOtherItems: false

  isRequired: true

  logicWid: 11

  score: null

  scoringRule: '-1'

  show: false

  sort: 3

  title: 今日午间体温

  value: '35.7'

  wid: '2829'

- answerContent: null

  answerIsCorrect: null

  answerScore: null

  basicConfig:

    addressIsRequired: null

    dateFormatType: null

    dateType: null

    decimals: 1

    extremeLabel: null

    isReversal: null

    leftValue: null

    level: null

    maxTime: null

    maxValue: '42'

    minTime: null

    minValue: '35'

    pointTime: null

    rightValue: null

    voteMaxValue: null

    voteMinValue: null

    voteType: null

  colName: field004

  description: ''

  fieldItems: []

  fieldType: '5'

  formWid: '26'

  hasOtherItems: false

  isRequired: true

  logicWid: 12

  score: null

  scoringRule: '-1'

  show: false

  sort: 4

  title: 今日晚间体温

  value: '36.2'

  wid: '2830'

- answerContent: null

  answerIsCorrect: null

  answerScore: null

  basicConfig:

    addressIsRequired: null

    dateFormatType: null

    dateType: null

    decimals: null

    extremeLabel: null

    isReversal: null

    leftValue: null

    level: null

    maxTime: null

    maxValue: null

    minTime: null

    minValue: null

    pointTime: null

    rightValue: null

    voteMaxValue: null

    voteMinValue: null

    voteType: null

  colName: field005

  description: ''

  fieldItems:

  - basicConfig: null

    content: 健康

    contentExtend: ''

    imageUrl: ''

    isAnswer: false

    isOtherItems: false

    isSelected: 1

    itemWid: '7315'

    otherItemType: '1'

    score: null

    selectCount: null

    showLogic: ''

    showLogicArray: null

    totalCount: 0

  - basicConfig: null

    content: 发热、咳嗽、乏力、呕吐、腹泻、胸闷等症状

    contentExtend: ''

    imageUrl: ''

    isAnswer: false

    isOtherItems: false

    isSelected: null

    itemWid: '7316'

    otherItemType: '1'

    score: null

    selectCount: null

    showLogic: ''

    showLogicArray: null

    totalCount: 0

  - basicConfig:

      addressIsRequired: null

      dateFormatType: null

      dateType: null

      decimals: 0

      extremeLabel: null

      isReversal: null

      leftValue: null

      level: null

      maxTime: null

      maxValue: '1000'

      minTime: null

      minValue: '1'

      pointTime: null

      rightValue: null

      voteMaxValue: null

      voteMinValue: null

      voteType: null

    content: 其他

    contentExtend: ''

    imageUrl: ''

    isAnswer: false

    isOtherItems: true

    isSelected: null

    itemWid: '7317'

    otherItemType: '1'

    score: null

    selectCount: null

    showLogic: ''

    showLogicArray: null

    totalCount: 0

  fieldType: '2'

  formWid: '26'

  hasOtherItems: true

  isRequired: true

  logicWid: 17

  score: null

  scoringRule: '-1'

  show: false

  sort: 5

  answerScore: null

  title: 今日健康状况

  value: ''

  wid: '2831'

- answerContent: null

  answerIsCorrect: null

  basicConfig:

    addressIsRequired: null

    dateFormatType: null

    dateType: null

    decimals: null

    extremeLabel: null

    isReversal: null

    leftValue: null

    level: null

    maxTime: null

    maxValue: null

    minTime: null

    minValue: null

    pointTime: null

    rightValue: null

    voteMaxValue: null

    voteMinValue: null

    voteType: null

  colName: field006

  description: ''

  fieldItems:

  - basicConfig: null

    content: 是

    contentExtend: ''

    imageUrl: ''

    isAnswer: false

    isOtherItems: false

    isSelected: 1

    itemWid: '7318'

    otherItemType: '1'

    score: null

    selectCount: null

    showLogic: ''

    showLogicArray: null

    totalCount: 0

  - basicConfig: null

    content: 否

    contentExtend: ''

    imageUrl: ''

    isAnswer: false

    isOtherItems: false

    isSelected: null

    itemWid: '7319'

    otherItemType: '1'

    score: null

    selectCount: null

    showLogic: ''

    showLogicArray: null

    totalCount: 0

  fieldType: '2'

  formWid: '26'

  hasOtherItems: false

  isRequired: true

  logicWid: 42

  score: null

  scoringRule: '-1'

  show: false

  sort: 6

  title: 今日宿舍是否通风消毒

  value: ''

  wid: '2832'

- answerContent: null

  answerIsCorrect: null

  answerScore: null

  basicConfig:

    addressIsRequired: null

    dateFormatType: null

    dateType: null

    decimals: null

    extremeLabel: null

    isReversal: null

    leftValue: null

    level: null

    maxTime: null

    maxValue: null

    minTime: null

    minValue: null

    pointTime: null

    rightValue: null

    voteMaxValue: null

    voteMinValue: null

    voteType: null

  colName: field007

  description: ''

  fieldItems:

  - basicConfig: null

    content: 校内

    contentExtend: ''

    imageUrl: ''

    isAnswer: false

    isOtherItems: false

    isSelected: 1

    itemWid: '7320'

    otherItemType: '1'

    score: null

    selectCount: null

    showLogic: ''

    showLogicArray: null

    totalCount: 0

  - basicConfig: null

    content: 校外区内

    contentExtend: ''

    imageUrl: ''

    isAnswer: false

    isOtherItems: false

    isSelected: null

    itemWid: '7321'

    otherItemType: '1'

    score: null

    selectCount: null

    showLogic: ''

    showLogicArray: null

    totalCount: 0

  - basicConfig: null

    content: 区外市内

    contentExtend: ''

    imageUrl: ''

    isAnswer: false

    isOtherItems: false

    isSelected: null

    itemWid: '7322'

    otherItemType: '1'

    score: null

    selectCount: null

    showLogic: ''

    showLogicArray: null

    totalCount: 0

  - basicConfig: null

    content: 市外省内

    contentExtend: ''

    imageUrl: ''

    isAnswer: false

    isOtherItems: false

    isSelected: null

    itemWid: '7323'

    otherItemType: '1'

    score: null

    selectCount: null

    showLogic: ''

    showLogicArray: null

    totalCount: 0

  - basicConfig: null

    content: 省外境内

    contentExtend: ''

    imageUrl: ''

    isAnswer: false

    isOtherItems: false

    isSelected: null

    itemWid: '7324'

    otherItemType: '1'

    score: null

    selectCount: null

    showLogic: ''

    showLogicArray: null

    totalCount: 0

  - basicConfig: null

    content: 境外

    contentExtend: ''

    imageUrl: ''

    isAnswer: false

    isOtherItems: false

    isSelected: null

    itemWid: '7325'

    otherItemType: '1'

    score: null

    selectCount: null

    showLogic: ''

    showLogicArray: null

    totalCount: 0

  fieldType: '2'

  formWid: '26'

  hasOtherItems: false

  isRequired: true

  logicWid: 13

  score: null

  scoringRule: '-1'

  show: false

  sort: 7

  title: 目前所在区域

  value: ''

  wid: '2833'

- answerContent: null

  answerIsCorrect: null

  answerScore: null

  basicConfig:

    addressIsRequired: null

    dateFormatType: null

    dateType: null

    decimals: null

    extremeLabel: null

    isReversal: null

    leftValue: null

    level: null

    maxTime: null

    maxValue: null

    minTime: null

    minValue: null

    pointTime: null

    rightValue: null

    voteMaxValue: null

    voteMinValue: null

    voteType: null

  colName: field008

  description: ''

  fieldItems:

  - basicConfig: null

    content: 否

    contentExtend: ''

    imageUrl: ''

    isAnswer: false

    isOtherItems: false

    isSelected: 1

    itemWid: '7326'

    otherItemType: '1'

    score: null

    selectCount: null

    showLogic: ''

    showLogicArray: null

    totalCount: 0

  - basicConfig: null

    content: 是

    contentExtend: ''

    imageUrl: ''

    isAnswer: false

    isOtherItems: false

    isSelected: null

    itemWid: '7327'

    otherItemType: '1'

    score: null

    selectCount: null

    showLogic: ''

    showLogicArray: null

    totalCount: 0

  fieldType: '2'

  formWid: '26'

  hasOtherItems: false

  isRequired: true

  logicWid: 14

  score: null

  scoringRule: '-1'

  show: false

  sort: 8

  title: 近14天本人及共同生活家庭成员是否有发热、干咳、乏力、咽痛、嗅味觉减退、腹泻等症状

  value: ''

  wid: '2834'

totalSize: 8



|||V-T3.7.4|||info|||10.240s|||

填充表单


|||V-T3.7.4|||info|||10.283s|||

提交表单

data

appVersion: 9.0.14

bodyString: cWsrEUFEnj1fMH73t82WxPyN70DnvZPO4D0H1i7c2dRrUhg7RXk34FaPf+UN4gu9E+IbKxNcyQYtJpPKUXKLmrVEnLUVJ8kTIKn8bcOmoAZKmmZjEHVjCiJwpm2gEvYhQQPwwc2obs9Z0DX5GJqt2vxRVEwrCVGNpF75xGggMv+QT9XEZcUhUYX+e6atAFF4oQyZoc34mtEz7mBq5pge82kZ0UN3RMM6BvP4Sveyunmv97ccQXf9HEcHPtxEYZxicNhGDFzEJcdhqRKo5htq3sxHMQipYbGZANFU75w7OL+h0zvQUtOgdku+PbwxpdPAveSfDyiyYbR0BvxB17ynaYbfEH0uDo8J9MCbR7/Gghw9yf+qDuYZsqFY3UnwCxVQCH1qmrdkgc8NXIbOZywZ2i+Cc5yMErfBBHuW/W/GkuIyVwnOniRJiX8FAC10TFdZBiq8gyNRjIeic29KUQ3M+fYgZfyoUFvQRXSXzwe+SfFummOqd1dNmK/mRN1gdOYXdWjXs/XusZLMju/OxOC/om4y+Dt/F9TgfTh3drp888KI0WvTPfDA+UYnzyO4eFknvV1CoUcRFYzitILq9eHQrnnfbuld3zbILOK1hFZOVinprr3eSP8Py3qcknPalkAYMSzKYjSnjUudkaKfotLllDNcVQ8RucwBub7yDE4vSq4MerqEd2BLmmLfdHdi4a+rm5WumZeIwE+kfsVRakXO9so0Q8+ohnQaRwCbd5Tr44vj1bxaDLB69uHwoWpc5o3q5sQfvkEHv6NliNgZiUMeBWAQ5dX4utvdPO3S7+PGloo5INvlWgOH7r0F67WtHrbrvmSCm10zL/pFVUezJ2crtl11Om9DfBiM4T11oE0w+SeQda/s0/+6P7xgQIOhZlGyWk6P2DJBPYPLUcv9jCfKg+hc8Sq2gXiuGzHm3p0SLTLa7cSDyf4BfzBdhuH+5WBwODCuiVPlFYb67JfiizK3MSkP2+JmvDfEpEH7MzuVQl4yxv26zkNiNN1/7OddNMpTKJibF/TZgBfHEHuQGwo43Nzz9aS6TnWOfrzZ1lAWHljHqsrXr3vaB/WaAAu2/6z0w9iyGPAVgsKu3ZNagGdNGT7brfE2K2BbFhVOE6KBnfQSgXVcE7sZb9ehXRSGdhlxkZxnIvzqaSgFq5M4jQMDTfBwmUfXWBoi0I5mVnH2z+P/XSzt3z1wFBjNmZC/Kmb+T622rtKf//urlcOjIjtOtfBAuEJRhRqOD0ysrNt/T9yQ7fKtOZZwDCNep73QGiuCEWAd4+egEc/bLervfYPx8tY1qg+YHXJgCU8wghN+KeK1AhR8QjNABThhfZ4iUIYikahpRD5mH5rOHEzRi1s7qBQhsuOyRy97YQRa1euykTEHArces+Nn4F18a85kJA5XdzhCZ43icLO8Xc0bxnjJ/i+2SXRRWz4/JcV7pq9ZYr5SzDRECf+sv/y/HJjjjbXitWkIK2Ue9PVw5r7XbsCaMcUJWBNvrlkjz29hT3Jm4MwwaqkEU34eXlXwcngyVcTp9xDB6LQLX496MeUdJ/hXCjAN+B8QDy/CVR4Farn+6yG8SPzoDpyp1iaZqjbqEbQcKR9issU2ZZSd0VJO89FqCVd7ot4FpRXHHrconUs9VfGCMbX0x9HN0DNeBlwFB46GB6y3VPdtSoRIeP8cNyQzUuYjapkcp+SQmBAlnAeNyG7BV2mjBNYFWX2DQ9NuKdpRHh/SwY8KBjXk1TBzMFVHNSTejoezG0U6l/TnPTiy0YFveJwPs6RRhInt3SJTb3/P6MGyLdqaVsV8ZCfewGVOlTVET3dskhcuk/V7xCeJYcGhUji8CMnt9i4pPE2zcyxEfxKMguiTbNK/m0w3PDfTxfttrNO3pyW5MBuF8Z/69IVWiLQ+oESLRgtlwshzf/r7f9kH6wtfSBFXWLIgiqFei6EMFnrU7Rf61hnVBvm51EUC/zcwrBlg/YgUhijvNBoqfP5OgVMtrt44hXpkP6kIg3EIEa9QSoQcdgNtNImehTKM0oX8rhvgxfjId38bP67SjF6LWzDYTVUQ4E75eKTZEkjWlH91YKljKTVifhV4jvc+H6634L4i0j2DLSx9Ww8FjHdWhIaInLTDmndne0tR7MY3UPP8emBqzLfC+6Ru0UZ7yuSJKYNsGzEw8iw37UU1bjyFnJ7QZ+drueq0qEH/yJmGzK+0Oot8b6XyVs/FV295qPkPYZqRV5vMLqEgG20zp3Cv51OWNm4VGyW/Ng666N33678vDLgFCHxzegBKjDiXuyzxNyceEm6rj2LDMawlyOiLCWudTYscuvg7fi5NygDo0BMFR3LtKeywe8+cXQNBV1PPk6YAMaKHC4ugeEmJnba/ngLjF47WLq7P8SKEbMEX1zGfGi0Gd4W5mMYjomTnX8W5OwhWpNnZ2BUy9Feo2RVaWy+HUlRv0ktbwLtRYEiHJ92ALjlb8oJlMmv1PURTUR5hO+HVsj25rWHnfHTCWssVqMshY9x9ZFSvdPhiJCOeCSzB/i38/rzidTwxtVgqpknASYL5WEx6zNNBCEEHMnaQ7qJcwXdyxeNoJ+/rsO8dU0xpGEDtvU8vw1uvjB+6K3O8ZoUqIucuquVIUJhYc9cW2TFxK8tiC22QkWlh0xmcCVeVyf+mwciPd/cZ9O8p+EWYCI51Vec5xvFffO8qEXXKN/3Iy/mC8Qs/yq3psApd5r2bQzUs7TnDd3Xw12g7N21+unDG/43KzjTJqEchh7BQsMhvw5LkE4vZR8YqHLocu/OC7YYST8R9ADpkAq30dpmDxgMZFhbonk1HSXDzAK1HCKTVH9ClARCLthNko66/o7O91h2pcsRssuLhJyeZXhoTTPnL7H37wlqOzunwqNBRy3KZ/LKx+jJJYr9L8bfG6zBVE6bP8QVa0T02+5dzMJX4BOI7Cq5kMIb0euJK2W6fIuyHcMhi6fxggYuhv/ADP15TPYg4WMKvgeIofbzKB6QjuHj1ad0QkQXJ3kNg0iK2rMdpTaBgSmgy+kyrAjJ1DpFjylnJQHGykylFTpDHLfgXN6NPhRWvGAtygQZjLr62J2fhHSLpQ8n7Ho4P8zNNUXhs6tVf5It8YQsjqqkwRht6vxntSd3UAjTf8mG8GfOMdQfjMxcTkTPgfMCqSSJsK34uqKKekUjoqgmfbOMnoQtBqwAi69Qn2i/O5O+7Wr2usLzwwiUNdulGnX38PNo66K9aWr8LwDm7JB4plJ4l+GPcO+KSI68kvF8b0ot2HtvUEVVpBqM1w6mO6kVjTJc7/owMROs0OAyBAVSKd6zMaL4u1E66pUpv7aCFkdyCW+swt7jkbp9b48OGes1LWTcsL6xY2OYCSzXyD8inGCIBY806W7LOkEQH++qaoPC+C18R7imG5tLk1eRTfG+01dII9nPSHrzh+wDghTrsTMWqgEqM4Rluu0f/IlLRbG0lrUhVlz15CaPaxItWfuvzkbbzHZOOggesGGL2ehiLZKLuIzMshIEInXZBCV0bLse2bou7P/MUdxVXa260pneGGBuCJ8JInhp3RyVWSuHCcdDsbzDj2GJ6b5B59jUfwDoncHJpBJU02oFs+++DNr+zvcoYPlN1mOSEJE4fkYUkXh+akxSz8XlZgyiFM6V8Z/mxJwrBLuktS6xK/O9bDYkXdUFwntqn/6NUPLmqNAP3yFrshEaIh9dDSiySm7uLGwOvcXC5EMWch/E2cu5wYv0ybLCUco2Z816XwZwNBTMxjTV8defoJ/pWmdKP3LokXvmX7WtonuejhYwGaJR2YgEGDg5HpT5BnZ1ivbj1Ai7G1fDFCioWStLR1iuWm977EBHVvRW/KFP9HtPAFzFW+ZkGl4HFSArmb7OQf+DoXdXZAqkPIKTzSMlE3Mj/lrpocc5KDtfz3lvnb9SKgcRAr8JcDfZiNl9Dw09nLXqEQuAPnLG+LV3EixY7u58+/znTBdCS4rEzFD5Hq8BHSSPq0e4Z5hHJSf3+Sg/x0zZ0q/jy8YwDz5zDsLei67MvOKCvhT3LN2gsU/W9J4tSNlhoB9h0gUzJlLRHpARwNLGudmSK6POVwk4MwluzG+m3Sj4iaIUowBvWccq1lR9GQts3fL7xekMy8x+86SQL4y/wDIeQX5TUu1/YvDYD4bYCei59p17acOEZmE8N4L4vyUFFGIsvgeFlZULBoWh7iJAvcYnXzViirqoDBgf+Rh/LQ+96ZVyfbdHdkL++jV3Os/mXCw+PuDcMWcNIj9GE5SmkfelG1xJmGpDPRXhPkaJ/91EAkRds2anVYaaLmxpC6UfsyP6z+v3YAIGJyRXVU4uNHIHNpZOOHnqQYC8Sa/hcdnqskfIFRIo0UBrePKyYZXsrnIZrCAD8uG42+aTIYzjJi5z1qGHP1jYlsBgwzThrelZm2Rj/bI44wra5C36YgUgMevCnFUyZmXWil1YSu2mR45yOOlXVk9D0VvJkm7XdOM0WzV49/GvV8yybbQFdfl4YuWjkDhYvQB7m9fo+iaN4OGt2uP8R4s6NXY9d9FYU1FquMwn1Y+XfN3hDQ89jgi7u+445X0b+Y5geD2RWDEniaE5dN2UVBkRgoatOM9NUbaPau7BzYZumaIDRM1X18iEPlJC19RBWDVvf55MFYL0PsO9draVsBK9tSu9aIOsMkd15691aLgsBlBlyssPu1MD3eYWDMfpGWVcxtwS97su9lvq/o4RvahxZn7JR9ztTfXTjOdJqlIIQ2Nx3nN4LFXLqe+Hm8zqIfcYTZCyYy4G98sh1y8XNRL2vC+O3ICVsQVO83siVwpiz7wQ7KjYJvgwxMKEMadZaifyXbr7RNqcJOh+i+Jy1MIStNxjS4O/iLXhJ/xRA9qX1LNXnVoGWAwwCkOcXrxkAyMapt6LObLENqoVrfy83rrWlWsoOLIAoU3g3DoHRmYM//ywDVcz/AE3IbQc8G4+qZhaEXN3vhbeKn1CaJWcyAa0Wa22V/30Soy4vb0w0BxDDTz8q2zjsTaQS6eeZfcKj1ENKraiLQUQqj7yXyRsYv2LrcugrS9HJuKHoFY3C8/SAtIa5zgHIzRSpgaGxz7sdYxxVGh88F/ml7ZQiLWCBUngDQQMo9hZvgebkLN/Dbm3GpZawdhlg04D+dlVu2Bpiy8UdNqcYBWgxJz+1pm+gqZ5P3Vlf0iJ9BnzqFMa5XpeFB703ZpIXUWrCLpOiKS32K1ydw4k2vDxteCDVFJ3dIa9uBmVlWUuXizZm+cq7kV/3Ry583FS7fZ8VltwQoDb3TYxCzs42v3CJBhXJs1GPS4d2G2eI9tsDI1RE/k6ugswHx//r7YQGqcMpSiWUD0spsv7aGPqDnsghGjD1Lf3ADOGQcyTvi1r+HWTMSKuBaEv5LyN1kdT0f/plLumkWUwZqoYo4AcHzhDUIL1pvywwptHAqq2GAcA1U5fW7xdt9TG0n6bH7hHU27MREAXQdPQnRhsSHUl+Y1caiG4JyucNvh/lL3GRSeDx2bO2ohTaEtbNMWr22QIKJysAs0cbg8lLVI9p1WuT/psYqeqKWjwAm17wLXXChS/2K7AKxAfqj+pKXxdlZRTA3TU47dD0+LnaTn/swLhszgCHADmD1cAOPQXdjVXDMF8crpU8zVWt4vMIJrX42Wq0bBtl/9gF6AHw24S6l+JPUF98wtExhvLwp2r7d3vGKT53wPhL/XsnUwYjtCBApWUP99yOiJz70fm3mLS/jR2qCuGbjS9V05btqrpDQD4A6W5zDM4mhPI1J48pZstDG93cjxynSKB8R+202Bv6aRjDpJZ8mhit3gAqty3Ul6sDlRwp1fXNIDDDagqkbxjTgMlWHTjFfiB1OfFCI9L0xgX+QgPOISNJXqZjvMNdlRkeJjLZe5RV0n45vQ9Scr9uTF/bkeCpPtp+crfHWuxiEa2o3GCB/jVv8wyspef8YMAs2WSho6BusopBjihgMO6eZF4Io6KDOqa+j1IkCHbaI/LUHdzaf6y7dUxd3b2lit92DGW3nDPNhp6Pvn0rGyUvBfmop80WxIbM2hgIBpMUc9oXJqxDN4mjELmEix7H0Fwec5ETue42QTL9ij4N3pkgUOpxVa0Qv1X0tS/sltS9lwriXgv4Uzv6unXjpAD02KH3MgKEs0kePClXJsJYz0FtwS5+lms8hQTcUgrszCsGSyfaKMYh0Yvk2jqhdvVulIovbvahLcPQ3pkmwWXoV+ndFkze4npMLWj110feWlelrloqtpP07i5gYRwTkOiaOvahYt2PqmhXBlACCiO5JeuRHgTlOgYfkSvn3s6kbcDmMcI6LqiX/pBYKhdGFBpTaWYoWU75BN/ptjMBXmxbsaZG+m0XDeAazgFl8K0ZiinXve2GXjZVjG0WUT9jIRIiKaSiOQ/a5V4bjhzwKdbmbo5zqvuMh5I/hHbO4W5igaz/4QpgShE3tXD75/BTgiOGOeTdm2vJQMldOLQRuXkiLDzgLF5/irrMiC0yOzJSf3Bfbc0tH75Qhh3NZmdrwOAmZu7gXJZhq7WHs7ybe468TxcAsg8gXUy9rRNBLuj6s3j+FoDKt3AjBWP+iPlOLDOjiEPk34Y4Xtzsy3Mvs1SNOBIZ/Vfwd3srh7sC5HrDIkfEFNFMx+Uvsz3MnPxMIbWAFIEVdd9Sn7l7ip9RlURluXD2J1upz9tbvMfCf8kVWyuaJLgoIla/Vs9En6DKVB+VNSrFGbjTWkEjz7UAd3K4DbFEDodboJDMWXHZNZK/ZEihkK2u3Pf6G2FRvvGq17RGA7VRdpoXJbXoHxCyG9ufElkDmbdYxuvITYaHyxWzankwsRNQGf1iNZzSfEMuXIAbe8ET0j6WFFqVUc9jhqIzNZiBaMCCtYzOelkgiZONlanDOCrYIFyshKLi0vXU/QjBxK2901unubLjnUpbKCe1+7S0E0OooPmPS+qzRUOd4YdAaIPrsVWW4Ig/KyYc/bc96oUVSrwAOivVzrZ46r1YWZiGN09KCJqplBIhAybScqA3j2yJxIZ+lkDp9hDuihbtldtoSOFb3SEwar7Ep7542k48PJq1yrGYvA83fgr4/PhVpkZa3DTj+5FvgUfUuyRvXlEQE56kQjg9wm+5OWUhbQyrY8XAjDQL5smz063EhLLkqV14/QAg57EHREVa4dSlHwIAgRFPS1A+IskX/r9L78VkT0FjMcVdO/UxjfsHA5yQhuWnVw/153U5Km6d9Mc1TZQRTooTXUMki+TEc3igndfQpoVa59CKCNcVf1g2wMR0YBmP9z7weF0vNsRanTpgi3206bhazHZ+aErMay+Cw6GFzF3MrzcUULSH4eKJAsCfxc2LKw7XMrNg50BZAQoMfjccP6x1yxSj7v839tbCGUr+izmacPhgNRx4sZXBUoTgfDZMsKyh0LNeKJMDjEqrRUSmrSlhk/g+SuITZkpVgBuhyQF2PYRZl84T1HnUdnNi7oTYASByatF4qQufuSWuUBJXhZJp1425KIyn3IuCWABvvq50PbrVDfqe0iye+M0YVFucp7Ebvz6aQ+b8tLmcGbOLww8xgj86pTYTtpxTlnBYmq6hhw6zBrBRwkGEu9E84RluG7euQ7IUbL9KWJXbQACQ+OWIZvKdVWHr5z1s4hwWC6SK4+de+mOX2veHLlTv68YjwFzlNhxfofKsp40IVtMpX+BoZlFQK5Lt7W9RFoWF5sfA5bc1rF6hy6MlSbGDKMROhJV9bjSxE7Y6LgUAaseTDEWT94tOK6qpRlYF5SqwhooEEHncYOmsDZW5P/C+JcaX9yNPjuJ6DU8J3a0ldm4MSVIP1Jh5fF2K6CjzLwCR0Ts2nfNdgHdZMeRpYl6mk12ycvTHe6nmQU+9wC4amw/uy+3f9mtXQ4xgojvrH3pr62J075nOUrwDZqoN4eblECVQcnz8SR7VYGO9r+/S0kYnTBUr8hkuoMiujtquWtnRJGOWg6k03eZSCu9mmDyI8o0RbYtaPSgsaAFZ8JBk+YxDeE7Rj15wgRr743u+yM25e0jJ8x6nk75fLLvRd5dbocjDlQK0WYOIJv/VbxPsW8cq+AAnaQfSSZD9AqTtIjZu2gUfVAZ1eLS58vpv0YSgZWv0s9LmUFHobWYCFuNCgVbzaT5xZzqDJtTHPLlF532CwZimZhhPpyzahCKfO1hj5b4SgfprkCRrf9tcEKCrm5Gv

calVersion: firstv

deviceId: BB412EAB-213C-9092-6017-64911818756F

lat: 38.012794

lon: 112.123942

model: OPPO R11 Plus

sign: 44443883e7a6f6699a62c7f7cda303c2

systemName: android

systemVersion: 4.4.4

**Comment by IceTiki** [comment]
有联系方式吗XD

**Comment by IceTiki** [comment]
看样子日志太长了，不是很完整..

**Comment by IceTiki** [comment]
顺便一提，下次日志记得一定要截出出错的位置

**Comment by eb66** [comment]
> 有联系方式吗XD

qq:2099234132

**Comment by IceTiki** [comment]
(删掉了两个包含你个人信息的回复)
