### ISSUE TITLE
告警通知

### ISSUE THREAD

**Issue by 1955782864** [IceTiki/ruoli-sign-optimization#55]
今天签到推送显示告警通知是怎么一回事啊

**Comment by IceTiki** [comment]
> 今天签到推送显示告警通知是怎么一回事啊

给下日志，要有报错部分

**Comment by IceTiki** [comment]
> > 今天签到推送显示告警通知是怎么一回事啊
> 
> 给下日志，要有报错部分

以及签到整体情况部分

**Comment by IceTiki** [comment]
> 今天签到推送显示告警通知是怎么一回事啊

![-4ece423099932b0.jpg](https://user-images.githubusercontent.com/61530581/164583597-bf5a32f7-78b5-4d01-b4ad-53654dc09f71.jpg)

**Comment by IceTiki** [comment]
> 今天签到推送显示告警通知是怎么一回事啊

是pushplus的问题，请咨询相关群组/人员。

**Comment by 1955782864** [comment]
不影响签到，哈哈

**Comment by 1955782864** [comment]
只是推送标题变了
