### ISSUE TITLE
关于早卡和午卡晚卡签到里多一个附加信息如何解决

### ISSUE THREAD

**Issue by afterlif** [IceTiki/ruoli-sign-optimization#56]
作者您好，我的早卡里比午卡和晚卡多一个额外附加信息需要选择，请问除了使用额外一个脚本单独针对早卡，以及在一个脚本里面设置两个同用户但是不同的forms以外 还有什么解决方案吗。

**Comment by IceTiki** [comment]
> 个人是一个脚本里两个同用户解决的 顺便问一下有没有本地自动化的方法呢？

本地自动化的话 你是打算用windows的计划任务?
如果有不同任务我也是用多用户解决的，现在**新版本**的仓库还可以限定任务的执行时间(非时间段自动跳过)
