### ISSUE TITLE
云函数测试报错

### ISSUE THREAD

**Issue by afterlif** [IceTiki/ruoli-sign-optimization#57]
想请问一下，部署云函数以后测试出现以下报错是什么原因呢 谢谢。
执行日志
START RequestId: 5b246a42-e70e-4496-a04a-2f58ac220aac

==========脚本开始初始化==========

Init Report RequestId: 5b246a42-e70e-4496-a04a-2f58ac220aac Coldstart: 688ms (PullCode: 316ms InitRuntime: 4ms InitFunction: 368ms) Memory: 128MB MemUsage: 11.71MB

ERROR RequestId: 5b246a42-e70e-4496-a04a-2f58ac220aac Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python37/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python37/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python37/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python37/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 728, in exec_module   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed   File "/var/user/index.py", line 54, in <module>     from liteTools import TaskError, RT, DT, LL, NT, MT, ST   File "/var/user/liteTools.py", line 2, in <module>     from types import NoneType ImportError: cannot import name 'NoneType' from 'types' (/var/lang/python37/lib/python3.7/types.py)", "statusCode": 443}

END RequestId: 5b246a42-e70e-4496-a04a-2f58ac220aac

Report RequestId: 5b246a42-e70e-4496-a04a-2f58ac220aac Duration: 0ms Memory: 128MB MemUsage: 11.71MB

**Comment by IceTiki** [comment]
你去litetools.py的头部删掉`from types import NoneType`就可用了。
之前用vscode的时候，它自动增加了这行没用的代码。

**Comment by afterlif** [comment]
> 

谢谢！已经解决。然后我在云函数中配置photo参数 我上传了一个文件夹里面有好几张照片，我photo指向的是图片文件夹，我看高级配置教程中说如果指向文件夹则会随机选择一张图片，可是每一次都只会调用第一张照片，请问是怎么回事。

**Comment by afterlif** [comment]
解决了，非常感谢，感谢你维护这个脚本，谢谢！
