### ISSUE TITLE
获取历史信息，查寝签到失败，用的是腾讯云函数

### ISSUE THREAD

**Issue by cuncun-edg** [IceTiki/ruoli-sign-optimization#59]
![image](https://user-images.githubusercontent.com/77426305/165760275-077e80fc-cb9b-4060-b53b-a8150777d1a7.png)

**Comment by IceTiki** [comment]
> 
> ![image](https://user-images.githubusercontent.com/77426305/165760275-077e80fc-cb9b-4060-b53b-a8150777d1a7.png)
> 

今天更新出的bug，你再更新下试试_(:з」∠)_

**Comment by IceTiki** [comment]
应该今天早上这个版本就好了，昨天大改了很多机制，所以存留了一些bug

**Comment by cuncun-edg** [comment]
> 我只配置了查寝签到，并增加了使用历史信息签到，
START RequestId: 54997f6c-1165-4bbb-b7e0-45306b294fff==========脚本开始初始化==========
Init Report RequestId: 54997f6c-1165-4bbb-b7e0-45306b294fff Coldstart: 1696ms (PullCode: 229ms InitRuntime: 4ms InitFunction: 1463ms) Memory: 128MB MemUsage: 27.57MB==========脚本开始执行==========
|||V-T3.8.5b|||info|||0.318s|||
正在初始化200628590213的配置

|||V-T3.8.5b|||info|||0.319s|||
正在初始化200628590213的配置

|||V-T3.8.5b|||info|||0.320s|||
正在初始化200628590213的配置

|||V-T3.8.5b|||info|||0.320s|||
正在进行第1轮尝试

|||V-T3.8.5b|||info|||0.320s|||
即将在第1轮尝试中为[200628590213]签到

|||V-T3.8.5b|||debug|||0.320s|||
程序正在暂停8.049秒

|||V-T3.8.5b|||info|||8.377s|||
准备登录

Starting new HTTPS connection (1): mobile.campushoy.com:443
https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None
|||V-T3.8.5b|||warn|||8.925s|||
学校接入今日校园方式为NOTCLOUD

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/info?ids=jxxdxy HTTP/1.1" 200 None
Starting new HTTPS connection (1): jxxdxy.campusphere.net:443
https://jxxdxy.campusphere.net:443 "GET /wec-portal-mobile/client HTTP/1.1" 301 178
https://jxxdxy.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 302 154
https://jxxdxy.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Fjxxdxy.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 302 0
Starting new HTTP connection (1): authserver.jxxdxy.com:80
http://authserver.jxxdxy.com:80 "GET /authserver/login?service=https%3A%2F%2Fjxxdxy.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D79688681239a4d779a52a3f180d60328 HTTP/1.1" 200 None
http://authserver.jxxdxy.com:80 "GET /authserver/login?service=https%3A%2F%2Fjxxdxy.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D79688681239a4d779a52a3f180d60328 HTTP/1.1" 200 None
http://authserver.jxxdxy.com:80 "GET /authserver/needCaptcha.html?username=200628590213 HTTP/1.1" 200 5
http://authserver.jxxdxy.com:80 "POST /authserver/login?service=https%3A%2F%2Fjxxdxy.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D79688681239a4d779a52a3f180d60328&username=200628590213&password=9wl0z8dzd3H%2ByUU7BNTX0MP%2Ffm%2BkcITxxVnMswGkpsAeKDPlbj9I7GWwovqlamhI%2BzRJjM9y5278%0AG67D2NaJWOotUquQnn%2Bx1Rm22FPcKm4%3D&lt=LT-659663-bE3aH9sEAJzA0sZhVUEhifhbTR0NFm1651198607447-zdsZ-cas&dllt=userNamePasswordLogin&execution=e2s1&_eventId=submit&rmShown=1 HTTP/1.1" 302 None
https://jxxdxy.campusphere.net:443 "GET /iap/loginSuccess?sessionToken=79688681239a4d779a52a3f180d60328&ticket=ST-1299513-IgafBpahP1Ybbepf2kIF1651198607643-q0fH-cas HTTP/1.1" 302 0
https://jxxdxy.campusphere.net:443 "GET /wec-portal-mobile/client/?ticket=ST-iap:1018615964278445:ST:5fb8c720-dc41-4a09-8e73-43e2c2467010:20220429101647 HTTP/1.1" 302 154
https://jxxdxy.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 404 710
http://authserver.jxxdxy.com:80 "GET / HTTP/1.1" 200 612
|||V-T3.8.5b|||error|||10.245s|||
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
['6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52']
Traceback (most recent call last):
  File "/var/user/index.py", line 275, in main
    userSessions[userId]['session'] = userSession
KeyError: '6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52'

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
200628590213签到失败['6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52']
Traceback (most recent call last):
  File "/var/user/index.py", line 275, in main
    userSessions[userId]['session'] = userSession
KeyError: '6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52'


|||V-T3.8.5b|||info|||10.245s|||
--200628590213|1
--['6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52']
Traceback (most recent call last):
  File "/var/user/index.py", line 275, in main
    userSessions[userId]['session'] = userSession
KeyError: '6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52'


|||V-T3.8.5b|||info|||10.245s|||
推送情况

QMSG酱|无效配置
SMTP|无效配置
若离邮箱API|无效配置
IceCream|无效配置
Pushplus|无效配置

|||V-T3.8.5b|||info|||10.245s|||
即将在第1轮尝试中为[200628590213]签到

|||V-T3.8.5b|||debug|||10.245s|||
程序正在暂停5.149秒

|||V-T3.8.5b|||info|||15.399s|||
准备登录

Starting new HTTPS connection (1): mobile.campushoy.com:443
https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None
|||V-T3.8.5b|||warn|||15.861s|||
学校接入今日校园方式为NOTCLOUD

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/info?ids=jxxdxy HTTP/1.1" 200 None
Starting new HTTPS connection (1): jxxdxy.campusphere.net:443
https://jxxdxy.campusphere.net:443 "GET /wec-portal-mobile/client HTTP/1.1" 301 178
https://jxxdxy.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 302 154
https://jxxdxy.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Fjxxdxy.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 302 0
Starting new HTTP connection (1): authserver.jxxdxy.com:80
http://authserver.jxxdxy.com:80 "GET /authserver/login?service=https%3A%2F%2Fjxxdxy.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D178e35836bbe4a92b9e88d0cf08a8991 HTTP/1.1" 200 None
http://authserver.jxxdxy.com:80 "GET /authserver/login?service=https%3A%2F%2Fjxxdxy.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D178e35836bbe4a92b9e88d0cf08a8991 HTTP/1.1" 200 None
http://authserver.jxxdxy.com:80 "GET /authserver/needCaptcha.html?username=200628590213 HTTP/1.1" 200 5
http://authserver.jxxdxy.com:80 "POST /authserver/login?service=https%3A%2F%2Fjxxdxy.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D178e35836bbe4a92b9e88d0cf08a8991&username=200628590213&password=KlKa9RqQvS5kWBXY3%2BmBWvam9wS%2BPgE4T8A5%2FvjPJvfYvXqr1NO3ELQGTvnOs%2BP%2BB7wjICTxzDcR%0ApIKXkfNGGAa8ec9UfinfbhCJxH4iq0U%3D&lt=LT-662841-yGLoV0LQZZT6WLENj2MleymI7gWeH01651198613940-335f-cas&dllt=userNamePasswordLogin&execution=e2s1&_eventId=submit&rmShown=1 HTTP/1.1" 302 None
https://jxxdxy.campusphere.net:443 "GET /iap/loginSuccess?sessionToken=178e35836bbe4a92b9e88d0cf08a8991&ticket=ST-1277899-RjpXBMnOuvzGn2CrKEKf1651198614173-dcS0-cas HTTP/1.1" 302 0
https://jxxdxy.campusphere.net:443 "GET /wec-portal-mobile/client/?ticket=ST-iap:1018615964278445:ST:031981c2-41de-499b-be24-02db36c7a33c:20220429101654 HTTP/1.1" 302 154
https://jxxdxy.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 404 710
http://authserver.jxxdxy.com:80 "GET / HTTP/1.1" 200 612
|||V-T3.8.5b|||error|||16.760s|||
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
['6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52']
Traceback (most recent call last):
  File "/var/user/index.py", line 275, in main
    userSessions[userId]['session'] = userSession
KeyError: '6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52'

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
200628590213签到失败['6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52']
Traceback (most recent call last):
  File "/var/user/index.py", line 275, in main
    userSessions[userId]['session'] = userSession
KeyError: '6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52'


|||V-T3.8.5b|||info|||16.760s|||
--200628590213|1
--['6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52']
Traceback (most recent call last):
  File "/var/user/index.py", line 275, in main
    userSessions[userId]['session'] = userSession
KeyError: '6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52'


|||V-T3.8.5b|||info|||16.760s|||
推送情况

QMSG酱|无效配置
SMTP|无效配置
若离邮箱API|无效配置
IceCream|无效配置
Pushplus|无效配置

|||V-T3.8.5b|||info|||16.760s|||
即将在第1轮尝试中为[200628590213]签到

|||V-T3.8.5b|||debug|||16.761s|||
程序正在暂停7.290秒

|||V-T3.8.5b|||info|||24.057s|||
准备登录

Starting new HTTPS connection (1): mobile.campushoy.com:443
https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None
|||V-T3.8.5b|||warn|||24.423s|||
学校接入今日校园方式为NOTCLOUD

https://mobile.campushoy.com:443 "GET /v6/config/guest/tenant/info?ids=jxxdxy HTTP/1.1" 200 None
Starting new HTTPS connection (1): jxxdxy.campusphere.net:443
https://jxxdxy.campusphere.net:443 "GET /wec-portal-mobile/client HTTP/1.1" 301 178
https://jxxdxy.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 302 154
https://jxxdxy.campusphere.net:443 "GET /iap/login?service=https%3A%2F%2Fjxxdxy.campusphere.net%2Fwec-portal-mobile%2Fclient%2F HTTP/1.1" 302 0
Starting new HTTP connection (1): authserver.jxxdxy.com:80
http://authserver.jxxdxy.com:80 "GET /authserver/login?service=https%3A%2F%2Fjxxdxy.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D872ea14a7c9b48c9b0700ba38950cf84 HTTP/1.1" 200 None
http://authserver.jxxdxy.com:80 "GET /authserver/login?service=https%3A%2F%2Fjxxdxy.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D872ea14a7c9b48c9b0700ba38950cf84 HTTP/1.1" 200 None
http://authserver.jxxdxy.com:80 "GET /authserver/needCaptcha.html?username=200628590213 HTTP/1.1" 200 5
http://authserver.jxxdxy.com:80 "POST /authserver/login?service=https%3A%2F%2Fjxxdxy.campusphere.net%2Fiap%2FloginSuccess%3FsessionToken%3D872ea14a7c9b48c9b0700ba38950cf84&username=200628590213&password=hAVuRXKkdAzxqh4jjY3NcApYqEOuJqpXV%2BYuwIhdScJCrLH7C%2BLuwBNCeHHVbRWWc6AO%2B3YeMRqM%0AYslG8Siq2D4Ccd%2FZCfWqhwhazqaeBis%3D&lt=LT-659668-RldXiFRCgwdbmfbV6y7cA3MiIfhRVo1651198622503-zdsZ-cas&dllt=userNamePasswordLogin&execution=e2s1&_eventId=submit&rmShown=1 HTTP/1.1" 302 None
https://jxxdxy.campusphere.net:443 "GET /iap/loginSuccess?sessionToken=872ea14a7c9b48c9b0700ba38950cf84&ticket=ST-1299515-YUEpzRyVpl5EsgCunkIa1651198622683-q0fH-cas HTTP/1.1" 302 0
https://jxxdxy.campusphere.net:443 "GET /wec-portal-mobile/client/?ticket=ST-iap:1018615964278445:ST:c374a9a0-e76a-43b4-84fe-ebc2215e12d6:20220429101702 HTTP/1.1" 302 154
https://jxxdxy.campusphere.net:443 "GET /wec-portal-mobile/client/ HTTP/1.1" 404 710
http://authserver.jxxdxy.com:80 "GET / HTTP/1.1" 200 612
|||V-T3.8.5b|||error|||25.273s|||
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
['6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52']
Traceback (most recent call last):
  File "/var/user/index.py", line 275, in main
    userSessions[userId]['session'] = userSession
KeyError: '6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52'

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
200628590213签到失败['6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52']
Traceback (most recent call last):
  File "/var/user/index.py", line 275, in main
    userSessions[userId]['session'] = userSession
KeyError: '6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52'


|||V-T3.8.5b|||info|||25.273s|||
--200628590213|1
--['6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52']
Traceback (most recent call last):
  File "/var/user/index.py", line 275, in main
    userSessions[userId]['session'] = userSession
KeyError: '6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52'


|||V-T3.8.5b|||info|||25.274s|||
推送情况

QMSG酱|无效配置
SMTP|无效配置
若离邮箱API|无效配置
IceCream|无效配置
Pushplus|无效配置

|||V-T3.8.5b|||info|||25.274s|||
『[V-T3.8.5b]全局签到情况(0/3)』
[默认备注名]
--200628590213|1
--['6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52']
Traceback (most recent call last):
  File "/var/user/index.py", line 275, in main
    userSessions[userId]['session'] = userSession
KeyError: '6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52'

[默认备注名]
--200628590213|1
--['6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52']
Traceback (most recent call last):
  File "/var/user/index.py", line 275, in main
    userSessions[userId]['session'] = userSession
KeyError: '6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52'

[默认备注名]
--200628590213|1
--['6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52']
Traceback (most recent call last):
  File "/var/user/index.py", line 275, in main
    userSessions[userId]['session'] = userSession
KeyError: '6f20934a46fecc7dff03ca88e2da7d6133afe665b9d08f5861faefe3f8b9ff52'



|||V-T3.8.5b|||info|||25.274s|||
推送情况

QMSG酱|无效配置
SMTP|无效配置
若离邮箱API|无效配置
IceCream|无效配置
Pushplus|无效配置

Response RequestId: 54997f6c-1165-4bbb-b7e0-45306b294fff RetMsg: "ok"END RequestId: 54997f6c-1165-4bbb-b7e0-45306b294fffReport RequestId: 54997f6c-1165-4bbb-b7e0-45306b294fff Duration: 24971ms Memory: 128MB MemUsage: 34.33MB

**Comment by IceTiki** [comment]
今早测试发现这个问题了，3.8.5c修复了这个问题

**Comment by IceTiki** [comment]
昨天大改了很多内容难免出bug
_(´ཀ`」 ∠)__

**Comment by IceTiki** [comment]
只修改了两个文件，更新就好

**Comment by IceTiki** [comment]
中午测试发现当没有任务时，报错会出问题，这个在3.8.5d修复了。

**Comment by cuncun-edg** [comment]
中午之前测试，没有任务会报错，我觉得问题不大就没有反馈，还有腾讯云函数更新代码有什么更方便快捷的操作吗？

**Comment by IceTiki** [comment]
> 中午之前测试，没有任务会报错，我觉得问题不大就没有反馈，还有腾讯云函数更新代码有什么更方便快捷的操作吗？

不是很清楚，我也是只知道直接替换文件
