### ISSUE TITLE
新版Pushplus 日志 发送成功，实际却未收到

### ISSUE THREAD

**Issue by cuncun-edg** [IceTiki/ruoli-sign-optimization#61]
![image](https://user-images.githubusercontent.com/77426305/166230988-a94d5355-39d2-4170-88cc-693b21e15f3e.png)
![image](https://user-images.githubusercontent.com/77426305/166231116-5c470ddf-aa22-45df-b63c-3fdfcb4ea5c3.png)

**Comment by IceTiki** [comment]
> ![image](https://user-images.githubusercontent.com/77426305/166230988-a94d5355-39d2-4170-88cc-693b21e15f3e.png)
> ![image](https://user-images.githubusercontent.com/77426305/166231116-5c470ddf-aa22-45df-b63c-3fdfcb4ea5c3.png)
> 

有可能是pushplus的问题或者是你没按照pushplus的教程配置好(比如没关注公众号或者关注错了之类的)

**Comment by cuncun-edg** [comment]
平时都正常使用pushplus，所以应该不是我的配置问题

**Comment by IceTiki** [comment]
> 平时都正常使用pushplus，所以应该不是我的配置问题

可能是pushplus出问题了。给的信息太少无法判断问题在哪里。
