### ISSUE TITLE
打卡失败

### ISSUE THREAD

**Issue by PpGoood** [IceTiki/ruoli-sign-optimization#63]
![QQ截图20220511183310](https://user-images.githubusercontent.com/105357668/167860112-ec9f7c27-3f3f-4f4a-a488-0b5d79042ed3.png)

打卡报错Crypto 报错这个库

**Comment by IceTiki** [comment]
看日志里面的中文

**Comment by IceTiki** [comment]
看图片里面的中文进行操作

**Comment by IceTiki** [comment]
依赖出问题也许删了重新安装就能解决吧

**Comment by IceTiki** [comment]
我觉得报错已经把问题说得很清楚了(?)

**Comment by PpGoood** [comment]
我是小白 我不会安装呜呜呜 网上搜了好多安装的方法还是报错为什么啊

**Comment by PpGoood** [comment]
太菜了我

**Comment by IceTiki** [comment]
https://github.com/IceTiki/ruoli-sign-optimization/blob/master/documents/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95.md

**Comment by IceTiki** [comment]
建议重新下载代码，因为有些依赖和代码文件混在一起分不出来。配置可以保留。
然后按照上面的说明书来做，

**Comment by PpGoood** [comment]
感谢大神重新下了一遍解决了
