### ISSUE TITLE
运行查寝，出现无效的URl，麻烦帮我看一下日志，是哪里的问题，感谢。

### ISSUE THREAD

**Issue by President-M** [IceTiki/ruoli-sign-optimization#64]

**Comment by President-M** [comment]
麻烦帮我看一下这个报错是什么原因，我该怎样设置？
<img width="1131" alt="截屏2022-05-15 01 51 39" src="https://user-images.githubusercontent.com/88828830/168443143-3818987e-fa86-4401-bb64-ee08a6126ec8.png">

**Comment by IceTiki** [comment]
似乎是验证服务器拒绝了你的连接请求。可能的原因有

1. 当前时间段用的人比较多/你请求的次数太密集，换个时间试试。
2. 你们学校教务系统没法登录(?)
