### ISSUE TITLE
阿里云

### ISSUE THREAD

**Issue by 532355805** [IceTiki/ruoli-sign-optimization#65]
{
    "ErrorCode": "CAFileNotFound",
    "ErrorMessage": "The function cannot be started. ContainerStartDuration:0 seconds. Error: Bootstrap file is missing,Error response from daemon: invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"exec: \\\\\\\"/code/bootstrap\\\\\\\": stat /code/bootstrap: no such file or directory\\\"\\n\""
}

**Comment by IceTiki** [comment]
我好像没有遇到过这个问题，可能要自己百度寻找答案。（看起来是阿里云函数的问题)

**Comment by huyqkk** [comment]
{
    "ErrorCode": "CAFileNotFound",
    "ErrorMessage": "The function cannot be started. ContainerStartDuration:0 seconds. Error: Bootstrap file is missing,Error response from daemon: invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"exec: \\\\\\\"/code/bootstrap\\\\\\\": stat /code/bootstrap: no such file or directory\\\"\\n\""
}

如何修复这个问题？
Custom Runtime 的本质是要启动一个 HTTP Server 用来处理您的请求。您需要在函数配置页签中配置启动命令和启动参数来启动您的 HTTP Server。或者，您也可以在代码包的根目录下添加一个可执行的文件名为 bootstrap 的文件，此文件可以为可执行的二进制文件，也可以为一个可执行的脚本。点击[这里](https://help.aliyun.com/document_detail/425055.html)查看更多详情。

请问这个要怎么解决呢

**Comment by IceTiki** [comment]
对不起，我基本没用过阿里云函数，不是很清楚

**Comment by IceTiki** [comment]
每一种服务都有不同的特性，不是每一个我都知道
![#c=芙莉莲#mtl=葬送的芙莉莲#m=第4话 魔法使的秘密##摸鱼 1252f2e183d886472ccf86e75e1dd0d889655e50 jpg@1100w](https://user-images.githubusercontent.com/61530581/171782035-9f97b4f9-5570-4567-b351-fd8c6a5337ca.jpg)
