### ISSUE TITLE
新版pushplus不能推送

### ISSUE THREAD

**Issue by eb66** [IceTiki/ruoli-sign-optimization#66]
如题，日志显示推送成功，实际收不到。几个月前pushplus新版就不能推送，换了旧版的pushplus就正常了，但现在旧版停止服务了。Running at 2022-06-01 16:50:23, using 63.19s

6: 0todo, 0done, 0skip, 6error, 0notFound

Starting new HTTPS connection (1): www.pushplus.plus:443

https://www.pushplus.plus:443 "POST /send?token=729753ad24524e64a25eadda94d2c16b&title=%E5%85%A8%E5%B1%80%E7%AD%BE%E5%88%B0%E6%83%85%E5%86%B5%280%2F6%29&content=%E3%80%8E%5BV-T3.8.8c%5D%E5%85%A8%E5%B1%80%E7%AD%BE%E5%88%B0%E6%83%85%E5%86%B5%280%2F6%29%E3%80%8F%3C%2Fbr%3E%5B%E9%BB%98%E8%AE%A4%E5%A4%87%E6%B3%A8%E5%90%8D%5D%3C%2Fbr%3E--201901111419%7C1%3C%2Fbr%3E--%E3%80%8E%7Bself.taskName%7D%E3%80%8F%E6%8F%90%E4%BA%A4%E8%A1%A8%E5%8D%95%E8%BF%94%E5%9B%9E%E3%80%8E%7B%27code%27%3A+%272210990000%27%2C+%27message%27%3A+%27%E6%9F%A5%E5%AF%9D%E6%9C%AA%E5%BC%80%E5%A7%8B%27%7D%E3%80%8F%E4%B8%94%E4%BB%BB%E5%8A%A1%E7%8A%B6%E6%80%81%E4%BB%8D%E6%98%AF%E6%9C%AA%E7%AD%BE%E5%88%B0%3C%2Fbr%3E%5B%E9%BB%98%E8%AE%A4%E5%A4%87%E6%B3%A8%E5%90%8D%5D%3C%2Fbr%3E--201901111414%7C1%3C%2Fbr%3E--%E3%80%8E%7Bself.taskName%7D%E3%80%8F%E6%8F%90%E4%BA%A4%E8%A1%A8%E5%8D%95%E8%BF%94%E5%9B%9E%E3%80%8E%7B%27code%27%3A+%272210990000%27%2C+%27message%27%3A+%27%E6%9F%A5%E5%AF%9D%E6%9C%AA%E5%BC%80%E5%A7%8B%27%7D%E3%80%8F%E4%B8%94%E4%BB%BB%E5%8A%A1%E7%8A%B6%E6%80%81%E4%BB%8D%E6%98%AF%E6%9C%AA%E7%AD%BE%E5%88%B0%3C%2Fbr%3E%5B%E9%BB%98%E8%AE%A4%E5%A4%87%E6%B3%A8%E5%90%8D%5D%3C%2Fbr%3E--201901111413%7C1%3C%2Fbr%3E--%E3%80%8E%7Bself.taskName%7D%E3%80%8F%E6%8F%90%E4%BA%A4%E8%A1%A8%E5%8D%95%E8%BF%94%E5%9B%9E%E3%80%8E%7B%27code%27%3A+%272210990000%27%2C+%27message%27%3A+%27%E6%9F%A5%E5%AF%9D%E6%9C%AA%E5%BC%80%E5%A7%8B%27%7D%E3%80%8F%E4%B8%94%E4%BB%BB%E5%8A%A1%E7%8A%B6%E6%80%81%E4%BB%8D%E6%98%AF%E6%9C%AA%E7%AD%BE%E5%88%B0%3C%2Fbr%3E%5B%E9%BB%98%E8%AE%A4%E5%A4%87%E6%B3%A8%E5%90%8D%5D%3C%2Fbr%3E--201901111406%7C1%3C%2Fbr%3E--%E3%80%8E%7Bself.taskName%7D%E3%80%8F%E6%8F%90%E4%BA%A4%E8%A1%A8%E5%8D%95%E8%BF%94%E5%9B%9E%E3%80%8E%7B%27code%27%3A+%272210990000%27%2C+%27message%27%3A+%27%E6%9F%A5%E5%AF%9D%E6%9C%AA%E5%BC%80%E5%A7%8B%27%7D%E3%80%8F%E4%B8%94%E4%BB%BB%E5%8A%A1%E7%8A%B6%E6%80%81%E4%BB%8D%E6%98%AF%E6%9C%AA%E7%AD%BE%E5%88%B0%3C%2Fbr%3E%5B%E9%BB%98%E8%AE%A4%E5%A4%87%E6%B3%A8%E5%90%8D%5D%3C%2Fbr%3E--201901111420%7C1%3C%2Fbr%3E--%E3%80%8E%7Bself.taskName%7D%E3%80%8F%E6%8F%90%E4%BA%A4%E8%A1%A8%E5%8D%95%E8%BF%94%E5%9B%9E%E3%80%8E%7B%27code%27%3A+%272210990000%27%2C+%27message%27%3A+%27%E6%9F%A5%E5%AF%9D%E6%9C%AA%E5%BC%80%E5%A7%8B%27%7D%E3%80%8F%E4%B8%94%E4%BB%BB%E5%8A%A1%E7%8A%B6%E6%80%81%E4%BB%8D%E6%98%AF%E6%9C%AA%E7%AD%BE%E5%88%B0%3C%2Fbr%3E%5B%E9%BB%98%E8%AE%A4%E5%A4%87%E6%B3%A8%E5%90%8D%5D%3C%2Fbr%3E--201901111407%7C1%3C%2Fbr%3E--%E3%80%8E%7Bself.taskName%7D%E3%80%8F%E6%8F%90%E4%BA%A4%E8%A1%A8%E5%8D%95%E8%BF%94%E5%9B%9E%E3%80%8E%7B%27code%27%3A+%272210990000%27%2C+%27message%27%3A+%27%E6%9F%A5%E5%AF%9D%E6%9C%AA%E5%BC%80%E5%A7%8B%27%7D%E3%80%8F%E4%B8%94%E4%BB%BB%E5%8A%A1%E7%8A%B6%E6%80%81%E4%BB%8D%E6%98%AF%E6%9C%AA%E7%AD%BE%E5%88%B0%3C%2Fbr%3ERunning+at+2022-06-01+16%3A50%3A23%2C+using+63.19s%3C%2Fbr%3E6%3A+0todo%2C+0done%2C+0skip%2C+6error%2C+0notFound%3C%2Fbr%3E HTTP/1.1" 200 None

|||V-T3.8.8c|||info|||63.408s|||

全局推送情况

推送情况

QMSG酱|无效配置

SMTP|无效配置

若离邮箱API|无效配置

IceCream|无效配置

Pushplus|发送成功

Response RequestId: 1e315bb9-9779-43d7-95c8-2d28e9a1e1e0 RetMsg: "ok"

END RequestId: 1e315bb9-9779-43d7-95c8-2d28e9a1e1e0

Report RequestId: 1e315bb9-9779-43d7-95c8-2d28e9a1e1e0 Duration: 63158ms Memory: 128MB MemUsage: 32.95MB

**Comment by IceTiki** [comment]
这个应该是Pushplus的问题，嘚问pushplus相关人员。
