### ISSUE TITLE
可以写给用腾讯云服务器部署的教程吗？

### ISSUE THREAD

**Issue by cuncun-edg** [IceTiki/ruoli-sign-optimization#67]
腾讯云函数收费了

**Comment by IceTiki** [comment]
实际上我对云服务器部署流程不是很清楚(而且不同的服务器可能操作也有不同)。如果想配置在服务器，可以根据配置教程里面的基本流程(安装python3...安装模块...上传代码........)一步步百度解决。

**Comment by cuncun-edg** [comment]
centos的定时任务，环境不好弄，手动执行没问题，定时就不执行


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IceTiki/ruoli-sign-optimization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月3日(星期五) 中午11:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IceTiki/ruoli-sign-optimization] 可以写给用腾讯云服务器部署的教程吗？ (Issue #67)





 
实际上我对云服务器部署流程不是很清楚(而且不同的服务器可能操作也有不同)。如果想配置在服务器，可以根据配置教程里面的基本流程(安装python3...安装模块...上传代码........)一步步百度解决。

**Comment by 532355805** [comment]
腾讯帮助文档有怎么配置触发器的教程 很简单

**Comment by cuncun-edg** [comment]
给个地址咯
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IceTiki/ruoli-sign-optimization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月4日(星期六) 晚上9:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IceTiki/ruoli-sign-optimization] 可以写给用腾讯云服务器部署的教程吗？ (Issue #67)





 
腾讯帮助文档有怎么配置触发器的教程 很简单

**Comment by 532355805** [comment]
htt删ps://clo删ud.ten删cent.com/docu删ment/produ删ct/583/97删08

**Comment by cuncun-edg** [comment]
你搞错了，我说的是需要服务器部署，而不是用云函数部署




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IceTiki/ruoli-sign-optimization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月4日(星期六) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IceTiki/ruoli-sign-optimization] 可以写给用腾讯云服务器部署的教程吗？ (Issue #67)





 
htt删ps://clo删ud.ten删cent.com/docu删ment/produ删ct/583/97删08

**Comment by IceTiki** [comment]
> centos的定时任务，环境不好弄，手动执行没问题，定时就不执行
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "IceTiki/ruoli-sign-optimization" ***@***.***&gt;; 发送时间:&nbsp;2022年6月3日(星期五) 中午11:42 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [IceTiki/ruoli-sign-optimization] 可以写给用腾讯云服务器部署的教程吗？ (Issue #67) 实际上我对云服务器部署流程不是很清楚(而且不同的服务器可能操作也有不同)。如果想配置在服务器，可以根据配置教程里面的基本流程(安装python3...安装模块...上传代码........)一步步百度解决。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这个好像和依赖(模块)有关，有可能是你手动运行时候的python版本和定时运行的python版本不一样导致模块的安装位置不一样...我也遇到过，但也是懵懵懂懂地解决的

**Comment by Jaincen** [comment]
> 你搞错了，我说的是需要服务器部署，而不是用云函数部署



Duplicate of #

> centos的定时任务，环境不好弄，手动执行没问题，定时就不执行
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "IceTiki/ruoli-sign-optimization" ***@***.***&gt;; 发送时间:&nbsp;2022年6月3日(星期五) 中午11:42 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [IceTiki/ruoli-sign-optimization] 可以写给用腾讯云服务器部署的教程吗？ (Issue #67) 实际上我对云服务器部署流程不是很清楚(而且不同的服务器可能操作也有不同)。如果想配置在服务器，可以根据配置教程里面的基本流程(安装python3...安装模块...上传代码........)一步步百度解决。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

考虑以下问题：
1. centos 系统时间
2. 是否重启定时服务
