### ISSUE TITLE
签到任务标题

### ISSUE THREAD

**Issue by Ben11123** [IceTiki/ruoli-sign-optimization#69]
我们每天查寝任务推送的标题不一样，比如 星期一查寝，星期二查寝，星期三查寝........    查寝配置里面选择检测标题执行的话能不能设置多标题，如果可以用什么符号隔开
title: str:星期一查寝 # [str:签到任务的标题|0:取最后一个未签到的任务]

**Comment by IceTiki** [comment]
> 我们每天查寝任务推送的标题不一样，比如 星期一查寝，星期二查寝，星期三查寝........    查寝配置里面选择检测标题执行的话能不能设置多标题，如果可以用什么符号隔开
> title: str:星期一查寝 # [str:签到任务的标题|0:取最后一个未签到的任务]

可以用正则匹配(看用户配置高级教程)

**Comment by IceTiki** [comment]
举个例子
`星期.查寝`
`.`是正则的通配符

**Comment by IceTiki** [comment]
正则参考
`星期.查寝`
`.`是正则的通配符
不过你不能直接填正则进去，你要根据用户配置高级教程中超级字符串描述的格式填
