### ISSUE TITLE
若离消息推送失败|'msg'

### ISSUE THREAD

**Issue by Jaya0455** [IceTiki/ruoli-sign-optimization#7]
大哥，信息收集能成功，但是我配置单独推送后，用若离大哥的api，报如下错误
![image](https://user-images.githubusercontent.com/82650452/147376555-afaef3db-e63f-4ac3-972c-49a066eec5e9.png)

config文件里面我是这样配置的
![image](https://user-images.githubusercontent.com/82650452/147376567-52f0136e-97f6-456f-a4e9-74de6a8adf58.png)

求指点！:smile:

**Comment by IceTiki** [comment]
目前来看是给若离API发送请求后，回复中找不到msg字段。
改成试了一下，发送请求后没有回复，有可能是若离的API出问题了。
这个功能我一直没有维护，可能在未来删掉。
邮箱推送请试着改用**pushplus或SMTP**替代。
