### ISSUE TITLE
运行过程中，一直卡在这个

### ISSUE THREAD

**Issue by President-M** [IceTiki/ruoli-sign-optimization#72]
<img width="1034" alt="截屏2022-06-22 23 36 37" src="https://user-images.githubusercontent.com/88828830/175073284-f9b4d561-7027-4045-ab80-1065bbfa0bf2.png">

**Comment by IceTiki** [comment]
> <img width="1034" alt="截屏2022-06-22 23 36 37" src="https://user-images.githubusercontent.com/88828830/175073284-f9b4d561-7027-4045-ab80-1065bbfa0bf2.png">
> 

这是日志还没加载全，不是卡了

**Comment by President-M** [comment]
<img width="1097" alt="截屏2022-06-27 15 47 53" src="https://user-images.githubusercontent.com/88828830/175887885-726f8361-f881-4d4e-9a0f-2145a25d9748.png">
<img width="1097" alt="截屏2022-06-27 15 47 34" src="https://user-images.githubusercontent.com/88828830/175887917-d204e4bd-0254-428e-acdd-3fdac0d91d01.png">

**Comment by President-M** [comment]
<img width="1097" alt="截屏2022-06-27 15 47 53" src="https://user-images.githubusercontent.com/88828830/175888005-4ec0c03e-224a-4513-a813-a234f2ea8616.png">
<img width="1097" alt="截屏2022-06-27 15 47 34" src="https://user-images.githubusercontent.com/88828830/175888024-a3e6ae92-7fff-4038-bd37-1e0795b20aea.png">
一直卡在这里，然后超过调用时间3600秒，就调用失败了

**Comment by IceTiki** [comment]
有完整日志吗。一般而言很少在国内平台出现网那么卡的情况，重试依然是这样吗(注意以下哪一部分耗时特别多)
