### ISSUE TITLE
表单尾部有个单选添加如何解决

### ISSUE THREAD

**Issue by Lulululx** [IceTiki/ruoli-sign-optimization#74]
![QQ图片20220626000809](https://user-images.githubusercontent.com/61971083/175781749-899cf1a0-69d0-4211-9d29-0e76faa03948.jpg)
如图，学校有个疫情填报最后需要点击个勾选框应该如何修改？

**Comment by IceTiki** [comment]
这个好像不需要配置的?
你试试运行一下有没有报错

**Comment by Lulululx** [comment]
> 
我们学校有两个疫情打卡的任务，使用了gethistory，只有一个没有最后那个选项的完成了打卡，而图上的这个却没有填报，不知道是什么原因
` type: 0 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName:  # 学校全称
    username: "" # 学号或者工号
    password: "" # 密码
    getHistorySign: True
    # 一般需填项-------
    signLevel: 1 # 签到等级[1:仅填报未填报的任务|2:已填报的任务也重复填报]
    title: 0 # [str:签到任务的标题|0:取最后一个未签到的任务]
    checkTitle: 1 # 是否检查表单各项的标题[1:检查|0:不检查]`
仅这样修改配置文件后面的内容全部注释了，不知可行？

**Comment by Lulululx** [comment]
![Uploading 屏幕截图 2022-06-26 130809.png…]()
