### ISSUE TITLE
请问阿里云一直报错没有在 index.py 文件中找到方法 initializer怎么回事

### ISSUE THREAD

**Issue by wenxywang** [IceTiki/ruoli-sign-optimization#79]
![image](https://user-images.githubusercontent.com/24751354/177685772-1c6d1343-5b66-43d9-96a1-e9d874eb2ddc.png)
![image](https://user-images.githubusercontent.com/24751354/177685807-0d471c2a-a990-405a-946d-bdd1f935d962.png)

**Comment by wenxywang** [comment]
另外老版本的代码在腾讯云上还可以用，新版代码无论在腾讯云哪个地区都说ip被屏蔽，这是为啥

**Comment by IceTiki** [comment]
> 另外老版本的代码在腾讯云上还可以用，新版代码无论在腾讯云哪个地区都说ip被屏蔽，这是为啥


这个和代码版本无关。IP被屏蔽是因为太多人用腾讯云云函数，旧版本也会出现这种问题。

**Comment by IceTiki** [comment]
关于`initializer`的问题
请把`函数配置`-`实例生命周期回调`里面的设置删掉

**Comment by wenxywang** [comment]
solved。 thx。
