### ISSUE TITLE
可否设置 推送信息自定义

### ISSUE THREAD

**Issue by leieerr** [IceTiki/ruoli-sign-optimization#85]
![IMG_20220818_113633](https://user-images.githubusercontent.com/106761073/185288118-7c1782ed-6fd2-4081-995b-03016e78c699.jpg)
[默认备注名]
Runing at 时间，
以及后续的时间，完成，错误，等等可否自定义是否推送此文字

**Comment by leieerr** [comment]
推送时，只能看到标题，不能看到Success的提示
可否优化设置成这样
『[V-T𝟑.𝟗.𝟎d]全局签到情况(𝟏/𝟏)』
--𝟐𝟏𝟓𝟒𝟎𝟏𝟎𝟔𝟐𝟗|𝟏
--[SUCCESS]每日健康打卡（上午）

**Comment by IceTiki** [comment]
> 推送时，只能看到标题，不能看到Success的提示
> 可否优化设置成这样
> 『[V-T𝟑.𝟗.𝟎d]全局签到情况(𝟏/𝟏)』
> --𝟐𝟏𝟓𝟒𝟎𝟏𝟎𝟔𝟐𝟗|𝟏
> --[SUCCESS]每日健康打卡（上午）
> 

其实标题的数字就代表签到是否成功
那个(1/1)就是(成功数/全部数)

**Comment by leieerr** [comment]
大佬辛苦啦，感谢感谢
