### ISSUE TITLE
登录出错

### ISSUE THREAD

**Issue by honorslife** [IceTiki/ruoli-sign-optimization#88]
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓看这里↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
[list index out of range]
Traceback (most recent call last):
  File "index.py", line 157, in main
    today.login()
  File "/root/today_cap_v2/ruoli-sign-optimization/todayLoginService.py", line 102, in login
    self.checkLogin()
  File "/root/today_cap_v2/ruoli-sign-optimization/todayLoginService.py", line 96, in checkLogin
    self.session.cookies = self.loginEntity.login()
  File "/root/today_cap_v2/ruoli-sign-optimization/login/casLogin.py", line 132, in login
    msg = soup.select('#formErrorTip2')[0].get_text()
IndexError: list index out of range

↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑看这里↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

**Comment by IceTiki** [comment]
发一下你教务系统的网址，似乎是需要适配

**Comment by honorslife** [comment]
有两个http://jwxt.jlnu.edu.cn/   http://my.jlnu.edu.cn/ywtb-portal/standard/index.html#/hall
之前还可以使用，然后假期两个月没有签到任务，重新才发现嗝屁了

**Comment by IceTiki** [comment]
http://authserver.jlnu.edu.cn/authserver
有时间我试着适配下

**Comment by honorslife** [comment]
> http://authserver.jlnu.edu.cn/authserver 有时间我试着适配下

ok，感谢

**Comment by IceTiki** [comment]
有联系方式吗，我想找时间测试下

**Comment by honorslife** [comment]
> 有联系方式吗，我想找时间测试下
QQ 2393751066微信同号

**Comment by IceTiki** [comment]
![image](https://user-images.githubusercontent.com/61530581/187722361-dbb793a5-c56d-47ee-900d-0d269110ed58.png)

**Comment by honorslife** [comment]
> ![image](https://user-images.githubusercontent.com/61530581/187722361-dbb793a5-c56d-47ee-900d-0d269110ed58.png)
![1661961095016](https://user-images.githubusercontent.com/35758821/187723086-b7680d12-743a-4a65-af96-2c9bf3e8b8d7.png)
