### ISSUE TITLE
No module named 'actions.autoSign'

### ISSUE THREAD

**Issue by wyek1n** [IceTiki/ruoli-sign-optimization#9]
大佬求助

root@WYE-Debian:~/school# python3 index.py

Traceback (most recent call last):
File "/root/school/index.py", line 4, in <module>
from actions.autoSign import AutoSign
ModuleNotFoundError: No module named 'actions.autoSign'

**Comment by IceTiki** [comment]
原因可能是你删依赖重新安装的时候不小心删了action文件夹。
建议重新拉取代码(以及重新安装依赖)
