### ISSUE TITLE
关于UA伪随机 提供一个包

### ISSUE THREAD

**Issue by Ronald-247533** [IceTiki/ruoli-sign-optimization#90]
fake_useragent

最近在研究某些漏洞的exp的时候发现了这个包 查看之后发现是在字典里随机取一个UA去使用。感觉可行（但毕竟金某平台还没有对UA下手 感觉上没必要

**Comment by IceTiki** [comment]
嗯。
现在除非必要不会随便增加依赖模块，等他哪一天下手了再说好了。
