### ISSUE TITLE
验证码验签失败

### ISSUE THREAD

**Issue by 1216332750** [IceTiki/ruoli-sign-optimization#91]
辅导员上了新的查寝验证方式，需要先通过验证码才能查寝

**Comment by IceTiki** [comment]
愿闻其详

**Comment by IceTiki** [comment]
不会是谷歌验证的那种类型吧

**Comment by ygk666** [comment]
是的，那种hcaptcha的

**Comment by IceTiki** [comment]
> > 不会是谷歌验证的那种类型吧
> 
> hcaptcha那种选择则图片中的什么什么的

唔......这种东西我要是能破解恐怕月薪百万了......
如果不是在准备考研我可能真的会去研究 神经网络
目前来说，最多通过投诉验证码太难来使你们辅导员关闭这种验证码功能。（一般比较难破解的验证码对人类也很不舒服）

**Comment by ygk666** [comment]
> > > 不会是谷歌验证的那种类型吧
> > 
> > 
> > hcaptcha那种选择则图片中的什么什么的
> 
> 唔......这种东西我要是能破解恐怕月薪百万了...... 如果不是在准备考研我可能真的会去研究 神经网络 目前来说，最多通过投诉验证码太难来使你们辅导员关闭这种验证码功能。（一般比较难破解的验证码对人类也很不舒服）

换个思路有没有办法跳过捏，此外我好像又看到国外一家付费的网站提供此类服务

**Comment by IceTiki** [comment]
> > > > 不会是谷歌验证的那种类型吧
> > > 
> > > 
> > > hcaptcha那种选择则图片中的什么什么的
> > 
> > 唔......这种东西我要是能破解恐怕月薪百万了...... 如果不是在准备考研我可能真的会去研究 神经网络 目前来说，最多通过投诉验证码太难来使你们辅导员关闭这种验证码功能。（一般比较难破解的验证码对人类也很不舒服）
> 
> 换个思路有没有办法跳过捏，此外我好像又看到国外一家付费的网站提供此类服务

不太可能有办法跳过。除非服务端代码写得太水太烂（非正常情况），不认为有空子可以钻。
验证码这种东西非常普遍，相关技术应该非常成熟，相关代码大概率也是从专门提供这类服务的厂商获取的。

**Comment by IceTiki** [comment]
倒是若离近期好像有点想做个识别API，或许你可以等下他的消息(

**Comment by ygk666** [comment]
> 倒是若离近期好像有点想做个识别API，或许你可以等下他的消息(

今天那种验证码没了，不会在APP上出现，但是日志反馈还是验证码验签失败

**Comment by ygk666** [comment]
> > 倒是若离近期好像有点想做个识别API，或许你可以等下他的消息(
> 
> 今天那种验证码没了，不会在APP上出现，但是日志反馈还是验证码验签失败

不知道是哪里卡住了

**Comment by ygk666** [comment]
> > > 倒是若离近期好像有点想做个识别API，或许你可以等下他的消息(
> > 
> > 
> > 今天那种验证码没了，不会在APP上出现，但是日志反馈还是验证码验签失败
> 
> 不知道是哪里卡住了

『{'code': '2210060000', 'message': '验证码验签失败'}』且任务状态仍是未签到

**Comment by IceTiki** [comment]
你试试用自己的电脑执行，然后根据用户配置高级教程，把设备类型什么的都填进配置里面试试？

**Comment by IceTiki** [comment]
填 杂项-隐藏项目 相关的那些内容进配置文件

**Comment by IceTiki** [comment]
如果手机没有验证码，云函数有。我猜测是因为设备或者IP改变了。
当然也可能是因为签到流程有变化，不过近期我比较忙可能没法测试。

**Comment by ygk666** [comment]
> 如果手机没有验证码，云函数有。我猜测是因为设备或者IP改变了。 当然也可能是因为签到流程有变化，不过近期我比较忙可能没法测试。



> 填 杂项-隐藏项目 相关的那些内容进配置文件

我在云函数中填入配置依旧不行

**Comment by ygk666** [comment]
> 如果手机没有验证码，云函数有。我猜测是因为设备或者IP改变了。 当然也可能是因为签到流程有变化，不过近期我比较忙可能没法测试。

辛苦了，这个问题也困扰我好多天

**Comment by ygk666** [comment]
> > 你试试用自己的电脑执行，然后根据用户配置高级教程，把设备类型什么的都填进配置里面试试？
> 
> 电脑应该运行文件包里的哪个文件

设备类型中的设备号怎么查找，需要更换吗

**Comment by ygk666** [comment]
> 如果手机没有验证码，云函数有。我猜测是因为设备或者IP改变了。 当然也可能是因为签到流程有变化，不过近期我比较忙可能没法测试。



> 如果手机没有验证码，云函数有。我猜测是因为设备或者IP改变了。 当然也可能是因为签到流程有变化，不过近期我比较忙可能没法测试。

嗯嗯希望大佬有空时候能测试下，太痛苦了

**Comment by Mosimita** [comment]
一样的问题，昨天抓了一下手机端的包，今天试了一下用真机的deviceid和参数一样是报{'code': '2210060000', 'message': '验证码验签失败'}，排查了一下发现了个比较可疑的API，不知道能不能逆向一下，地址是https://***.campusphere.net/wec-counselor-attendance-apps/student/attendance/getCheatModuleStatus

**Comment by Mosimita** [comment]
实验了一下，用代理挂到vps上去签到真机是可以签上的，没有异常，也没有报验证码，vps的ip应该是干净的，所有能填的都已经填上了，感觉应该是加了一些别的检测

**Comment by ygk666** [comment]
我刚才换了一部手机登录查寝，跳出了谷歌那种验证，然后点击重新定位也会出现

**Comment by ygk666** [comment]
应该是切换设备后触发了验证

**Comment by IceTiki** [comment]
> 应该是切换设备后触发了验证

可能是产生了新的登陆状态

**Comment by CodeRookieIV** [comment]
我大概找到了解决的方法了，但是抓的包丢了😭

**Comment by CodeRookieIV** [comment]
> > > 应该是切换设备后触发了验证
> > 
> > 
> > 可能是产生了新的登陆状态
> 
> 有可能退出今日校园然后又重新登陆也会产生验证码

是新的登录状态，因为换了设备，在检查是否需要验证码的时候，请求了一个本地设备的id，换设备就会弹出来。我在研究验证码的时候，发现了，每张图片会加上今天的日期水印。我分析了一下，找到了原验证码的库。大约900多张，有分类的。我的解决方案是把原图片都下载下来，然后请求获取验证码，把验证码的hash值获取，利用Dhash算法，比较他们的相似度，因为就差个水印，比较起来也是挺方便的。但是最后提交的地址和数据包格式忘记了，还等等晚上再试试

**Comment by IceTiki** [comment]
能留一个联系方式吗(期望qq)

**Comment by IceTiki** [comment]
> 我大概找到了解决的方法了，但是抓的包丢了😭

能留一个联系方式吗(期望qq)

**Comment by CodeRookieIV** [comment]
> > 我大概找到了解决的方法了，但是抓的包丢了😭
> 
> 能留一个联系方式吗(期望qq)

1197387947

**Comment by Zclojh** [comment]
> > > > 应该是切换设备后触发了验证
> > > 
> > > 
> > > 可能是产生了新的登陆状态
> > 
> > 
> > 有可能退出今日校园然后又重新登陆也会产生验证码
> 
> 是新的登录状态，因为换了设备，在检查是否需要验证码的时候，请求了一个本地设备的id，换设备就会弹出来。我在研究验证码的时候，发现了，每张图片会加上今天的日期水印。我分析了一下，找到了原验证码的库。大约900多张，有分类的。我的解决方案是把原图片都下载下来，然后请求获取验证码，把验证码的hash值获取，利用Dhash算法，比较他们的相似度，因为就差个水印，比较起来也是挺方便的。但是最后提交的地址和数据包格式忘记了，还等等晚上再试试

请问可以告诉我一下是怎么找到的原验证码库吗，万分感谢

**Comment by IceTiki** [comment]
为了防止内鬼，暂时关闭issue。
未来可能会提供一个验证码识别和加密API以完成签到流程。

**Comment by zhuzhutudou** [comment]
> 实验了一下，用代理挂到vps上去签到真机是可以签上的，没有异常，也没有报验证码，vps的ip应该是干净的，所有能填的都已经填上了，感觉应该是加了一些别的检测

能教一下吗
