### ISSUE TITLE
ValueError: check_hostname requires server_hostname

### ISSUE THREAD

**Issue by Ao-Wu-Benjamin** [IceTiki/ruoli-sign-optimization#93]

**Comment by IceTiki** [comment]
请提供更完整的日志

**Comment by Ao-Wu-Benjamin** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IceTiki/ruoli-sign-optimization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月18日(星期天) 下午3:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IceTiki/ruoli-sign-optimization] ValueError: check_hostname requires server_hostname (Issue #93)





 
请提供更完整的日志

**Comment by Ao-Wu-Benjamin** [comment]
[LOG#t=2022-09-18--15-47-54##.txt](https://github.com/IceTiki/ruoli-sign-optimization/files/9593324/LOG.t.2022-09-18--15-47-54.txt)

**Comment by IceTiki** [comment]
目前来看是登录状态有问题，目前猜测的教务系统的问题，可能过几天就好了
前天有另一个人（也是宜宾学院）也出现登录失败，过来段时间又好了

**Comment by IceTiki** [comment]
另外可以试着排查下
1. 账号密码错误
2. 教务系统出问题了，试一下[手动登陆](http://authserver.yibinu.edu.cn/authserver/login?service=https%3A%2F%2Fyibinu.campusphere.net%2Fwec-portal-mobile%2Fclient%2F)

**Comment by Ao-Wu-Benjamin** [comment]
解决了，就是登录教务处的时候搞了个强制绑手机号。手动绑了就行了。谢谢大佬
