### ISSUE TITLE
待解决的问题: 查寝验证码

### ISSUE THREAD

**Issue by IceTiki** [IceTiki/ruoli-sign-optimization#94]
本issue仅标记存在该问题，不进行讨论

**Comment by Ronald-247533** [comment]
是指物体识别那种验证码？

**Comment by IceTiki** [comment]
> 是指物体识别那种验证码？

是的

**Comment by ygk666** [comment]
1

**Comment by IceTiki** [comment]
2

**Comment by Ronald-247533** [comment]
baidu识图api 貌似可以尝试一下哈

**Comment by IceTiki** [comment]
> baidu识图api 貌似可以尝试一下哈

现在解决方案其实已经基本成型了，只是在筹备实装。

**Comment by Ronald-247533** [comment]
> > baidu识图api 貌似可以尝试一下哈
> 
> 现在解决方案其实已经基本成型了，只是在筹备实装。

牛

**Comment by IceTiki** [comment]
目前防内鬼，建议不要在讨论区讲可能的解决方案

**Comment by IceTiki** [comment]
毕竟代挂一多，抢排行榜的人一多。验证迟早升级。

**Comment by ygk666** [comment]
> 毕竟代挂一多，抢排行榜的人一多。验证迟早升级。

理解，抢排行榜的纯没脑子

**Comment by Ronald-247533** [comment]
确实 一帮nc

**Comment by Copyctrlc** [comment]
今日校园信息收集初次提交的deviceId会推送验证码，解决方案是使用手机进行一次验证码，抓包获取提交的字段中的deviceID，添加到新的deviceID字段
抓包参考：可使用小黄鸟httpCanary等，自行百度
[https://github.com/Jerry-zhuang/HQU-FxxkCPDaily](url)

**Comment by IceTiki** [comment]
下载最新的代码并运行一下，也许可以自己找到解决方案...
