### ISSUE TITLE
信息收集验证码

### ISSUE THREAD

**Issue by q82415670** [IceTiki/ruoli-sign-optimization#95]
信息收集也有验证码了 烦

**Comment by q82415670** [comment]
![13770473a2e1f019acccda5bad45382](https://user-images.githubusercontent.com/110165439/191556024-2fd0681c-8488-4553-9e8d-b75aa2c856cd.jpg)
如图

**Comment by MeetinaXD** [comment]
刚想说这个问题，而且验证码有时候会有好几轮。

**Comment by q82415670** [comment]
经测试 好像签到过一次的设备就不需要验证码了

**Comment by CodeRookieIV** [comment]
> 刚想说这个问题，而且验证码有时候会有好几轮。

已经解决了，后续可能会放出API，不再公开化了

**Comment by leieerr** [comment]
腾讯云OCR能解决这个不

**Comment by ygk666** [comment]
> > 刚想说这个问题，而且验证码有时候会有好几轮。
> 
> 已经解决了，后续可能会放出API，不再公开化了

给这个烦死了救救

**Comment by cyxnzb** [comment]
应该是辅导猫最近更新了，金x那边有注意到，规避的话也是有办法的,OCR

**Comment by IceTiki** [comment]
下载最新的代码并运行一下，也许可以自己找到解决方案...
