### ISSUE TITLE
图片验证码

### ISSUE THREAD

**Issue by zhuzhutudou** [IceTiki/ruoli-sign-optimization#97]
![80BC8FDA-6F9C-461E-9F1B-4C985D0D36E8](https://user-images.githubusercontent.com/114417215/192432565-3104f286-9efe-4d6f-9833-80e892cfa25e.png)
救救😭

**Comment by zhuzhutudou** [comment]
device id 怎么使用呀

**Comment by zhuzhutudou** [comment]
> 

添加了device id还是上面的那种情况

**Comment by IceTiki** [comment]
> > 
> 
> 添加了device id还是上面的那种情况

可能的原因
1. deviceId以抓包为准，设备ID可能和实际提交不相同
2. 填写后，要用手机手签一次
3. 其他未知原因

**Comment by zhuzhutudou** [comment]
> > > 
> > 
> > 
> > 添加了device id还是上面的那种情况
> 
> 可能的原因
> 
> 1. deviceId以抓包为准，设备ID可能和实际提交不相同
> 2. 填写后，要用手机手签一次
> 3. 其他未知原因

图片还是验证失败

**Comment by zhuzhutudou** [comment]
抓取的包什么字段后面是device id呀试了好多个

**Comment by xvJobs** [comment]
> deviceId的生成机制比较迷。只能通过抓包获取，一般在提交表单的时候会附带deviceId。 抓包以后请参看用户配置高级教程进行填入

1个deviceId只能打一个账号吗

**Comment by huajixiaoyan** [comment]
> 抓取的包什么字段后面是device id呀试了好多个

你知道了吗。

**Comment by IceTiki** [comment]
下载最新的代码并运行一下，也许可以自己找到解决方案...
