### ISSUE TITLE
最近应该有些更新,希望作者可以对应更新下

### ISSUE THREAD

**Issue by cyxnzb** [IceTiki/ruoli-sign-optimization#98]
xx猫上面的提示：
近期xx猫陆续上新签到、信息收集、查寝模块的图片安全验证功能。功能上线以来，所有学生首次使用对应功能/每次更换设备/每7-14天都会随机弹出安全验证，以防止学生通过抓包等方式进行机刷等作弊行为。
另：
或许可以试试抓包看看能不能抓到js.map

**Comment by Well2333** [comment]
此issue已被反复提出，目前正在积极解决，请到已有issue下进行评论

**Comment by IceTiki** [comment]
你更新代码并运行一下，也许可以自己找到解决方案...
